Repository maistra/istio-operator, pull requests merged in 2020-06, with the labels that each got.

#452 MAISTRA-1504 Fix import k8s.io/kubernetes/pkg/apis/rbac
  go.mod
  pkg/controller/common/test/controller-test-utils.go
Labels: okay to merge, ready to merge, size/XS

#371 Do not hardcode GOARCH
  build/build.sh
Labels: ok-to-test, okay to merge, ready to merge, size/XS

#453 MAISTRA-1358: OAuth sidecars should trust cluster's CA
  build/patch-grafana.sh
  build/patch-prometheus.sh
  resources/helm/overlays/istio/charts/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/overlays/istio/charts/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/overlays/istio/templates/trusted-ca-bundle-cm.yaml
  resources/helm/v1.1/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/prometheus/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/v1.1/istio/charts/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/v1.1/istio/templates/trusted-ca-bundle-cm.yaml
Labels: okay to merge, size/L

#442 MAISTRA-1496 Ensure lastTransitionTime isn't updated when no transition occurs
  pkg/apis/maistra/v1/status.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge, size/M

#457 MAISTRA-1496 Ensure lastTransitionTime isn't updated when no transition occurs
  pkg/apis/maistra/v1/status.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge, size/M

#456 MAISTRA-1358: OAuth sidecars should trust cluster's CA
  build/patch-grafana.sh
  build/patch-prometheus.sh
  resources/helm/overlays/istio/charts/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/overlays/istio/charts/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/overlays/istio/templates/trusted-ca-bundle-cm.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/role.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/rolebindings.yaml
  resources/helm/v1.1/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/prometheus/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/v1.1/istio/charts/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/v1.1/istio/templates/trusted-ca-bundle-cm.yaml
  resources/helm/v1.2/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.2/istio/charts/prometheus/templates/deployment.yaml
  resources/helm/v1.2/istio/charts/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/v1.2/istio/charts/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/v1.2/istio/templates/trusted-ca-bundle-cm.yaml
Labels: okay to merge, ready to merge, size/L

#459 MAISTRA-1512: Identify https based remote repository URIs
  Makefile
Labels: okay to merge, size/XS

#397 MAISTRA-1331 ensure jaeger and kiali crds are available when enabling…
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
Labels: okay to merge, size/L

#410 MAISTRA-1352 remove unused helm templates
  Makefile
  pkg/controller/servicemesh/controlplane/integration_test.go
  resources/helm/v1.0/istio-init/files/crd-certmanager-10.yaml
  resources/helm/v1.0/istio-init/files/crd-certmanager-11.yaml
  resources/helm/v1.0/istio-init/templates/clusterrole.yaml
  resources/helm/v1.0/istio-init/templates/clusterrolebinding.yaml
  resources/helm/v1.0/istio-init/templates/configmap-crd-10.yaml
  resources/helm/v1.0/istio-init/templates/configmap-crd-11.yaml
  resources/helm/v1.0/istio-init/templates/configmap-crd-certmanager-10.yaml
  resources/helm/v1.0/istio-init/templates/configmap-crd-certmanager-11.yaml
  resources/helm/v1.0/istio-init/templates/job-crd-10.yaml
  resources/helm/v1.0/istio-init/templates/job-crd-11.yaml
  resources/helm/v1.0/istio-init/templates/job-crd-certmanager-10.yaml
  resources/helm/v1.0/istio-init/templates/job-crd-certmanager-11.yaml
  resources/helm/v1.0/istio-init/templates/serviceaccount.yaml
  resources/helm/v1.0/istio/charts/tracing/templates/deployment-zipkin.yaml
  resources/helm/v1.1/istio-init/files/crd-certmanager-10.yaml
  resources/helm/v1.1/istio-init/files/crd-certmanager-11.yaml
  resources/helm/v1.1/istio-init/templates/clusterrole.yaml
  resources/helm/v1.1/istio-init/templates/clusterrolebinding.yaml
  resources/helm/v1.1/istio-init/templates/configmap-crd-10.yaml
  resources/helm/v1.1/istio-init/templates/configmap-crd-11.yaml
  resources/helm/v1.1/istio-init/templates/configmap-crd-14.yaml
  resources/helm/v1.1/istio-init/templates/configmap-crd-certmanager-10.yaml
  resources/helm/v1.1/istio-init/templates/configmap-crd-certmanager-11.yaml
  resources/helm/v1.1/istio-init/templates/job-crd-10.yaml
  resources/helm/v1.1/istio-init/templates/job-crd-11.yaml
  resources/helm/v1.1/istio-init/templates/job-crd-14.yaml
  resources/helm/v1.1/istio-init/templates/job-crd-certmanager-10.yaml
  resources/helm/v1.1/istio-init/templates/job-crd-certmanager-11.yaml
  resources/helm/v1.1/istio-init/templates/serviceaccount.yaml
  resources/helm/v1.1/istio/charts/grafana/templates/tests/test-grafana-connection.yaml
  resources/helm/v1.1/istio/charts/kiali/templates/tests/test-kiali-connection.yaml
  resources/helm/v1.1/istio/charts/prometheus/templates/tests/test-prometheus-connection.yaml
  resources/helm/v1.1/istio/charts/security/templates/tests/test-citadel-connection.yaml
  resources/helm/v1.1/istio/charts/tracing/templates/deployment-zipkin.yaml
  resources/helm/v1.1/istio/charts/tracing/templates/tests/test-tracing-connection.yaml
  resources/helm/v1.1/istio/files/injection-template.yaml
  resources/helm/v1.1/istio/values.yaml
Labels: okay to merge, ready to merge, size/XXL

#460 MAISTRA-1374: support multiple multus CNI interfaces
  build/patch-charts.sh
  resources/helm/v1.1/istio/templates/sidecar-injector-configmap.yaml
Labels: okay to merge, size/XS

#401 MAISTRA-1339 Set SMMR status when reconciliation skipped due to invalid SMCP
  pkg/apis/maistra/v1/servicemeshmemberroll_types.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/L

#404 MAISTRA-1349 Update readiness during installation
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/S

#463 MAISTRA-1555: Pull in 1.1.2+3 metadata
  build/generate-manifests.sh
  manifests-servicemesh/1.1.2.3/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.2.3/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.2.3/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.2.3/servicemeshoperator.v1.1.2+3.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: size/XL

#465 MAISTRA-1534: Update operator metadata for 1.1.3
  build/generate-manifests.sh
  manifests-maistra/1.1.3/maistraoperator.v1.1.3.clusterserviceversion.yaml
  manifests-maistra/1.1.3/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/1.1.3/servicemeshmemberrolls.crd.yaml
  manifests-maistra/1.1.3/servicemeshmembers.crd.yaml
  manifests-maistra/maistra.package.yaml
  manifests-servicemesh/1.1.3/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.3/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.3/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.3/servicemeshoperator.v1.1.3.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: size/XXL

#461 MAISTRA-1523 Install some control plane components in parallel
  pkg/controller/common/test/client.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
  pkg/controller/servicemesh/controlplane/manifestprocessing_test.go
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge, size/L

#468 MAISTRA-1594 Update operator metadata for Maistra 1.1.4
  build/generate-manifests.sh
  deploy/servicemesh-operator.yaml
  manifests-servicemesh/1.1.4/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.4/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.4/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.4/servicemeshoperator.v1.1.4.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: size/XL

#475 Fix reconciler_test.go (doesn't compile)
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: size/XS

#474 MAISTRA-1604 Ensure maps in SMCP.status.lastAppliedConfiguration are actually modified
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, ready to merge, size/S
