Repository maistra/istio-operator, pull requests merged in 2020-10, with the labels that each got.

#568 Changes to the Jaeger templates to avoid schema validation issues
  resources/helm/overlays/istio-telemetry/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/overlays/istio-telemetry/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/v2.0/istio-telemetry/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/v2.0/istio-telemetry/tracing/templates/jaeger-production-elasticsearch.yaml
Labels: ok-to-test, okay to merge, size/M

#569 MAISTRA-1330 set global.istioNamespace when rendering 1.x charts
  pkg/controller/versions/rendering_strategy_v1_x.go
Labels: okay to merge, ready to merge, size/XS

#573 MAISTRA-1885 Include manifest generation in `gen` target
  Makefile
  build/generate-manifests.sh
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: okay to merge, size/XL

#575 MAISTRA-1889 Fix 3scale adapter tag
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: okay to merge, ready to merge, size/S

#571 MAISTRA-1878 Align ServiceMeshExtension CRD with maistra/istio
  Makefile
  build/generate-crds.sh
  build/generate-manifests.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-servicemesh/2.0.0/servicemeshextensions.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
  pkg/apis/maistra/v1alpha1/servicemeshextension_types.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  resources/helm/overlays/istio-init/files/servicemeshextensions.extensions.maistra.io.crd.yaml
  resources/helm/v2.0/istio-init/files/servicemeshextensions.extensions.maistra.io.crd.yaml
Labels: okay to merge, ready to merge, size/L

#547 MAISTRA-1799 Reconciler now checks if Prometheus is enabled when Kiali is enabled
  pkg/apis/maistra/status/status.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/versions/strategy_v1_0.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/util.go
  pkg/controller/versions/versions.go
Labels: okay to merge, size/L

#576 MAISTRA-1896 Restrict SME permissions to mesh namespaces
  build/patch-charts.sh
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/clusterrole.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/meshclusterrole.yaml
Labels: okay to merge, ready to merge, size/S

#577 MAISTRA-1905 Add missing labels to ServiceMeshExtension CRD
  build/generate-crds.sh
  resources/helm/overlays/istio-init/files/servicemeshextensions.extensions.maistra.io.crd.yaml
  resources/helm/v2.0/istio-init/files/servicemeshextensions.extensions.maistra.io.crd.yaml
Labels: okay to merge, size/S

#584 MAISTRA-1914 Introduce DependencyMissingError status to SMCP
  pkg/apis/maistra/status/status.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/util.go
Labels: okay to merge, ready to merge, size/M

#587 MAISTRA-1916 Add switch for enabling Prometheus in the web console
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: okay to merge, size/M

#585 MAISTRA-1897: Disable ingressClassName support
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, ready to merge, size/XS

#586 MAISTRA-1915 Ensure Kiali is not shown as ready when disabled
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/XS

#581 MAISTRA-1907 Set rootNamespace in MeshConfig
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/configmap.yaml
Labels: okay to merge, size/S

#578 MAISTRA-1895 Remove CRD list/get/watch permissions
  build/patch-charts.sh
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/meshclusterrole.yaml
Labels: okay to merge, size/S

#589 MAISTRA-1722: Remove cluster-scoped permissions from istiod
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/meshclusterrole.yaml
Labels: okay to merge, ready to merge, size/S

#591 MAISTRA-1816 Set status.configuredMembers to [] when SMCP is deleted
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, ready to merge, size/XS

#590 MAISTRA-1903 Revert proxy.global.tracer renaming
  build/patch-charts.sh
  build/patch-jaeger.sh
  pkg/apis/maistra/conversion/jaeger_test.go
  pkg/apis/maistra/conversion/tracing.go
  resources/helm/v2.0/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.0/gateways/istio-ingress/templates/deployment.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/configmap.yaml
Labels: okay to merge, size/M

#592 MAISTRA-1816 Make sure we're receiving deletion events for SMCPs
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, ready to merge, size/XS

#593 MAISTRA-1766: Add support for the disconnected annotation
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
Labels: okay to merge, size/XS

#582 Re-add "Remove ca_file option in Kiali operator CR (1.0 branch)"
  README.md
  helm/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.0/istio/charts/kiali/templates/kiali-cr.yaml
Labels: ok-to-test, size/S

#583 Re-add "Remove ca_file option in Kiali operator CR"
  README.md
  resources/helm/overlays/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.0/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.1/istio/charts/kiali/templates/kiali-cr.yaml
Labels: ok-to-test, size/S

#595 MAISTRA-1900: Add a toggle for policy and telemetry types
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: okay to merge, size/M

#596 MAISTRA-1931 remove runAsUser/Group 1337 from mixer deployments
  build/patch-charts.sh
  pkg/apis/maistra/conversion/cluster.go
  pkg/apis/maistra/conversion/cluster_test.go
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/gateways_test.go
  pkg/apis/maistra/conversion/grafana_test.go
  pkg/apis/maistra/conversion/jaeger_test.go
  pkg/apis/maistra/conversion/kiali_test.go
  pkg/apis/maistra/conversion/logging_test.go
  pkg/apis/maistra/conversion/policy_test.go
  pkg/apis/maistra/conversion/prometheus_test.go
  pkg/apis/maistra/conversion/proxy_test.go
  pkg/apis/maistra/conversion/runtime_test.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/conversion/techpreviews_test.go
  pkg/apis/maistra/conversion/telemetry_test.go
  pkg/apis/maistra/conversion/threescale_test.go
  resources/helm/overlays/istio-policy/templates/configmap-envoy.yaml
  resources/helm/v2.0/istio-policy/templates/configmap-envoy.yaml
  resources/helm/v2.0/istio-policy/templates/deployment.yaml
  resources/helm/v2.0/istio-telemetry/mixer-telemetry/templates/deployment.yaml
Labels: okay to merge, ready to merge, size/XXL

#597 MAISTRA-1846 Add globs to service name regexes
  build/patch-prometheus.sh
  resources/helm/v2.0/istio-telemetry/prometheus/templates/configmap.yaml
Labels: okay to merge, ready to merge, size/XS

#600 MAISTRA-1933: Remove ca_file option in Kiali operator CR
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.0/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, ready to merge, size/XS

#599 MAISTRA-1538 Fix and improve ServiceMeshMemberRoll reconciler
  build/generate-crds.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshmemberrolls.crd.yaml
  pkg/apis/maistra/v1/servicemeshmemberroll_types.go
  pkg/apis/maistra/v1/zz_generated.deepcopy.go
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/controller/servicemesh/controlplane/addons.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/L

#598 MAISTRA-1038 Update podlocality controller to copy new labels
  pkg/controller/podlocality/controller.go
Labels: okay to merge, size/S

#601 MAISTRA-1937 Clean up API
  build/generate-crds.sh
  build/patch-charts.sh
  deploy/examples/maistra_v2_servicemeshcontrolplane_cr_auth.yaml
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/prometheus.go
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/conversion/telemetry_test.go
  pkg/apis/maistra/v1alpha1/register.go
  pkg/apis/maistra/v2/prometheus.go
  pkg/apis/maistra/v2/security.go
  pkg/apis/maistra/v2/smcp_new.yaml
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  resources/helm/overlays/istio-init/files/servicemeshextensions.maistra.io.crd.yaml
  resources/helm/overlays/wasm-extensions/templates/clusterrole.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/clusterrole.yaml
  resources/helm/v2.0/istio-init/files/servicemeshextensions.maistra.io.crd.yaml
  resources/helm/v2.0/wasm-extensions/templates/clusterrole.yaml
Labels: okay to merge, size/L

#602 MAISTRA-1941 use default name for kiali resource if unspecified
  pkg/apis/maistra/v2/jaeger.go
  pkg/apis/maistra/v2/kiali.go
  pkg/controller/servicemesh/controlplane/addons.go
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, ready to merge, size/M

#603 MAISTRA-1945 Remove fieldDependency for non-sibling fields
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: okay to merge, ready to merge, size/S

#605 MAISTRA-1938 includeInboundPorts should default to '*'
  build/patch-charts.sh
  resources/helm/v2.0/global.yaml
  resources/helm/v2.0/istio-control/istio-discovery/files/injection-template.yaml
Labels: don't squash, okay to merge, size/S

#606 MAISTRA-1955 Use json-patch to update status
  pkg/controller/common/status-patch.go
  pkg/controller/servicemesh/controlplane/integration_test.go
Labels: okay to merge, ready to merge, size/L

#608 MAISTRA-1957: remove optional version from CRDs
  build/generate-crds.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/2.0.0/servicemeshmemberrolls.crd.yaml
  manifests-maistra/2.0.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: okay to merge, size/S

#609 OSSM-284 initialize istio version endpoint
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.0/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XS

#610 MAISTRA-1867 explicit enablement of pod disruption budget
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/runtime.go
  pkg/apis/maistra/conversion/runtime_test.go
  pkg/apis/maistra/v2/runtime.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/servicemesh/controlplane/profiles_test.go
  resources/smcp-templates/v2.0/small
Labels: okay to merge, size/M

#611 MAISTRA-1902: Fix disablePolicyChecks logic in yaml template
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/configmap.yaml
Labels: okay to merge, ready to merge, size/XS

#612 MAISTRA-1964 use MergeFrom patch instead of Merge patch during reconcile
  pkg/controller/common/helm/patch.go
Labels: okay to merge, size/S
