Repository maistra/istio-operator, pull requests merged in 2020-01, with the labels that each got.

#281 MAISTRA-964: add support for exposing non service mesh services via h…
  helm/istio/templates/networkpolicy.yaml
  pkg/controller/servicemesh/memberroll/ovs_networkpolicy.go
Labels: okay to merge

#278 MAISTRA-1074 Extract common finalizer handling code
  pkg/controller/common/finalizers.go
  pkg/controller/common/util.go
  pkg/controller/servicemesh/member/controller.go
Labels: okay to merge

#283 Configure mergify to squash commits unless "don't squash" label is present
  .mergify.yml
Labels: okay to merge

#280 MAISTRA-1075 A few minor fixes
  pkg/apis/addtoscheme_maistra_v1.go
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge

#284 MAISTRA-984 Additional MemberRoll controller tests
  pkg/controller/common/test/assert/asserts.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler_test.go
  pkg/controller/servicemesh/memberroll/ovs_multitenant.go
  pkg/controller/servicemesh/memberroll/ovs_networkpolicy.go
  pkg/controller/servicemesh/memberroll/ovs_subnet.go
Labels: okay to merge

#256 OSSM-89 - Add support for ES index cleaner configuration
  helm/istio/charts/tracing/templates/jaeger-production-elasticsearch.yaml
Labels: okay to merge

#288 MAISTRA-1008 List namespaces instead of relying on SMMR.spec.members
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge

#291 MAISTRA-1092 Add test target to Makefile
  Makefile
Labels: okay to merge

#287 MAISTRA-1081 Allow users to configure the number of worker threads us…
  cmd/manager/main.go
  pkg/controller/common/helm.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge

#292 MAISTRA-1093 Ensure all tests use a client with all resource kinds us…
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler_test.go
Labels: okay to merge

#294 MAISTRA-1094 Create ReconcileControlPlane object in helper function
  pkg/controller/servicemesh/controlplane/controller_test.go
Labels: okay to merge

#297 MAISTRA-984 Add unit tests for networking strategies
  pkg/controller/common/test/assert/asserts.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
  pkg/controller/servicemesh/memberroll/ovs_multitenant.go
  pkg/controller/servicemesh/memberroll/ovs_multitenant_test.go
  pkg/controller/servicemesh/memberroll/ovs_networkpolicy.go
  pkg/controller/servicemesh/memberroll/ovs_networkpolicy_test.go
  pkg/controller/servicemesh/memberroll/ovs_subnet_test.go
Labels: okay to merge

#293 MAISTRA-1095 Don't rely on execute permission for vendored file
  build/codegen/update-generated.sh
  vendor/k8s.io/code-generator/generate-groups.sh
Labels: okay to merge

#299 always enable go modules when building
  build/build.sh
Labels: okay to merge

#301 MAISTRA-1101: Remove egress from NetworkPolicy
  helm/istio/templates/networkpolicy.yaml
Labels: okay to merge

#302 Maistra-1106: disable installation mode OwnNamespace
  tmp/build/manifest-templates/clusterserviceversion.yaml
Labels: okay to merge

#304 MAISTRA-1112 Update 1.1 operator to support Maistra 1.0.4
  resources/smcp-templates/v1.0/base
Labels: okay to merge

#300 MAISTRA-1096 Add unit tests for operator's validating webhooks
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/servicemesh/validation/common_test.go
  pkg/controller/servicemesh/validation/controlplane_test.go
  pkg/controller/servicemesh/validation/member.go
  pkg/controller/servicemesh/validation/member_test.go
  pkg/controller/servicemesh/validation/memberroll.go
  pkg/controller/servicemesh/validation/memberroll_test.go
Labels: okay to merge

#296 MAISTRA-984 Test if namespace reconciler preserves other resources
  pkg/controller/common/test/assert/asserts.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler_test.go
Labels: okay to merge

#286 MAISTRA-1057: Add IOR back
  build/manifest-templates/clusterserviceversion.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_auth.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_full.yaml
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
  resources/helm/overlays/istio/charts/gateways/templates/ior-deployment.yaml
  resources/helm/overlays/istio/charts/gateways/templates/ior-role.yaml
  resources/helm/overlays/istio/charts/gateways/templates/ior-rolebinding.yaml
  resources/helm/overlays/istio/charts/gateways/templates/ior-serviceaccount.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/ior-deployment.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/ior-role.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/ior-rolebinding.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/ior-serviceaccount.yaml
  resources/smcp-templates/v1.1/base
  resources/smcp-templates/v1.1/maistra
  resources/smcp-templates/v1.1/servicemesh
Labels: okay to merge

#305 MAISTRA-1102: Add support for discovering Calico networking
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge

#310 MAISTRA-1124 Add ControlPlaneReconciler unit tests
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/controller_test.go
  pkg/controller/servicemesh/controlplane/deleter.go
  pkg/controller/servicemesh/controlplane/hooks.go
  pkg/controller/servicemesh/controlplane/htpasswd.go
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
  pkg/controller/servicemesh/controlplane/pruner.go
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge

#312 MAISTRA-1128 Rename validation/controller.go to webhook_server.go
  pkg/controller/servicemesh/validation/webhook_server.go
  pkg/controller/servicemesh/validation/webhook_server_test.go
Labels: okay to merge

#317 MAISTRA-1131 Let `make test` run without correct remote present
  Makefile
Labels: okay to merge, size/XS

#313 Revert OSSM-81, to remove streaming-elasticsearch tracing template
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_auth.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_full.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_minimal.yaml
  resources/helm/overlays/istio/charts/tracing/templates/jaeger-streaming-elasticsearch.yaml
  resources/helm/v1.1/istio/charts/tracing/templates/jaeger-streaming-elasticsearch.yaml
Labels: okay to merge, size/L

#318 MAISTRA-1133: case insensitive network type comparison
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, size/S

#315 MAISTRA-1130 Add unit tests for operator's mutating/validating webhoo…
  pkg/controller/common/webhooks.go
  pkg/controller/servicemesh/mutatingwebhook/controller.go
  pkg/controller/servicemesh/mutatingwebhook/controller_test.go
  pkg/controller/servicemesh/validatingwebhook/controller.go
  pkg/controller/servicemesh/validatingwebhook/controller_test.go
Labels: okay to merge, size/L

#311 MAISTRA-1127 Fix inconsistent controller names in logs and events
  pkg/controller/podlocality/controller.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/mutatingwebhook/controller.go
  pkg/controller/servicemesh/validatingwebhook/controller.go
Labels: okay to merge, size/S

#321 MAISTRA-1126 Remove global log vars to ensure correct logger is used
  pkg/controller/common/util.go
  pkg/controller/podlocality/controller.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/controller_test.go
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/mutatingwebhook/controller.go
  pkg/controller/servicemesh/validatingwebhook/controller.go
Labels: okay to merge, size/L

#322 MAISTRA-1139 Add test if Member controller creates SMMR after namespace is created
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/servicemesh/member/controller_test.go
Labels: okay to merge, size/M
