Repository maistra/istio-operator, pull requests merged in 2020-04, with the labels that each got.

#392 MAISTRA-1160 Allow ingress traffic to external Jaeger on port 8443
  resources/helm/overlays/istio/templates/networkpolicy.yaml
  resources/helm/v1.1/istio/templates/networkpolicy.yaml
Labels: okay to merge, size/S

#393 add maistra logo to operator csv files
  build/manifest-templates/clusterserviceversion.yaml
  build/manifest-templates/maistra_rgb_icon_default_128px.png
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/L

#396 MAISTRA-1329 remove operator dependencies from csv
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/M

#400 MAISTRA-1340 Fix wrong ior_image name
  resources/smcp-templates/v1.1/servicemesh
Labels: okay to merge, size/XS

#402 MAISTRA-1344: Remove egress sections from NetworkPolicy
  resources/helm/overlays/istio/templates/networkpolicy.yaml
  resources/helm/v1.1/istio/templates/networkpolicy.yaml
Labels: okay to merge, size/S

#403 MAISTRA-1345: Add support for identification of Calico networking
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
Labels: okay to merge, size/L

#415 MAISTRA-1397 improve properties file loading
  cmd/manager/main.go
Labels: okay to merge, size/S

#416 OSSM-110 use ImageStream for oauth proxy image
  build/generate-manifests.sh
  build/patch-container-image.sh
  build/patch-grafana.sh
  build/patch-prometheus.sh
  cmd/manager/main.go
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  go.mod
  manifests-maistra/1.1.1/maistraoperator.v1.1.1.clusterserviceversion.yaml
  manifests-servicemesh/1.1.1/servicemeshoperator.v1.1.1.clusterserviceversion.yaml
  pkg/apis/addtoscheme_maistra_v1.go
  pkg/controller/common/config.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  resources/helm/v1.0/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.0/istio/charts/prometheus/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/prometheus/templates/deployment.yaml
  resources/smcp-templates/v1.1/servicemesh
  vendor/github.com/openshift/api/image/docker10/doc.go
  vendor/github.com/openshift/api/image/docker10/dockertypes.go
  vendor/github.com/openshift/api/image/docker10/register.go
  vendor/github.com/openshift/api/image/docker10/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/doc.go
  vendor/github.com/openshift/api/image/dockerpre012/dockertypes.go
  vendor/github.com/openshift/api/image/dockerpre012/register.go
  vendor/github.com/openshift/api/image/dockerpre012/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/doc.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/legacy.go
  vendor/github.com/openshift/api/image/v1/register.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: okay to merge, size/XXL

#417 OSSM-110 fix oauth-proxy image resolution for disconnected environments
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/S

#418 OSSM-110 fix oauth-proxy image resolution for disconnected environmen…
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/S
