Repository maistra/istio-operator, pull requests merged in 2020-08, with the labels that each got.

#479 MAISTRA-1071 Add manifest namespace validation
  pkg/controller/common/util.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/L

#496 Revert "MAISTRA-1071 Add manifest namespace validation (#479)"
  pkg/controller/common/util.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/util.go
Labels: size/L

#500 MAISTRA-1714: Update operator metadata for product
  build/generate-manifests.sh
  manifests-servicemesh/1.1.6/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.6/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.6/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.6/servicemeshoperator.v1.1.6.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: size/XL

#497 Update v1.1 charts
  resources/helm/v1.1/istio/charts/galley/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/pilot/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: okay to merge, ready to merge, size/M

#492 MAISTRA-1631 implement SMCP v1 to v2 conversion
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
  pkg/apis/maistra/conversion/addons.go
  pkg/apis/maistra/conversion/cluster.go
  pkg/apis/maistra/conversion/cluster_test.go
  pkg/apis/maistra/conversion/common.go
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/conversion/gateways_test.go
  pkg/apis/maistra/conversion/grafana.go
  pkg/apis/maistra/conversion/grafana_test.go
  pkg/apis/maistra/conversion/jaeger.go
  pkg/apis/maistra/conversion/jaeger_test.go
  pkg/apis/maistra/conversion/kiali.go
  pkg/apis/maistra/conversion/kiali_test.go
  pkg/apis/maistra/conversion/logging.go
  pkg/apis/maistra/conversion/logging_test.go
  pkg/apis/maistra/conversion/policy.go
  pkg/apis/maistra/conversion/policy_test.go
  pkg/apis/maistra/conversion/prometheus.go
  pkg/apis/maistra/conversion/prometheus_test.go
  pkg/apis/maistra/conversion/proxy.go
  pkg/apis/maistra/conversion/proxy_test.go
  pkg/apis/maistra/conversion/runtime.go
  pkg/apis/maistra/conversion/runtime_test.go
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/conversion/telemetry.go
  pkg/apis/maistra/conversion/telemetry_test.go
  pkg/apis/maistra/v1/helmvalues.go
  pkg/apis/maistra/v2/gateways.go
  pkg/apis/maistra/v2/grafana.go
  pkg/apis/maistra/v2/jaeger.go
  pkg/apis/maistra/v2/logging.go
  pkg/apis/maistra/v2/policy.go
  pkg/apis/maistra/v2/proxy.go
  pkg/apis/maistra/v2/runtime.go
  pkg/apis/maistra/v2/security.go
  pkg/apis/maistra/v2/telemetry.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
Labels: size/XXL

#503 MAISTRA-1720 Fix CRD generation for SMCPv2
  build/generate-manifests.sh
Labels: okay to merge, size/XS

#506 MAISTRA-1725 Group Maistra CRDs into category maistra-io
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/2.0.0/servicemeshmemberrolls.crd.yaml
  manifests-maistra/2.0.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
  pkg/apis/maistra/v1/servicemeshcontrolplane_types.go
  pkg/apis/maistra/v1/servicemeshmember_types.go
  pkg/apis/maistra/v1/servicemeshmemberroll_types.go
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
Labels: okay to merge, ready to merge, size/M

#508 MAISTRA-1747: Update base tag for 1.1.7
  resources/smcp-templates/v1.1/base
Labels: size/XS

#510 MAISTRA-1633 add ingress Gateway resource; move k8sIngress from Clust…
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
  pkg/apis/maistra/conversion/cluster.go
  pkg/apis/maistra/conversion/cluster_test.go
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/status/status.go
  pkg/apis/maistra/v1/servicemeshcontrolplane_types.go
  pkg/apis/maistra/v2/cluster.go
  pkg/apis/maistra/v2/gateways.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/versions/strategy_v2_0.go
  resources/helm/overlays/gateways/istio-ingress/templates/gateways.yaml
  resources/helm/v2.0/gateways/istio-ingress/templates/gateways.yaml
  resources/smcp-templates/v2.0/base
Labels: size/XL

#512 MAISTRA-1751 Replace 1337 UIDs and GIDs with ProxyUID
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/files/injection-template.yaml
Labels: size/S

#511 MAISTRA-1750 Make sure configuredMembers is never omitted in JSON marshalling
  pkg/apis/maistra/v1/servicemeshmemberroll_types.go
Labels: size/XS

#514 MAISTRA-1724 Remove namespace permissions from istiod ClusterRole
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/meshclusterrole.yaml
Labels: okay to merge, ready to merge, size/XS

#515 MAISTRA-1612 Remove injectPodRedirectAnnot option and always inject them
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
Labels: okay to merge, size/XS

#516 MAISTRA-1632 add conversion webhook to SMCP resource
  go.mod
  pkg/apis/addtoscheme_maistra_v1.go
  pkg/apis/addtoscheme_maistra_v2.go
  pkg/apis/maistra/conversion/cluster_test.go
  pkg/apis/maistra/conversion/controller.go
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/conversion/gateways_test.go
  pkg/apis/maistra/conversion/jaeger.go
  pkg/apis/maistra/status/status.go
  pkg/apis/maistra/v1/conversion.go
  pkg/apis/maistra/v1/servicemeshcontrolplane_types_test.go
  pkg/apis/maistra/v2/conversion.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/common/webhooks.go
  pkg/controller/controller.go
  pkg/controller/servicemesh/webhookca/controller.go
  pkg/controller/servicemesh/webhookca/controller_test.go
  pkg/controller/servicemesh/webhookca/conversion.go
  pkg/controller/servicemesh/webhookca/manager.go
  pkg/controller/servicemesh/webhookca/mutating.go
  pkg/controller/servicemesh/webhookca/validating.go
  pkg/controller/servicemesh/webhookca/wrappers.go
  pkg/controller/servicemesh/webhooks/hacks.go
  pkg/controller/servicemesh/webhooks/server.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/decoder.go
Labels: okay to merge, size/XXL

#517 MAISTRA-1633 add correct cni network to injected pod annotations
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, ready to merge, size/XS

#521 MAISTRA-1780 Use v4.6.0 of json-patch to speed up generation of patch
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/modules.txt
Labels: okay to merge, ready to merge, size/M

#524 MAISTRA-1784 Code cleanup: Use ToNamespacedName across the codebase
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/common/util.go
  pkg/controller/podlocality/controller.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/deleter.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/webhookca/controller.go
  pkg/controller/servicemesh/webhookca/controller_test.go
Labels: okay to merge, ready to merge, size/M
