Repository maistra/istio-operator, pull requests merged in 2020-11, with the labels that each got.

#616 MAISTRA-1975 ensure ClusterRole resources are unique
  build/patch-charts.sh
  resources/helm/overlays/wasm-extensions/templates/clusterrole.yaml
  resources/helm/overlays/wasm-extensions/templates/clusterrolebinding.yaml
  resources/helm/v2.0/istio-policy/templates/clusterrole.yaml
  resources/helm/v2.0/istio-policy/templates/clusterrolebinding.yaml
  resources/helm/v2.0/wasm-extensions/templates/clusterrole.yaml
  resources/helm/v2.0/wasm-extensions/templates/clusterrolebinding.yaml
Labels: okay to merge, ready to merge, size/S

#615 MAISTRA-1974 Set enableClientPolicyCheck if policy.type==Mixer
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/configmap.yaml
Labels: okay to merge, size/XS

#619 MAISTRA-1983 treat nil values as non-existent
  pkg/apis/maistra/v1/helmvalues.go
Labels: okay to merge, size/M

#623 MAISTRA-1982 Fix panic in conversion of logging level in v1 SMCP
  pkg/apis/maistra/conversion/logging.go
  pkg/apis/maistra/conversion/logging_test.go
Labels: okay to merge, ready to merge, size/L

#624 MAISTRA-1997 crd installation should work with invalid semver in mais…
  pkg/bootstrap/crds.go
  pkg/bootstrap/crds_test.go
Labels: size/S

#627 MAISTRA-2003 Skip reconciliation of SMCPs that failed to convert from v1 to v2
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge, ready to merge, size/M

#626 MAISTRA-1981 Mutating webhook should default v1 SMCPs to version v1.1
  pkg/controller/servicemesh/webhooks/mutation/controlplane.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane_test.go
Labels: okay to merge, size/S

#622 MAISTRA-1963 Mark gateways as unprivileged pods
  build/patch-charts.sh
  resources/helm/v2.0/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.0/gateways/istio-ingress/templates/deployment.yaml
Labels: okay to merge, size/S
