Repository maistra/istio-operator, pull requests merged in 2020-09, with the labels that each got.

#527 MAISTRA-1776 fix issue with null params in handler resources for v1.x…
  Makefile
  resources/helm/v1.0/istio/charts/mixer/templates/config.yaml
  resources/helm/v1.1/istio/charts/mixer/templates/config.yaml
Labels: okay to merge, size/XS

#525 MAISTRA-1776 do not mark SMCP as ready if reconcile fails
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, ready to merge, size/S

#528 Remove a duplicated generator
  build/codegen/update-generated.sh
  pkg/apis/maistra/conversion/zz_generated.conversion.go
  pkg/apis/maistra/status/zz_generated.deepcopy.go
Labels: okay to merge, size/XS

#532 Move sed a few lines higher
  build/generate-manifests.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/2.0.0/servicemeshmemberrolls.crd.yaml
  manifests-maistra/2.0.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: ok-to-test, okay to merge, ready to merge, size/M

#523 MAISTRA-1781 support v2 resources in mutating/validating webhooks
  deploy/examples/maistra_v2_servicemeshcontrolplane_cr_auth.yaml
  deploy/examples/maistra_v2_servicemeshcontrolplane_cr_full.yaml
  deploy/examples/maistra_v2_servicemeshcontrolplane_cr_minimal.yaml
  pkg/apis/addtoscheme_dependencies.go
  pkg/apis/addtoscheme_maistra_v1.go
  pkg/apis/addtoscheme_maistra_v2.go
  pkg/controller/common/test/api.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/common/test/enhanced-tracker.go
  pkg/controller/common/test/manager.go
  pkg/controller/common/test/runner.go
  pkg/controller/servicemesh/controlplane/deleter.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/webhooks/hacks.go
  pkg/controller/servicemesh/webhooks/mutation/common.go
  pkg/controller/servicemesh/webhooks/mutation/common_test.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/common_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/versions/strategy_v1_0.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/util.go
  pkg/controller/versions/versions.go
Labels: okay to merge, ready to merge, size/XXL

#489 MAISTRA-1400, MAISTRA-1685, MAISTRA-1348: Changes to IOR
  build/patch-charts.sh
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_auth.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_full.yaml
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/conversion/gateways_test.go
  pkg/apis/maistra/v2/gateways.go
  pkg/apis/maistra/v2/smcp_new.yaml
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/common/config.go
  pkg/controller/versions/strategy_v2_0.go
  resources/helm/overlays/gateways/ior/templates/ior-deployment.yaml
  resources/helm/overlays/gateways/ior/templates/ior-role.yaml
  resources/helm/overlays/gateways/ior/templates/ior-rolebinding.yaml
  resources/helm/overlays/gateways/ior/templates/ior-serviceaccount.yaml
  resources/helm/v2.0/gateways/ior/templates/ior-deployment.yaml
  resources/helm/v2.0/gateways/ior/templates/ior-role.yaml
  resources/helm/v2.0/gateways/ior/templates/ior-rolebinding.yaml
  resources/helm/v2.0/gateways/ior/templates/ior-serviceaccount.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/clusterrole.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
  resources/smcp-templates/v2.0/base
  resources/smcp-templates/v2.0/maistra
  resources/smcp-templates/v2.0/servicemesh
Labels: okay to merge, ready to merge, size/L

#529 Remove ca_file option in Kiali operator CR (1.0 branch)
  README.md
  helm/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.0/istio/charts/kiali/templates/kiali-cr.yaml
Labels: ok-to-test, ready to merge, size/S

#520 Remove ca_file option in Kiali operator CR
  README.md
  resources/helm/overlays/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.0/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.1/istio/charts/kiali/templates/kiali-cr.yaml
Labels: ok-to-test, okay to merge, size/S

#538 bump community to 1.1.8
  deploy/maistra-operator.yaml
  manifests-maistra/1.1.8/maistraoperator.v1.1.8.clusterserviceversion.yaml
  manifests-maistra/1.1.8/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/1.1.8/servicemeshmemberrolls.crd.yaml
  manifests-maistra/1.1.8/servicemeshmembers.crd.yaml
  manifests-maistra/maistra.package.yaml
Labels: okay to merge, size/XL

#539 bump 1.1 community to 1.1.8
  Makefile
  deploy/maistra-operator.yaml
  deploy/src/deployment-maistra.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: okay to merge, size/L

#541 Revert "Remove ca_file option in Kiali operator CR (#520)"
  README.md
  resources/helm/overlays/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.0/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.1/istio/charts/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/S

#542 Revert "Remove ca_file option in Kiali operator CR (1.0 branch) (#529)"
  README.md
  helm/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.0/istio/charts/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/S

#543 MAISTRA-1800 Use service-ca-operator to inject CA bundle
  build/generate-manifests.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  pkg/controller/common/webhooks.go
  pkg/controller/servicemesh/webhookca/controller.go
  pkg/controller/servicemesh/webhookca/controller_test.go
  pkg/controller/servicemesh/webhookca/conversion.go
  pkg/controller/servicemesh/webhookca/manager.go
  pkg/controller/servicemesh/webhooks/hacks.go
Labels: size/XL

#544 MAISTRA-1821 Add support for ServiceMeshExtensions
  build/codegen/update-generated.sh
  build/generate-manifests.sh
  build/patch-charts.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/2.0.0/servicemeshextensions.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshextensions.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshextensions.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
  pkg/apis/addtoscheme_maistra_v1alpha1.go
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
  pkg/apis/maistra/conversion/techpreviews_test.go
  pkg/apis/maistra/conversion/zz_generated.conversion.go
  pkg/apis/maistra/v1alpha1/register.go
  pkg/apis/maistra/v1alpha1/servicemeshextension_types.go
  pkg/apis/maistra/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/maistra/v2/runtime.go
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/common/config.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/testing.go
  pkg/controller/servicemesh/controlplane/wasm_extensions_test.go
  pkg/controller/versions/rendering_strategy_v1_x.go
  pkg/controller/versions/strategy_v2_0.go
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/overlays/wasm-extensions/Chart.yaml
  resources/helm/overlays/wasm-extensions/templates/_helpers.tpl
  resources/helm/overlays/wasm-extensions/templates/clusterrole.yaml
  resources/helm/overlays/wasm-extensions/templates/clusterrolebinding.yaml
  resources/helm/overlays/wasm-extensions/templates/deployment.yaml
  resources/helm/overlays/wasm-extensions/templates/service.yaml
  resources/helm/overlays/wasm-extensions/templates/serviceaccount.yaml
  resources/helm/overlays/wasm-extensions/values.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/v2.0/wasm-extensions/Chart.yaml
  resources/helm/v2.0/wasm-extensions/templates/_helpers.tpl
  resources/helm/v2.0/wasm-extensions/templates/clusterrole.yaml
  resources/helm/v2.0/wasm-extensions/templates/clusterrolebinding.yaml
  resources/helm/v2.0/wasm-extensions/templates/deployment.yaml
  resources/helm/v2.0/wasm-extensions/templates/service.yaml
  resources/helm/v2.0/wasm-extensions/templates/serviceaccount.yaml
  resources/helm/v2.0/wasm-extensions/values.yaml
  resources/smcp-templates/v2.0/base
  resources/smcp-templates/v2.0/maistra
  resources/smcp-templates/v2.0/servicemesh
  resources/smcp-templates/v2.0/small
Labels: size/XXL

#549 MAISTRA-1832 Rely on vendor directory for deps
  build/split-istio-crds.sh
  go.mod
Labels: okay to merge, ready to merge, size/XS

#550 MAISTRA-1833 Don't check CNI readiness during SMCP installation
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/S

#548 MAISTRA-1830 Set the correct --cacheCluster for fetching WASM extensions
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
Labels: size/XS

#555 MAISTRA-1804 fix kiali integration for 2.0
  pkg/controller/common/test/client.go
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.0/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/S

#557 MAISTRA-1847: Fix missing bitbucket dependency
  go.mod
  go.sum
  internal/bitbucket.org/ww/goautoneg/README.txt
  internal/bitbucket.org/ww/goautoneg/autoneg.go
  internal/bitbucket.org/ww/goautoneg/go.mod
Labels: okay to merge, size/L

#554 MAISTRA-1838 Ignore empty objects in rendered YAML
  pkg/controller/common/helm/manifestprocessing.go
Labels: okay to merge, ready to merge, size/XS

#551 MAISTRA-1787 add support for setting tls settings in istiod
  resources/helm/v2.0/global.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/S

#553 MAISTRA-1837 Fix minimal, full and auth v2 SMCP example YAMLs
  deploy/examples/maistra_v2_servicemeshcontrolplane_cr_auth.yaml
  deploy/examples/maistra_v2_servicemeshcontrolplane_cr_full.yaml
  deploy/examples/maistra_v2_servicemeshcontrolplane_cr_minimal.yaml
Labels: okay to merge, size/L

#559 MAISTRA-1849 Add validation of SMMR.spec.members
  pkg/controller/servicemesh/webhooks/validation/memberroll.go
  pkg/controller/servicemesh/webhooks/validation/memberroll_test.go
Labels: size/M

#558 MAISTRA-1831 use objectSelector in injector webhook
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/smcp-templates/v2.0/base
Labels: okay to merge, size/M

#562 MAISTRA-1844: Update operator to support maistra 1.1.9
  deploy/servicemesh-operator.yaml
  manifests-servicemesh/1.1.9/servicemeshoperator.v1.1.9.clusterserviceversion.yaml
Labels: size/M

#560 MAISTRA-1851 STATUS column should only show readiness status if the SMCP has been reconciled successfully
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-maistra/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
  pkg/apis/maistra/status/status.go
  pkg/apis/maistra/v1/servicemeshcontrolplane_types.go
  pkg/controller/servicemesh/controlplane/readiness.go
Labels: okay to merge, ready to merge, size/M

#564 MAISTRA-1861 update kiali resource correctly for smmr changes
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, ready to merge, size/XS

#561 MAISTRA-1767 add operators.openshift.io/infrastructure-features annot…
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.0.0/maistraoperator.v2.0.0.clusterserviceversion.yaml
  manifests-servicemesh/2.0.0/servicemeshoperator.v2.0.0.clusterserviceversion.yaml
Labels: size/S

#567 MAISTRA-1723: Disable NodePort gateway support
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, ready to merge, size/XS
