Repository maistra/istio-operator, pull requests merged in 2020-12, with the labels that each got.

#634 MAISTRA-1898: Sync with maistra/istio
  resources/helm/v2.0/gateways/istio-ingress/templates/preconfigured.yaml
  resources/helm/v2.0/global.yaml
  resources/helm/v2.0/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.0/istio-control/istio-discovery/files/injection-template.yaml
  resources/helm/v2.0/istio-telemetry/mixer-telemetry/templates/deployment.yaml
  resources/helm/v2.0/mesh-config/templates/telemetryv2_1.6.yaml
Labels: okay to merge, size/M

#630 MAISTRA-1946: Whitelist OVNKubernetes provider
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
Labels: okay to merge, size/XS

#636 MAISTRA-612: Automatic redirect of http to https in routes
  resources/helm/overlays/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/ingress.yaml
  resources/helm/v2.0/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/v2.0/istio-telemetry/prometheus/templates/ingress.yaml
Labels: okay to merge, ready to merge, size/XS

#637 MAISTRA-2026 Add default DestinationRule for wasm-cacher
  resources/helm/overlays/wasm-extensions/templates/destinationrule.yaml
  resources/helm/v2.0/wasm-extensions/templates/destinationrule.yaml
Labels: okay to merge, ready to merge, size/M

#572 add basic crd docs
  Makefile
  docs/README.adoc
  docs/crd/CRDS.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_AddonsConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_ControlPlaneClusterConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_ControlPlaneRuntimeConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_GatewaysConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_GeneralConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_HelmValues_v1.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_NetworkType_v1.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_PolicyConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_ProxyConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_ReadinessStatus_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_SecurityConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_TelemetryConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_TracingConfig_v2.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_v1.adoc
  docs/crd/maistra.io_ServiceMeshControlPlane_v2.adoc
  docs/crd/maistra.io_ServiceMeshExtension_DeploymentStatus_v1alpha1.adoc
  docs/crd/maistra.io_ServiceMeshExtension_FilterPhase_v1alpha1.adoc
  docs/crd/maistra.io_ServiceMeshExtension_WorkloadSelector_v1alpha1.adoc
  docs/crd/maistra.io_ServiceMeshExtension_v1alpha1.adoc
  docs/crd/maistra.io_ServiceMeshMemberRoll_v1.adoc
  docs/crd/maistra.io_ServiceMeshMember_ServiceMeshControlPlaneRef_v1.adoc
  docs/crd/maistra.io_ServiceMeshMember_v1.adoc
  tools/doc/main.go
  tools/pkg/doc/adoc.go
  tools/pkg/doc/gen.go
  tools/pkg/doc/markdown.go
  tools/pkg/doc/util.go
Labels: okay to merge, size/XXL

#618 MAISTRA-1976 Pruner now deletes config.istio.io/v1alpha2 instance objects
  pkg/controller/servicemesh/controlplane/pruner.go
Labels: okay to merge, size/XS

#617 MAISTRA-1979 Don't drop fields in SMCP status when converting from v2 to v1
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
Labels: okay to merge, ready to merge, size/XS

#631 MAISTRA-2005 fix gateway service annotations config mapping
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/conversion/gateways_test.go
Labels: okay to merge, size/S

#613 MAISTRA-1968 enable status when analysis is enabled
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/templates/configmap.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, ready to merge, size/S

#629 MAISTRA-2014 fix external jaeger integration for 1.1 control planes
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
  pkg/apis/maistra/conversion/kiali.go
  pkg/apis/maistra/conversion/tracing.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/versions/rendering_strategy_v1_x.go
Labels: okay to merge, size/L

#633 MAISTRA-2007 Use self-signed cert for webhook caBundle if present
  pkg/controller/common/webhooks.go
  pkg/controller/servicemesh/webhookca/controller.go
  pkg/controller/servicemesh/webhookca/controller_test.go
  pkg/controller/servicemesh/webhookca/manager.go
  pkg/controller/servicemesh/webhookca/source.go
  pkg/controller/servicemesh/webhooks/hacks.go
Labels: okay to merge, size/XL

#641 MAISTRA-1940: Wait for components when updating control planes
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/S

#644 MAISTRA-2037: Update manifests for 2.0.1
  Makefile
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.0.1/maistraoperator.v2.0.1.clusterserviceversion.yaml
  manifests-servicemesh/2.0.1/servicemeshoperator.v2.0.1.clusterserviceversion.yaml
Labels: okay to merge, size/L

#645 MAISTRA-2041: Update operator metadata to 1.1.11
  Makefile
  build/download-charts.sh
  build/generate-manifests.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  manifests-maistra/1.1.11/maistraoperator.v1.1.11.clusterserviceversion.yaml
  manifests-servicemesh/1.1.11/servicemeshoperator.v1.1.11.clusterserviceversion.yaml
Labels: okay to merge, size/L

#646 MAISTRA-2040 fix issue with caBundle controller source predicates
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/common/test/runner.go
  pkg/controller/servicemesh/webhookca/controller.go
  pkg/controller/servicemesh/webhookca/maistra2040_test.go
Labels: okay to merge, size/L

#650 MAISTRA-2043: Updated for 1.1.11 release
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-servicemesh/2.0.1/servicemeshoperator.v2.0.1.clusterserviceversion.yaml
Labels: okay to merge, size/M

#652 MAISTRA-2046: Fix the patching for the cni networking
  build/patch-charts.sh
  resources/helm/v2.0/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge

#653 MAISTRA-2053 use unique object for every CABundleSource
  pkg/controller/common/test/enhanced-tracker.go
  pkg/controller/servicemesh/webhookca/controller.go
  pkg/controller/servicemesh/webhookca/maistra2040_test.go
  pkg/controller/servicemesh/webhookca/manager.go
  pkg/controller/servicemesh/webhookca/source.go
Labels: okay to merge, size/XL

#654 Look for the right yq; Check if it's the correct one
  build/generate-manifests.sh
Labels: okay to merge, size/S
