Repository maistra/istio-operator, pull requests merged in 2020-02, with the labels that each got.

#323 Remove 1.0.1 and 1.0.3 releases from community
  manifests-maistra/1.0.1/maistraoperator.v1.0.1.clusterserviceversion.yaml
  manifests-maistra/1.0.1/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/1.0.1/servicemeshmemberrolls.crd.yaml
  manifests-maistra/1.0.2/maistraoperator.v1.0.2.clusterserviceversion.yaml
  manifests-maistra/1.0.3/maistraoperator.v1.0.3.clusterserviceversion.yaml
  manifests-maistra/1.0.3/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/1.0.3/servicemeshmemberrolls.crd.yaml
  manifests-maistra/1.0.4/maistraoperator.v1.0.4.clusterserviceversion.yaml
Labels: size/XL

#316 MAISTRA-1129 reconcileNamespaces should return all configuredNamespaces
  pkg/controller/common/test/assert/asserts.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler_test.go
Labels: okay to merge, size/M

#326 MAISTRA-1147: Update service mesh manifests to support 1.0.7
  deploy/servicemesh-operator.yaml
  deploy/smcp-templates/base
  manifests-servicemesh/1.0.7/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.0.7/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.0.7/servicemeshoperator.v1.0.7.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
  tmp/build/generate-manifests.sh
Labels: okay to merge, size/L

#328 MAISTRA-1153: adds ability to read pods and services for ior
  resources/helm/overlays/istio/charts/gateways/templates/ior-role.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/ior-role.yaml
Labels: okay to merge, size/XS

#329 MAISTRA-1155 Fix bad indentation in grafana's patched values.yaml
  build/patch-grafana.sh
  resources/helm/v1.1/istio/charts/grafana/values.yaml
Labels: okay to merge, size/S

#330 MAISTRA-1156 Add Make targets to check whether generated files have been checked in
  Makefile
Labels: okay to merge, size/S

#324 MAISTRA-1143 Propagate context properly throughout the call stack
  cmd/manager/main.go
  pkg/bootstrap/cni.go
  pkg/bootstrap/common.go
  pkg/bootstrap/crds.go
  pkg/controller/common/context.go
  pkg/controller/common/finalizers.go
  pkg/controller/common/manifestprocessing.go
  pkg/controller/common/metadata.go
  pkg/controller/common/patch.go
  pkg/controller/common/scc.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/common/util.go
  pkg/controller/common/webhooks.go
  pkg/controller/hacks/hacks.go
  pkg/controller/podlocality/controller.go
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/controller_test.go
  pkg/controller/servicemesh/controlplane/deleter.go
  pkg/controller/servicemesh/controlplane/hooks.go
  pkg/controller/servicemesh/controlplane/htpasswd.go
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
  pkg/controller/servicemesh/controlplane/pruner.go
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/memberroll/common_test.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler_test.go
  pkg/controller/servicemesh/memberroll/ovs_multitenant.go
  pkg/controller/servicemesh/memberroll/ovs_multitenant_test.go
  pkg/controller/servicemesh/memberroll/ovs_networkpolicy.go
  pkg/controller/servicemesh/memberroll/ovs_networkpolicy_test.go
  pkg/controller/servicemesh/memberroll/ovs_subnet.go
  pkg/controller/servicemesh/memberroll/ovs_subnet_test.go
  pkg/controller/servicemesh/mutatingwebhook/controller.go
  pkg/controller/servicemesh/mutatingwebhook/controller_test.go
  pkg/controller/servicemesh/validatingwebhook/controller.go
  pkg/controller/servicemesh/validatingwebhook/controller_test.go
  pkg/controller/servicemesh/validation/common_test.go
  pkg/controller/servicemesh/validation/controlplane.go
  pkg/controller/servicemesh/validation/controlplane_test.go
  pkg/controller/servicemesh/validation/member.go
  pkg/controller/servicemesh/validation/member_test.go
  pkg/controller/servicemesh/validation/memberroll.go
  pkg/controller/servicemesh/validation/memberroll_test.go
  pkg/controller/servicemesh/validation/webhook_server.go
Labels: okay to merge, size/XXL

#332 MAISTRA-1161 Change networkName for maistra-1.1
  pkg/controller/common/cni.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/XS

#333 MAISTRA-1162 Remove --manageWebhookConfig parameter, add --useOldPipe…
  build/patch-charts.sh
  resources/helm/v1.1/istio/charts/galley/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: okay to merge, size/XS

#334 MAISTRA-1163 Fix sed patterns targeting sidecar-injector templates
  build/patch-charts.sh
  resources/helm/v1.1/istio/files/injection-template.yaml
Labels: okay to merge, size/S

#335 MAISTRA-1164 Move CNI annotation to injectedAnnotations
  build/patch-charts.sh
  resources/helm/v1.1/istio/templates/sidecar-injector-configmap.yaml
Labels: okay to merge, size/S

#325 MAISTRA-1108 Operator fails to create 1.1 CRDs on OpenShift 3.11
  pkg/bootstrap/crds.go
  pkg/controller/hacks/hacks.go
Labels: okay to merge, size/M

#337 MAISTRA-1171 Introduce CNIConfig struct to replace global variables
  pkg/bootstrap/cni.go
  pkg/controller/common/cni.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/controller_test.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/controlplane/testing.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/L

#339 MAISTRA-1172 Timeout when creating ServiceMeshMemberRole with many namespaces
  pkg/controller/servicemesh/validation/member_test.go
  pkg/controller/servicemesh/validation/memberroll.go
  pkg/controller/servicemesh/validation/memberroll_test.go
  pkg/controller/servicemesh/validation/webhook_server_test.go
Labels: don't squash, okay to merge, size/L

#341 MAISTRA-1180: Update network policy to fix intermittent ingress gatew…
  helm/istio/charts/gateways/templates/networkpolicy.yaml
Labels: okay to merge, size/XS

#343 MAISTRA-1190: Update operator to support Maistra 1.0.8
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/smcp-templates/base
  manifests-maistra/1.0.8/maistraoperator.v1.0.8.clusterserviceversion.yaml
  manifests-maistra/1.0.8/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/1.0.8/servicemeshmemberrolls.crd.yaml
  manifests-maistra/maistra.package.yaml
  manifests-servicemesh/1.0.8/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.0.8/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.0.8/servicemeshoperator.v1.0.8.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
  tmp/build/generate-manifests.sh
Labels: okay to merge, size/XL

#336 MAISTRA-1113 Support deploying CRDs from multiple Maistra versions
  go.mod
  pkg/bootstrap/crds.go
  pkg/bootstrap/crds_test.go
  pkg/controller/common/patch.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/hacks/hacks.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/XL

#338 MAISTRA-1097 Only support AllNamespaces installation in OLM
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/S

#349 MAISTRA-1079: Replace deprecated API's
  pkg/controller/servicemesh/controlplane/pruner.go
  tmp/build/patch-charts.sh
Labels: okay to merge, size/M

#350 MAISTRA-1212 Fix galley CLI argument
  build/patch-charts.sh
  resources/helm/v1.1/istio/charts/galley/templates/deployment.yaml
Labels: okay to merge, size/XS

#354 MAISTRA-1210 Fix inconsistencies in CNI file names (v1.1 -> v1-1)
  resources/helm/overlays/istio_cni/templates/configmap.yaml
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v1.1/istio_cni/templates/configmap.yaml
  resources/helm/v1.1/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/S

#352 [Maistra-1215][Maistra-1211] Added collect-olm-manifests
  .gitignore
  Makefile
Labels: okay to merge, size/S

#351 MAISTRA-1213 Deploy prometheus using global hub and tag (fixed sed pa…
  build/patch-prometheus.sh
  resources/helm/v1.1/istio/charts/prometheus/templates/deployment.yaml
Labels: okay to merge, size/XS

#347 MAISTRA-1202 Speed up deployment of CRDs
  pkg/apis/addtoscheme_maistra_v1.go
  pkg/bootstrap/crds.go
  pkg/bootstrap/crds_test.go
  pkg/controller/hacks/hacks.go
Labels: okay to merge, size/L
