Repository maistra/istio-operator, pull requests merged in 2020-07, with the labels that each got.

#476 MAISTRA-1617 Generate CSVs for 1.1.4+2
  build/generate-manifests.sh
  deploy/servicemesh-operator.yaml
  manifests-servicemesh/1.1.4.2/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.4.2/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.4.2/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.4.2/servicemeshoperator.v1.1.4+2.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: okay to merge, ready to merge, size/XL

#462 MAISTRA-1071 Add manifest namespace validation
  pkg/controller/common/util.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_util.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_v1_1.go
Labels: okay to merge, size/L

#482 MAISTRA-1672: Update operator metadata for maistra 1.1.5
  build/generate-manifests.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  manifests-maistra/1.1.5/maistraoperator.v1.1.5.clusterserviceversion.yaml
  manifests-maistra/1.1.5/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/1.1.5/servicemeshmemberrolls.crd.yaml
  manifests-maistra/1.1.5/servicemeshmembers.crd.yaml
  manifests-maistra/maistra.package.yaml
  manifests-servicemesh/1.1.5/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.5/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.5/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.5/servicemeshoperator.v1.1.5.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: size/XXL

#483 MAISTRA-1625: update templates
  resources/smcp-templates/v1.0/base
Labels: size/XS

#484 MAISTRA-1557: Add service mesh icon and automate generation
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  build/manifest-templates/servicemesh_rgb_icon_default_128px.png
  manifests-maistra/1.1.5/maistraoperator.v1.1.5.clusterserviceversion.yaml
  manifests-servicemesh/1.1.5/servicemeshoperator.v1.1.5.clusterserviceversion.yaml
Labels: size/L

#485 Update README.md
  README.md
Labels: needs-ok-to-test, okay to merge, size/XS

#486 MAISTRA-1681: Do not define env unless one of the TLS variables is be…
  resources/helm/v1.1/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: size/XS

#487 fix test failure from bad commit
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge, size/XS

#488 MAISTRA-1633 update overlays to work with istio 1.6 values.yaml structure
  build/patch-charts.sh
  pkg/apis/maistra/conversion/addons.go
  pkg/apis/maistra/conversion/cluster.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/versions/strategy_v2_0.go
  resources/helm/overlays/gateways/istio-ingress/templates/istio-ingressgateway-route.yaml
  resources/helm/overlays/gateways/istio-ingress/templates/networkpolicy.yaml
  resources/helm/overlays/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/overlays/istio-telemetry/grafana/templates/networkpolicy.yaml
  resources/helm/overlays/istio-telemetry/grafana/templates/secrets.yaml
  resources/helm/overlays/istio-telemetry/grafana/templates/serviceaccount.yaml
  resources/helm/overlays/istio-telemetry/kiali/templates/networkpolicy.yaml
  resources/helm/overlays/istio-telemetry/telemetry-common/templates/htpasswd-secret.yaml
  resources/helm/overlays/istio-telemetry/telemetry-common/templates/trusted-ca-bundle-cm.yaml
  resources/helm/overlays/istio-telemetry/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/overlays/istio-telemetry/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/overlays/istio-telemetry/tracing/templates/networkpolicy.yaml
  resources/helm/overlays/istio-telemetry/tracing/templates/policy-jaeger.yaml
  resources/helm/overlays/istio-telemetry/tracing/templates/service.yaml
  resources/helm/overlays/istio-telemetry/tracing/templates/serviceaccount-jaeger.yaml
  resources/helm/overlays/mesh-config/templates/enable-mesh-mtls.yaml
  resources/helm/overlays/mesh-config/templates/enable-mesh-permissive.yaml
  resources/helm/overlays/mesh-config/templates/grafana-ports-mtls.yaml
  resources/helm/overlays/mesh-config/templates/networkpolicy.yaml
  resources/helm/overlays/mesh-config/templates/policy-jaeger.yaml
  resources/helm/overlays/mesh-config/values.yaml
  resources/helm/v2.0/gateways/istio-ingress/templates/istio-ingressgateway-route.yaml
  resources/helm/v2.0/gateways/istio-ingress/templates/networkpolicy.yaml
  resources/helm/v2.0/global.yaml
  resources/helm/v2.0/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/v2.0/istio-telemetry/grafana/templates/networkpolicy.yaml
  resources/helm/v2.0/istio-telemetry/grafana/templates/secrets.yaml
  resources/helm/v2.0/istio-telemetry/grafana/templates/serviceaccount.yaml
  resources/helm/v2.0/istio-telemetry/kiali/templates/networkpolicy.yaml
  resources/helm/v2.0/istio-telemetry/telemetry-common/templates/htpasswd-secret.yaml
  resources/helm/v2.0/istio-telemetry/telemetry-common/templates/trusted-ca-bundle-cm.yaml
  resources/helm/v2.0/istio-telemetry/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/v2.0/istio-telemetry/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/v2.0/istio-telemetry/tracing/templates/networkpolicy.yaml
  resources/helm/v2.0/istio-telemetry/tracing/templates/policy-jaeger.yaml
  resources/helm/v2.0/istio-telemetry/tracing/templates/service.yaml
  resources/helm/v2.0/istio-telemetry/tracing/templates/serviceaccount-jaeger.yaml
  resources/helm/v2.0/mesh-config/templates/enable-mesh-mtls.yaml
  resources/helm/v2.0/mesh-config/templates/enable-mesh-permissive.yaml
  resources/helm/v2.0/mesh-config/templates/grafana-ports-mtls.yaml
  resources/helm/v2.0/mesh-config/templates/networkpolicy.yaml
  resources/helm/v2.0/mesh-config/templates/policy-jaeger.yaml
  resources/helm/v2.0/mesh-config/values.yaml
Labels: okay to merge, ready to merge, size/XL

#493 MAISTRA-1699: Update templates and validation for cipher suites and E…
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_v1_1.go
  resources/helm/v1.1/istio/charts/galley/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/pilot/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: size/L

#494 MAISTRA-1703: Update information for 1.1.5+2 release
  build/generate-manifests.sh
  manifests-servicemesh/1.1.5.2/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.5.2/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.5.2/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.5.2/servicemeshoperator.v1.1.5+2.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: size/XL
