Repository maistra/istio-operator, pull requests merged in 2020-05, with the labels that each got.

#394 MAISTRA-1316 Prevent SMCP/SMMR/SMM resources from being created in the operator namespace
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/member.go
  pkg/controller/servicemesh/webhooks/validation/member_test.go
  pkg/controller/servicemesh/webhooks/validation/memberroll.go
  pkg/controller/servicemesh/webhooks/validation/memberroll_test.go
Labels: don't squash, okay to merge, size/M

#395 MAISTRA-1318 SMCP validating webhook needlessly lists SMCPs in all namespaces
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
Labels: okay to merge, size/S

#421 added license
  LICENSE
Labels: okay to merge, size/L

#419 MAISTRA-1371 refactor version customization
  pkg/apis/maistra/versions.go
  pkg/bootstrap/cni.go
  pkg/controller/common/cni/cni.go
  pkg/controller/common/cni/cni_test.go
  pkg/controller/common/config.go
  pkg/controller/common/helm/helm.go
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/patch.go
  pkg/controller/common/util.go
  pkg/controller/podlocality/controller.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/controller_test.go
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/controlplane/testing.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler_test.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_downgrade_v1_1.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_upgrade_v1_0.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_v1_0.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_v1_1.go
  pkg/controller/versions/strategy_v1_0.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/strategy_v1_2.go
  pkg/controller/versions/util.go
  pkg/controller/versions/versions.go
  pkg/controller/versions/versions_test.go
Labels: okay to merge, size/XXL

#428 MAISTRA-1433 Fix panic in manifest processing
  pkg/controller/common/helm/manifestprocessing.go
Labels: okay to merge, size/XS

#420 MAISTRA-1419 use new smcp when validating upgrade/downgrade
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
Labels: okay to merge, size/S

#432 MAISTRA-1443: Update operator support for Maistra 1.1.2
  deploy/servicemesh-operator.yaml
  manifests-servicemesh/1.1.2/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.2/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.2/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.2/servicemeshoperator.v1.1.2.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
  resources/smcp-templates/v1.1/base
Labels: size/XL

#430 MAISTRA-1436 fix SIGSEGV when specified smcp.spec.template does not e…
  pkg/controller/common/test/api.go
  pkg/controller/common/test/client.go
  pkg/controller/common/test/manager.go
  pkg/controller/common/test/runner.go
  pkg/controller/common/test/verifiers.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/L

#425 MAISTRA-1427 Fix misleading message in condition of individual control plane components
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/status.go
Labels: okay to merge, size/S

#399 MAISTRA-1317 Allow creation of SMMR even if SMCP does not yet exist
  pkg/controller/servicemesh/webhooks/validation/memberroll.go
  pkg/controller/servicemesh/webhooks/validation/memberroll_test.go
Labels: okay to merge, size/S

#437 MAISTRA-1486: include second 1.1.2 release
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  manifests-servicemesh/1.1.2+2/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.2+2/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.2+2/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.2+2/servicemeshoperator.v1.1.2+2.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: okay to merge, size/XL

#438 MAISTRA-1491: generate a sanitised version for the directory and CSV …
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  build/manifest-templates/package.yaml
  manifests-servicemesh/1.1.2.2/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.2.2/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.2.2/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.2.2/servicemeshoperator.v1.1.2+2.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
Labels: size/S

#435 MAISTRA-1465 Use delete-collection to reduce number of requests when pruning
  pkg/controller/servicemesh/controlplane/hooks.go
  pkg/controller/servicemesh/controlplane/pruner.go
Labels: okay to merge, size/L

#436 MAISTRA-1473 Use PATCH operation when updating object's status
  pkg/controller/common/status-patch.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/L

#439 MAISTRA-1494: Add support for the metadata version
  build/generate-manifests.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  manifests-servicemesh/1.1.2.2/servicemeshoperator.v1.1.2+2.clusterserviceversion.yaml
  pkg/apis/maistra/v1/status.go
Labels: size/S

#444 MAISTRA-1494: Use the sanitised version for reconciliation
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  manifests-servicemesh/1.1.2.2/servicemeshoperator.v1.1.2+2.clusterserviceversion.yaml
Labels: size/XS

#443 MAISTRA-1449 Pull in updated charts
  resources/helm/v1.1/istio/charts/gateways/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/role.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/rolebindings.yaml
Labels: okay to merge, size/S

#441 MAISTRA-1373 Enable specification of oauth-proxy container resources
  build/patch-grafana.sh
  build/patch-prometheus.sh
  resources/helm/v1.1/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/prometheus/templates/deployment.yaml
Labels: okay to merge, size/S

#446 [maistra-1.2] MAISTRA-1373 Enable specification of oauth-proxy container resources
  build/patch-grafana.sh
  build/patch-prometheus.sh
  resources/helm/v1.1/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/prometheus/templates/deployment.yaml
  resources/helm/v1.2/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.2/istio/charts/prometheus/templates/deployment.yaml
Labels: okay to merge, size/M

#440 MAISTRA-1495 Keep SMCP.status.components in installation order
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/M

#434 MAISTRA-1451 Enable injectPodRedirectAnnot flag when enabled in SMCP
  build/patch-charts.sh
  resources/helm/v1.1/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: okay to merge, size/XS

#406 MAISTRA-1354 Make it possible to turn on/off verbose output in operator tests
  Makefile
Labels: okay to merge, size/XS

#407 MAISTRA-1353 Operator shouldn't add owner reference to SMMR
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/M

#447 MAISTRA-1500 Fix race condition in post-install readiness check
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
  pkg/controller/servicemesh/controlplane/manifestprocessing_test.go
  pkg/controller/servicemesh/controlplane/readiness.go
Labels: okay to merge, size/L

#398 MAISTRA-1315 Implement proper global handling of update conflicts
  pkg/bootstrap/crds.go
  pkg/controller/common/conflicts.go
  pkg/controller/common/conflicts_test.go
  pkg/controller/common/finalizers.go
  pkg/controller/common/test/assert/asserts.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, size/L

#427 MAISTRA-1431 ControlPlaneStatus.ComponentStatus array shouldn't be an array of pointers
  pkg/apis/maistra/v1/servicemeshcontrolplane_types.go
  pkg/apis/maistra/v1/status.go
  pkg/apis/maistra/v1/zz_generated.deepcopy.go
  pkg/controller/servicemesh/controlplane/manifestprocessing_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/S

#429 MAISTRA-1435 Add v1.2 entry to istio-cni-config ConfigMap
  pkg/controller/common/cni/cni.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  resources/helm/overlays/istio_cni/templates/configmap.yaml
  resources/helm/v1.2/istio_cni/templates/configmap.yaml
Labels: okay to merge, size/M

#450 Update links to the docs; Remove the version field from minimal
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_auth.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_full.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_minimal.yaml
Labels: okay to merge, size/XS

#451 Update links to the docs; Remove the version field from minimal
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_auth.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_full.yaml
  deploy/examples/maistra_v1_servicemeshcontrolplane_cr_minimal.yaml
Labels: okay to merge, size/XS

#449 Configure mergify to add "ready to merge" label to PRs
  .mergify.yml
Labels: okay to merge, size/S
