Repository maistra/istio-operator, pull requests merged in 2020-03, with the labels that each got.

#355 MAISTRA-1222: Update service mesh manifests to support 1.0.9
  deploy/servicemesh-operator.yaml
  deploy/smcp-templates/base
  manifests-servicemesh/1.0.9/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.0.9/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.0.9/servicemeshoperator.v1.0.9.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
  tmp/build/generate-manifests.sh
Labels: size/L

#357 MAISTRA-1204 Use local cache to check status of SMCP
  pkg/controller/servicemesh/controlplane/readiness.go
Labels: okay to merge, size/L

#360 MAISTRA-1237 Add SMCP UX changes that have disappeared
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-maistra/1.1.0/servicemeshcontrolplanes.crd.yaml
  manifests-maistra/1.1.0/servicemeshmemberrolls.crd.yaml
  manifests-maistra/1.1.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.0/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.1.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/L

#358 MAISTRA-1230 Create mesh-user role and binding for SMCP
  deploy/examples/use-mesh-rbac-example.yaml
  pkg/controller/servicemesh/controlplane/rbac.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/L

#364 MAISTRA-1251 Allow overriding Maistra Istio repo in download-charts.sh using env var
  build/download-charts.sh
Labels: okay to merge, size/S

#366 MAISTRA-1214 Fail patch scripts if a sed command does not match
  build/download-charts.sh
  build/patch-charts.sh
  build/patch-grafana.sh
  build/patch-jaeger.sh
  build/patch-prometheus.sh
Labels: okay to merge, size/L

#367 MAISTRA-1217 Pull in chart changes due to 1.4.6 update
  build/patch-charts.sh
  resources/helm/v1.1/istio/charts/galley/templates/clusterrole.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/grafana/dashboards/galley-dashboard.json
  resources/helm/v1.1/istio/charts/pilot/templates/clusterrole.yaml
  resources/helm/v1.1/istio/files/injection-template.yaml
  resources/helm/v1.1/istio/values.yaml
  resources/smcp-templates/v1.1/base
Labels: okay to merge, size/L

#368 MAISTRA-1043: Replace deprecated API's
  pkg/controller/servicemesh/controlplane/pruner.go
Labels: okay to merge, size/XS

#369 MAISTRA-1256 add version field to kiali cr
  resources/helm/overlays/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.1/istio/charts/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/S

#372 MAISTRA-1241 Remove namespace/finalizers update permissions from galley
  build/patch-charts.sh
  resources/helm/v1.1/istio/charts/galley/templates/clusterrole.yaml
Labels: okay to merge, size/S

#370 MAISTRA-1263 add replaces and olm.skipRange to csv files
  Makefile
  build/manifest-templates/clusterserviceversion.yaml
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-servicemesh/1.1.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/M

#373 MAISTRA-1259 fix zipkin service port in v1.1 charts
  resources/helm/overlays/istio/charts/tracing/templates/service.yaml
  resources/helm/v1.1/istio/charts/tracing/templates/service.yaml
Labels: okay to merge, size/XS

#374 MAISTRA-1182: Update network policy to fix intermittent ingress gatew…
  resources/helm/overlays/istio/charts/gateways/templates/networkpolicy.yaml
  resources/helm/v1.1/istio/charts/gateways/templates/networkpolicy.yaml
Labels: okay to merge, size/XS

#376 MAISTRA-1160 Add support for external Jaeger instances
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  resources/helm/overlays/istio/charts/kiali/templates/kiali-cr.yaml
  resources/helm/v1.1/istio/charts/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/L

#377 MAISTRA-1273: Update operator to support Maistra 1.0.10
  manifests-servicemesh/1.0.10/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/1.0.10/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/1.0.10/servicemeshoperator.v1.0.10.clusterserviceversion.yaml
  manifests-servicemesh/servicemesh.package.yaml
  tmp/build/generate-manifests.sh
Labels: okay to merge, size/L

#361 MAISTRA-1076 add upgrade/downgrade validation
  Makefile
  build/codegen/update-generated.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
  pkg/apis/addtoscheme_istio.go
  pkg/apis/istio/simple/config/v1alpha2/deprecated_types.go
  pkg/apis/istio/simple/config/v1alpha2/doc.go
  pkg/apis/istio/simple/config/v1alpha2/register.go
  pkg/apis/istio/simple/config/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/istio/simple/networking/v1alpha3/doc.go
  pkg/apis/istio/simple/networking/v1alpha3/register.go
  pkg/apis/istio/simple/networking/v1alpha3/types.go
  pkg/apis/istio/simple/networking/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/istio/simple/security/v1beta1/doc.go
  pkg/apis/istio/simple/security/v1beta1/register.go
  pkg/apis/istio/simple/security/v1beta1/types.go
  pkg/apis/istio/simple/security/v1beta1/zz_generated.deepcopy.go
  pkg/apis/istio/simple/types.go
  pkg/apis/istio/simple/types_test.go
  pkg/apis/maistra/versions.go
  pkg/apis/maistra/versions_test.go
  pkg/bootstrap/cni.go
  pkg/controller/common/cni.go
  pkg/controller/common/cni_test.go
  pkg/controller/common/helm.go
  pkg/controller/common/test/assert/asserts.go
  pkg/controller/common/test/client.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/common/test/enhanced-tracker.go
  pkg/controller/common/test/runner.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_downgrade_v1_1.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_upgrade_v1_0.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_util.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_v1_0.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_v1_1.go
Labels: okay to merge, size/XXL

#379 MAISTRA-1273: Update operator to support Maistra 1.0.10
  deploy/servicemesh-operator.yaml
  deploy/smcp-templates/base
  manifests-servicemesh/1.0.10/servicemeshoperator.v1.0.10.clusterserviceversion.yaml
Labels: size/S

#380 MAISTRA-1208: Use a file for oauth secret cookies
  build/patch-grafana.sh
  build/patch-prometheus.sh
  pkg/controller/servicemesh/controlplane/hooks.go
  pkg/controller/servicemesh/controlplane/htpasswd.go
  resources/helm/overlays/istio/charts/grafana/templates/secrets.yaml
  resources/helm/overlays/istio/charts/prometheus/templates/secrets.yaml
  resources/helm/v1.1/istio/charts/grafana/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/grafana/templates/secrets.yaml
  resources/helm/v1.1/istio/charts/prometheus/templates/deployment.yaml
  resources/helm/v1.1/istio/charts/prometheus/templates/secrets.yaml
Labels: okay to merge, size/L

#383 MAITRA-1289 use Maistra for community CSV
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/1.1.0/maistraoperator.v1.1.0.clusterserviceversion.yaml
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/L

#381 MAISTRA-1288 pull in latest profiles from maistra-1.0
  Makefile
  resources/smcp-templates/v1.0/base
Labels: okay to merge, size/XS

#384 MAISTRA-1295 add aggregate project roles for view/edit of istio.io re…
  pkg/bootstrap/crds.go
  pkg/bootstrap/crds_test.go
Labels: okay to merge, size/M

#386 MAISTRA-1295 ignore conflict errors when creating/updating aggregate …
  pkg/bootstrap/crds.go
  pkg/bootstrap/crds_test.go
Labels: okay to merge, size/S

#387 MAISTRA-1160 Make sure custom Jaeger instances are accessible through…
  resources/helm/overlays/istio/templates/networkpolicy.yaml
  resources/helm/v1.1/istio/templates/networkpolicy.yaml
Labels: okay to merge, size/L

#389 update servicemesh csv replaces to 1.0.10
  Makefile
  manifests-servicemesh/1.1.0/servicemeshoperator.v1.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#388 Controller test framework improvements
  pkg/controller/common/test/api.go
  pkg/controller/common/test/manager.go
  pkg/controller/common/test/runner.go
Labels: okay to merge, size/L

#390 MAISTRA-1194 Remove applied version from SMCP
  pkg/apis/maistra/v1/servicemeshcontrolplane_types.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/M

#391 MAISTRA-1160 Simplify external Jaeger NetworkPolicy to ignore instanc…
  resources/helm/overlays/istio/templates/networkpolicy.yaml
  resources/helm/v1.1/istio/templates/networkpolicy.yaml
Labels: okay to merge, size/M
