Repository maistra/istio-operator, pull requests merged in 2021-03, with the labels that each got.

#683 MAISTRA-2099 maistra updates for istio 1.8
  Makefile
  build/patch-charts.sh
  resources/helm/v2.1/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.1/gateways/istio-ingress/templates/deployment.yaml
  resources/helm/v2.1/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/clusterrole.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/endpoints.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/role.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/rolebinding.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/services.yaml
  resources/helm/v2.1/istio-init/files/workloadgroups.networking.istio.io.crd.yaml
  resources/helm/v2.1/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.1/istio_cni/templates/clusterrole.yaml
  resources/helm/v2.1/istio_cni/templates/clusterrolebinding.yaml
  resources/helm/v2.1/istio_cni/templates/configmap.yaml
  resources/helm/v2.1/istio_cni/templates/serviceaccount.yaml
  resources/helm/v2.1/mesh-config/templates/telemetryv2_1.6.yaml
  resources/helm/v2.1/mesh-config/templates/telemetryv2_1.7.yaml
  resources/helm/v2.1/mesh-config/templates/telemetryv2_1.8.yaml
Labels: okay to merge, size/XL

#685 MAISTRA-2169 Show Projects instead of Namespaces in ServiceMeshMember form
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.0.2/maistraoperator.v2.0.2.clusterserviceversion.yaml
  manifests-servicemesh/2.0.2/servicemeshoperator.v2.0.2.clusterserviceversion.yaml
Labels: cherrypick/maistra-2.1, okay to merge, size/S

#684 MAISTRA-2192 Concurrent reconciliation of member namespaces
  cmd/manager/main.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
Labels: okay to merge, size/L

#686 MAISTRA-2206 Remove member-of label from SMCP namespace on deletion
  pkg/controller/common/metadata.go
  pkg/controller/servicemesh/controlplane/deleter.go
  pkg/controller/servicemesh/controlplane/namespace_labels.go
  pkg/controller/servicemesh/controlplane/namespace_labels_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: cherrypick/maistra-1.1, cherrypick/maistra-2.1, okay to merge, size/L

#688 MAISTRA-2209: temporarily add perms to list/watch namespaces for istiod
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/v2.1/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.1/istio-control/istio-discovery/files/injection-template.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/meshclusterrole.yaml
Labels: don't squash, okay to merge, size/S

#694 MAISTRA-2227 ignore empty yaml bytes
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/manifestprocessing_test.go
Labels: okay to merge, size/M

#692 MAISTRA-2169 Show Projects instead of Namespaces in ServiceMeshMember form
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#695 MAISTRA-2229 ignore empty yaml bytes
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/manifestprocessing_test.go
Labels: okay to merge, size/M
