Repository maistra/istio-operator, pull requests merged in 2021-09, with the labels that each got.

#828 MAISTRA-2405 Ensure SMMR.status.MemberStatuses contains entry for each member
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/S

#831 MAISTRA-2613 Update to latest Istio 1.9.8
  Makefile
  build/download-charts.sh
  resources/helm/v2.1/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/mutatingwebhook.yaml
Labels: okay to merge, size/XS

#833 MAISTRA-2637 Disable ingress controller in istiod
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
Labels: okay to merge, size/XS

#835 MAISTRA-2644 Convert v1beta1 webhookconfigurations to v1 when deploying istio manifests
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/manifestprocessing_test.go
Labels: okay to merge, size/L

#834 MAISTRA-2641 Prune non-deprecated versions of Ingress and WebhookConfigurations
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/rbac.yaml
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
  pkg/controller/servicemesh/controlplane/pruner.go
Labels: okay to merge, size/S

#832 MAISTRA-2117 Mount smcp-templates ConfigMap if it exists
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
  pkg/controller/servicemesh/controlplane/profiles_test.go
Labels: okay to merge, size/M

#823 MAISTRA-2627 Remove namespace field from istiod-internal ClusterRoleBinding definition
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrolebinding.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/meshclusterrolebinding.yaml
Labels: okay to merge, size/XS

#825 MAISTRA-2629 Register maistra/v2 CR metrics
  cmd/manager/main.go
Labels: okay to merge, size/XS, cherrypick/maistra-2.1

#824 MAISTRA-2627 Remove namespace field from istiod-internal ClusterRoleBinding definition
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrolebinding.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/meshclusterrolebinding.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/meshclusterrolebinding.yaml
Labels: okay to merge, size/XS

#839 Log error in RenderChart
  pkg/controller/common/helm/helm.go
Labels: okay to merge, size/XS

#836 OSSM-569 Use default resources for prometheus sidecar
  build/patch-prometheus.sh
  resources/helm/v2.0/istio-telemetry/prometheus/templates/deployment.yaml
Labels: okay to merge, size/S

#840 Run make gen
  resources/helm/v2.0/istio-init/files/servicemeshextensions.maistra.io.crd.yaml
  resources/helm/v2.0/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.0/istio_cni/templates/clusterrole.yaml
  resources/helm/v2.0/istio_cni/templates/clusterrolebinding.yaml
Labels: okay to merge, size/L

#842 OSSM-569 Use default resources for prometheus sidecar
  resources/helm/overlays/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.1/istio-telemetry/prometheus/templates/deployment.yaml
Labels: okay to merge, size/S

#844 Fix post-submit job
  Makefile
Labels: okay to merge, size/XS

#846 MAISTRA-2656 Fix missing DNS entries for services imported through federation
  build/patch-charts.sh
  resources/helm/overlays/global.yaml
  resources/helm/v2.1/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.1/gateways/istio-egress/values.yaml
  resources/helm/v2.1/gateways/istio-ingress/templates/deployment.yaml
  resources/helm/v2.1/gateways/istio-ingress/values.yaml
  resources/helm/v2.1/global.yaml
Labels: okay to merge, size/S

#847 MAISTRA-1399 default to NetworkPolicy if an unknown network type is in use
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
Labels: okay to merge, size/S, cherrypick/maistra-2.1

#848 MAISTRA-1399 default to NetworkPolicy if an unknown network type is i…
  pkg/controller/servicemesh/member/namespace_reconciler.go
Labels: okay to merge, size/S

#850 OSSM-543 Add 2.1 to "Control Plane Version" dropdown
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/S

#841 MAISTRA-2322 Move Kiali affinity config to SMCP.spec.runtime.components
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.1.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.1.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/kiali.go
  pkg/apis/maistra/conversion/kiali_test.go
  pkg/apis/maistra/conversion/runtime.go
  pkg/apis/maistra/conversion/runtime_test.go
  pkg/apis/maistra/v2/kiali.go
  pkg/apis/maistra/v2/runtime.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/versions/strategy_v2_1.go
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.1/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XXL

#849 MAISTRA-2668 Set sideEffects on webhooks
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/manifestprocessing_test.go
Labels: okay to merge, size/L

#854 MAISTRA-2654 Replace remaining occurrences of 2.0.7 with 2.0.8
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.0.8/maistraoperator.v2.0.8.clusterserviceversion.yaml
  manifests-servicemesh/2.0.8/servicemeshoperator.v2.0.8.clusterserviceversion.yaml
  pkg/controller/servicemesh/controlplane/profiles_test.go
  resources/smcp-templates/v2.0/maistra
  resources/smcp-templates/v2.0/servicemesh
Labels: okay to merge, size/L

#855 MAISTRA-2671 Ensure Galley can start on OCP 4.9+
  build/patch-charts.sh
  resources/helm/v1.1/istio/charts/galley/templates/deployment.yaml
Labels: okay to merge, size/XS

#857 [maistra-2.0] Run make gen
  resources/helm/v1.1/istio/charts/galley/templates/deployment.yaml
Labels: okay to merge, size/XS

#853 MAISTRA-2668 Set sideEffects on webhooks
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/manifestprocessing_test.go
Labels: okay to merge, size/L

#859 run make gen
  pkg/controller/servicemesh/controlplane/profiles_test.go
  resources/helm/v1.1/istio/charts/galley/templates/deployment.yaml
  resources/smcp-templates/v2.0/maistra
  resources/smcp-templates/v2.0/servicemesh
Labels: okay to merge, size/XS

#852 MAISTRA-2669: Webhook controller should handle secret deletion
  pkg/controller/servicemesh/webhookca/controller.go
Labels: okay to merge, size/XS

#861 MAISTRA-2686 Clear configuredMembers when SMCP is deleted
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/M

#862 MAISTRA-2688 Ensure pruner never deletes RoleBindings in member namespaces
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/member/namespace_reconciler.go
  pkg/controller/servicemesh/member/namespace_reconciler_test.go
  pkg/controller/servicemesh/member/ovs_networkpolicy.go
  pkg/controller/servicemesh/member/ovs_networkpolicy_test.go
Labels: okay to merge, size/M
