Repository maistra/istio-operator, pull requests merged in 2021-04, with the labels that each got.

#648 MAISTRA-1351 Redesign ServiceMeshMemberRoll and ServiceMeshMember controllers
  deploy/examples/maistra_v1_servicemeshmember_cr_minimal.yaml
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  docs/crd/maistra.io_ServiceMeshMemberRoll_v1.adoc
  docs/crd/maistra.io_ServiceMeshMember_v1.adoc
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
  manifests-maistra/2.1.0/servicemeshmemberrolls.crd.yaml
  manifests-maistra/2.1.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/2.1.0/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/2.1.0/servicemeshmembers.crd.yaml
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
  pkg/apis/maistra/status/status.go
  pkg/apis/maistra/v1/servicemeshmember_types.go
  pkg/apis/maistra/v1/servicemeshmemberroll_types.go
  pkg/apis/maistra/v1/zz_generated.deepcopy.go
  pkg/controller/common/finalizers.go
  pkg/controller/common/test/client.go
  pkg/controller/common/util.go
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/member/namespace_reconciler.go
  pkg/controller/servicemesh/member/namespace_reconciler_test.go
  pkg/controller/servicemesh/member/ovs_multitenant.go
  pkg/controller/servicemesh/member/ovs_multitenant_test.go
  pkg/controller/servicemesh/member/ovs_networkpolicy.go
  pkg/controller/servicemesh/member/ovs_networkpolicy_test.go
  pkg/controller/servicemesh/member/ovs_subnet.go
  pkg/controller/servicemesh/member/ovs_subnet_test.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/XXL

#700 Run make gen
  resources/helm/v2.0/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/_affinity.tpl
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/L

#701 Run make gen
  resources/helm/v2.0/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/_affinity.tpl
  resources/helm/v2.0/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.1/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/_affinity.tpl
  resources/helm/v2.1/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.1/istio-control/istio-discovery/values.yaml
Labels: okay to merge, size/L

#697 Fix typo in grafana.go
  pkg/apis/maistra/conversion/grafana.go
Labels: ok-to-test, okay to merge, size/XS

#696 MAISTRA-2023 Add support for specifying kiali resource and scheduling constraints
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  docs/crd/maistra.io_ServiceMeshControlPlane_AddonsConfig_v2.adoc
  manifests-maistra/2.0.3/maistraoperator.v2.0.3.clusterserviceversion.yaml
  manifests-maistra/2.0.3/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.3/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.0.3/servicemeshoperator.v2.0.3.clusterserviceversion.yaml
  pkg/apis/maistra/conversion/kiali.go
  pkg/apis/maistra/conversion/kiali_test.go
  pkg/apis/maistra/v1/helmvalues.go
  pkg/apis/maistra/v2/kiali.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.0/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XXL

#698 MAISTRA-2261 Ensure ServiceMeshMember is reconciled on SMCP events
  pkg/controller/servicemesh/member/controller.go
  resources/helm/v2.0/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: don't squash, okay to merge, size/S

#699 MAISTRA-1956 Stabilize accessible_namespaces in the Kiali resource
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.1/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/S

#702 MAISTRA-2253 Ensure correct conversion for all 2.x versions
  pkg/apis/maistra/conversion/cluster.go
  pkg/apis/maistra/conversion/cluster_test.go
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/conversion/gateways_test.go
  pkg/apis/maistra/conversion/grafana_test.go
  pkg/apis/maistra/conversion/jaeger_test.go
  pkg/apis/maistra/conversion/kiali_test.go
  pkg/apis/maistra/conversion/logging_test.go
  pkg/apis/maistra/conversion/policy.go
  pkg/apis/maistra/conversion/policy_test.go
  pkg/apis/maistra/conversion/prometheus_test.go
  pkg/apis/maistra/conversion/proxy_test.go
  pkg/apis/maistra/conversion/runtime_test.go
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/conversion/techpreviews_test.go
  pkg/apis/maistra/conversion/telemetry.go
  pkg/apis/maistra/conversion/telemetry_test.go
  pkg/apis/maistra/conversion/threescale_test.go
  pkg/controller/versions/conversion_strategy_v1_x.go
  pkg/controller/versions/conversion_strategy_v2_x.go
  pkg/controller/versions/strategy_v1_0.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
  pkg/controller/versions/versions.go
Labels: okay to merge, size/XXL

#704 MAISTRA-2288 Set default number of ServiceMeshMember reconcilers to 10
  cmd/manager/main.go
Labels: okay to merge, size/XS

#705 Run make gen to pull in istio chart changes
  resources/helm/v2.1/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.1/istio-control/istio-discovery/values.yaml
Labels: okay to merge, size/XS

#651 MAISTRA-2047 Allow operator to reconcile other SMCPs while waiting for cache to sync
  pkg/bootstrap/cni.go
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/manifestprocessing_test.go
  pkg/controller/hacks/hacks.go
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/deleter.go
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
  pkg/controller/servicemesh/controlplane/manifestprocessing_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge, size/L

#707 MAISTRA-2253 Sidecar injection fails if tracing is set to None
  pkg/apis/maistra/conversion/jaeger_test.go
  pkg/apis/maistra/conversion/tracing.go
Labels: okay to merge, size/XS

#708 MAISTRA-2209 Remove namespace permissions from pilot
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/meshclusterrole.yaml
Labels: okay to merge, size/S

#703 MAISTRA-2293 chart updates for MeshFederation resource support
  build/generate-crds.sh
  build/patch-charts.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  docs/crd/maistra.io_ServiceMeshControlPlane_ControlPlaneClusterConfig_v2.adoc
  manifests-maistra/2.1.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.1.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/v2/cluster.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  resources/helm/overlays/istio-init/files/servicemeshextensions.maistra.io.crd.yaml
  resources/helm/v2.1/gateways/istio-ingress/templates/meshexpansion.yaml
  resources/helm/v2.1/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/role.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/rolebinding.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/service.yaml
  resources/helm/v2.1/istio-init/files/meshfederations.maistra.io.crd.yaml
  resources/helm/v2.1/istio-init/files/servicemeshextensions.maistra.io.crd.yaml
Labels: don't squash, okay to merge, size/L
