Repository maistra/istio-operator, pull requests merged in 2021-07, with the labels that each got.

#756 Fix invalid sidecarInjectorWebhook config
  build/patch-charts.sh
  resources/helm/v2.1/istio-control/istio-discovery/templates/mutatingwebhook.yaml
Labels: okay to merge, size/M

#761 MAISTRA-2462 Cache NetworkAttachmentDefinition objects
  go.mod
  go.sum
  pkg/apis/addtoscheme_dependencies.go
  pkg/controller/common/metadata.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/member/namespace_reconciler.go
  pkg/controller/servicemesh/member/namespace_reconciler_test.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/LICENSE
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/types.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/modules.txt
Labels: okay to merge, size/XL

#763 MAISTRA-2486 Fix flaky test TestMAISTRA_2040
  pkg/controller/servicemesh/webhookca/maistra2040_test.go
Labels: okay to merge, size/S

#755 Added missing CRD file error handling for the CRD tool
  resources/helm/v2.1/istio-init/files/federationstatuses.maistra.io.crd.yaml
  resources/helm/v2.1/istio-init/files/meshfederations.maistra.io.crd.yaml
  resources/helm/v2.1/istio-init/files/serviceexports.maistra.io.crd.yaml
  resources/helm/v2.1/istio-init/files/serviceimports.maistra.io.crd.yaml
  resources/helm/v2.1/istio-init/files/servicemeshextensions.maistra.io.crd.yaml
  tools/crd/main.go
Labels: ok-to-test, okay to merge, size/M

#757 MAISTRA-2476 Handle update conflicts in podlocality controller
  pkg/controller/podlocality/controller.go
Labels: okay to merge, size/XS

#760 MAISTRA-2425 and MAISTRA-2426 - Federation API Updates
  pkg/controller/servicemesh/controlplane/integration_test.go
  resources/helm/v2.1/istio-init/files/federationstatuses.maistra.io.crd.yaml
  resources/helm/v2.1/istio-init/files/meshfederations.maistra.io.crd.yaml
Labels: okay to merge, size/L

#765 MAISTRA-2418: Remove wasmExtensions section from base template
  pkg/controller/servicemesh/controlplane/profiles_test.go
  resources/smcp-templates/v2.1/base
Labels: okay to merge, size/XS

#754 Update comment for workingDir hack
  build/patch-charts.sh
Labels: okay to merge, size/XS

#753 Fix namespace deletion issues in operator
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler_test.go
Labels: don't squash, okay to merge, size/L

#766 Download charts from maistra-2.1 branch again
  Makefile
  build/download-charts.sh
Labels: okay to merge, size/XS

#767 MAISTRA-2493 No need to turn ingressControllerMode=off manually
  pkg/controller/versions/strategy_v2_1.go
Labels: okay to merge, size/XS

#772 MAISTRA-2512: add architecture labels
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/S

#774 MAISTRA-2511: Set minimum supported version as defined in the spec file
  build/build.sh
  pkg/bootstrap/cni.go
  pkg/bootstrap/cni_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/versions/versions.go
  pkg/version/version.go
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v2.1/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/L

#777 MAISTRA-2475 Fix initialization and update of Kiali.spec.deployment.accessible_namespaces
  pkg/bootstrap/cni.go
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/manifestprocessing_test.go
  pkg/controller/servicemesh/controlplane/hooks.go
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.1/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/M

#779 MAISTRA-2524 Cache config.openshift.io/Network and network.openshift.io/ClusterNetwork
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/rbac.yaml
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
  pkg/apis/addtoscheme_dependencies.go
  pkg/controller/servicemesh/member/namespace_reconciler.go
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/stringsource.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: okay to merge, size/XXL

#778 MAISTRA-2523 Configure tracing address correctly
  pkg/controller/versions/strategy_v2_1.go
Labels: okay to merge, size/XS

#780 MAISTRA-2525: Remove hostNetwork permission from CNI
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v2.1/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/S

#781 MAISTRA-2530 Fix wasmExtensions.cacher image field name in default SMCP template
  resources/smcp-templates/v2.1/maistra
  resources/smcp-templates/v2.1/servicemesh
Labels: okay to merge, size/XS

#782 MAISTRA-2531 Fix wasmExtensions.cacher image field name in default SMCP tempalte
  resources/smcp-templates/v2.0/maistra
  resources/smcp-templates/v2.0/servicemesh
Labels: okay to merge, size/XS

#785 Run make gen update-2.1-charts
  resources/helm/v2.1/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.1/istio-control/istio-discovery/files/injection-template.yaml
  resources/smcp-templates/v2.0/maistra
  resources/smcp-templates/v2.0/servicemesh
Labels: okay to merge, size/S

#783 MAISTRA-2536 Fix global proxy env injection
  pkg/apis/maistra/conversion/proxy.go
  pkg/apis/maistra/conversion/proxy_test.go
  pkg/apis/maistra/conversion/runtime.go
  pkg/apis/maistra/v1/helmvalues.go
Labels: okay to merge, size/L

#776 MAISTRA-2459 Don't treat NotFound as an error when deleting a resource
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
  pkg/controller/servicemesh/memberroll/ovs_networkpolicy.go
Labels: okay to merge, size/XS

#789 MAISTRA-2538 Operator needs to set Kiali CR external_services fields
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.1/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XS
