Repository maistra/istio-operator, pull requests merged in 2021-01, with the labels that each got.

#658 MAISTRA-2062: updated maistra CSV to support 1.1.11
  deploy/maistra-operator.yaml
  deploy/src/deployment-maistra.yaml
  manifests-maistra/2.0.1/maistraoperator.v2.0.1.clusterserviceversion.yaml
Labels: okay to merge, size/M

#649 MAISTRA-2055 make doc generation stable across executions
  tools/pkg/doc/gen.go
Labels: okay to merge, size/M

#659 Update metadata.go to clarify mesh generation
  pkg/controller/common/metadata.go
Labels: okay to merge, size/XS

#657 MAISTRA-2060: Point to Red Hat Jira for issues
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: cherrypick/maistra-2.1, okay to merge, size/S

#656 Fix indentation on sample smcp v2
  pkg/apis/maistra/v2/smcp_new.yaml
Labels: cherrypick/maistra-2.1, okay to merge, size/M

#671 MAISTRA-2097: Update metadata to include the architecture labels
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.0.2/maistraoperator.v2.0.2.clusterserviceversion.yaml
  manifests-servicemesh/2.0.2/servicemeshoperator.v2.0.2.clusterserviceversion.yaml
Labels: cherrypick/maistra-2.1, okay to merge, size/S

#672 MAISTRA-2102: Add support for a minimum supported version of the mesh…
  pkg/bootstrap/cni.go
  pkg/bootstrap/cni_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/versions/versions.go
  pkg/version/version.go
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v2.0/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/L

#673 MAISTRA-2102: Add support for a minimum supported version of the mesh…
  build/build.sh
Labels: okay to merge, size/XS
