Repository maistra/istio-operator, pull requests merged in 2021-06, with the labels that each got.

#724 MAISTRA-2385 Fix reconciliation of SMMR with large number of members when ovs-multitenant is used
  pkg/controller/servicemesh/member/namespace_reconciler.go
  pkg/controller/servicemesh/member/ovs_multitenant.go
  pkg/controller/servicemesh/member/ovs_multitenant_test.go
Labels: okay to merge, size/L

#721 MAISTRA-2309 chart updates for FederationStatus resource support
  pkg/controller/servicemesh/controlplane/integration_test.go
  resources/helm/v2.1/istio-control/istio-discovery/templates/role.yaml
  resources/helm/v2.1/istio-init/files/federationstatuses.maistra.io.crd.yaml
Labels: okay to merge, size/L

#730 MAISTRA-2402: Remove the default values from CRD's
  build/generate-crds.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.1.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.1.0/servicemeshcontrolplanes.crd.yaml
Labels: okay to merge, size/S

#731 Remove unused version pkg
  version/version.go
Labels: okay to merge, size/XS

#739 Don't set the IMAGE variable by default
  Makefile
Labels: okay to merge, size/XS

#740 MAISTRA-2416 Fix incorrect log statements in SMMR controller
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, size/XS

#734 MAISTRA-2406 ensure rewriteApplicationProbes setting is propagated to…
  pkg/apis/maistra/conversion/proxy.go
  pkg/controller/servicemesh/controlplane/profiles_test.go
Labels: okay to merge, size/M

#745 MAISTRA-2435: Update operator metadata for maistra 1.1.16
  resources/smcp-templates/v1.1/base
Labels: okay to merge, size/XS

#741 MAISTRA-2254: Fix permissions to wasm-cacher ClusterRole
  resources/helm/overlays/wasm-extensions/templates/clusterrole.yaml
  resources/helm/v2.1/wasm-extensions/templates/clusterrole.yaml
Labels: okay to merge, size/S

#747 MAISTRA-2418: Enable WASM Extensions by default
  resources/helm/overlays/wasm-extensions/values.yaml
  resources/helm/v2.1/wasm-extensions/values.yaml
Labels: okay to merge, size/XS

#748 MAISTRA-2466: Bump Kiali version to v1.36
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.1/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: needs-ok-to-test, ok-to-test, okay to merge, size/XS

#752 Run make gen
  resources/helm/v2.0/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.0/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, size/S

#749 MAISTRA-2458 Include namespace in logs produced by removeNamespaceFromMesh()
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
Labels: okay to merge, size/XS

#750 MAISTRA-2460 Only log "ignoring control plane namespace" when it's in SMMR.spec.members
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, size/S
