Repository maistra/istio-operator, pull requests merged in 2021-08, with the labels that each got.

#790 MAISTRA-2544 Improve SMCP status condition message on operator upgrade
  pkg/apis/maistra/status/status.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/S

#791 MAISTRA-2528 Enable DNS Capture for proxies by default
  build/patch-charts.sh
  resources/helm/overlays/global.yaml
  resources/helm/v2.1/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.1/gateways/istio-egress/values.yaml
  resources/helm/v2.1/gateways/istio-ingress/templates/deployment.yaml
  resources/helm/v2.1/gateways/istio-ingress/values.yaml
  resources/helm/v2.1/global.yaml
Labels: okay to merge, size/M

#797 MAISTRA-2552: Add a check for 2.1 CNI images
  pkg/controller/common/cni/cni.go
Labels: okay to merge, size/XS

#793 MAISTRA-2547 Ensure status is updated when status.readiness.components changes
  pkg/controller/servicemesh/controlplane/readiness.go
Labels: okay to merge, size/S

#795 MAISTRA-2532 Gather readiness information for gateways outside control plane namespace
  pkg/controller/servicemesh/controlplane/readiness.go
  pkg/controller/servicemesh/controlplane/readiness_test.go
Labels: okay to merge, size/L

#792 MAISTRA-2548 Reject SMCP if default gateway targets a non-member namespace
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/versions/util.go
  pkg/controller/versions/util_test.go
Labels: okay to merge, size/L

#799 MAISTRA-2557 add support for processing v1 CRDs
  pkg/bootstrap/crds.go
  pkg/bootstrap/crds_test.go
  pkg/controller/common/test/api.go
  pkg/controller/common/test/assertions.go
  pkg/controller/common/test/verifiers.go
  pkg/controller/hacks/hacks.go
  pkg/controller/servicemesh/controlplane/integration_test.go
Labels: okay to merge, size/L

#802 Fix TestDefaultInstall
  pkg/controller/servicemesh/controlplane/integration_test.go
Labels: okay to merge, size/XS

#803 MAISTRA-2411 Create NetworkPolicy for additional ingress gateways
  pkg/controller/servicemesh/controlplane/gateways_test.go
  resources/helm/overlays/gateways/istio-ingress/templates/networkpolicy.yaml
  resources/helm/v2.0/gateways/istio-ingress/templates/networkpolicy.yaml
Labels: okay to merge, size/M

#805 Run make gen
  resources/helm/v2.0/gateways/istio-ingress/templates/networkpolicy.yaml
Labels: okay to merge, size/XS

#800 MAISTRA-2395: Implement Rate Limiting
  .gitignore
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
  pkg/apis/maistra/v2/runtime.go
  pkg/controller/common/config.go
  pkg/controller/common/util.go
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/profiles_test.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/controlplane/rls_test.go
  pkg/controller/versions/rendering_strategy_v2_x.go
  pkg/controller/versions/strategy_v2_1.go
  resources/helm/overlays/rls/Chart.yaml
  resources/helm/overlays/rls/templates/autoscale.yaml
  resources/helm/overlays/rls/templates/configmap.yaml
  resources/helm/overlays/rls/templates/deployment.yaml
  resources/helm/overlays/rls/templates/service.yaml
  resources/helm/overlays/rls/templates/serviceaccount.yaml
  resources/helm/overlays/rls/values.yaml
  resources/helm/v2.1/rls/Chart.yaml
  resources/helm/v2.1/rls/templates/autoscale.yaml
  resources/helm/v2.1/rls/templates/configmap.yaml
  resources/helm/v2.1/rls/templates/deployment.yaml
  resources/helm/v2.1/rls/templates/service.yaml
  resources/helm/v2.1/rls/templates/serviceaccount.yaml
  resources/helm/v2.1/rls/values.yaml
  resources/smcp-templates/v2.1/maistra
  resources/smcp-templates/v2.1/servicemesh
Labels: okay to merge, size/XL

#801 MAISTRA-2556 Default gateway label 'app' to gateway (service) name
  pkg/controller/common/test/verifiers.go
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/gateways_test.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
Labels: okay to merge, size/M

#813 MAISTRA-2584 ensure x-kubernetes-preserve-unknown-fields is added to …
  pkg/bootstrap/crds.go
  pkg/controller/hacks/hacks.go
Labels: okay to merge, size/M

#811 Remove duplicate prometheus config from sample smcp v2
  pkg/apis/maistra/v2/smcp_new.yaml
Labels: okay to merge, size/XS

#804 MAISTRA-2411 Create NetworkPolicy for additional ingress gateways
  pkg/controller/servicemesh/controlplane/gateways_test.go
  resources/helm/overlays/gateways/istio-ingress/templates/networkpolicy.yaml
  resources/helm/v2.1/gateways/istio-ingress/templates/networkpolicy.yaml
Labels: okay to merge, size/M

#796 MAISTRA-2546 Ensure gateways outside control plane namespace trigger SMCP reconciliation
  pkg/bootstrap/cni.go
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/manifestprocessing_test.go
  pkg/controller/common/metadata.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/manifestprocessing.go
Labels: okay to merge, size/M

#794 Move operator installation instruction
  DEVEL.md
  README.md
Labels: okay to merge, size/L

#822 MAISTRA-2625: Replace rbac.authorization.k8s.io/v1beta1 with v1
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/rbac.yaml
  resources/helm/overlays/istio_cni/templates/clusterrole.yaml
  resources/helm/overlays/istio_cni/templates/clusterrolebinding.yaml
  resources/helm/v2.1/istio_cni/templates/clusterrole.yaml
  resources/helm/v2.1/istio_cni/templates/clusterrolebinding.yaml
Labels: okay to merge, size/S

#826 MAISTRA-2589 Do not allow 2.1 control planes with Mixer enabled
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/versions/strategy_v2_1.go
Labels: okay to merge, size/S
