Repository maistra/istio-operator, pull requests merged in 2021-02, with the labels that each got.

#677 [maistra-2.1] Import latest maistra-2.0 charts
  resources/helm/v2.0/istio_cni/templates/daemonset.yaml
  resources/helm/v2.1/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.1/gateways/istio-ingress/templates/deployment.yaml
Labels: okay to merge, size/S

#676 MAISTRA-2081 Add maistra.io apiGroup access to aggregate roles
  pkg/bootstrap/crds.go
Labels: okay to merge, size/XS

#678 MAISTRA-2130 Make sure to copy all 2.0 templates
  Makefile
Labels: okay to merge

#680 MAISTRA-2136 Add CNI 2.1 support
  pkg/bootstrap/cni.go
  resources/helm/overlays/istio_cni/templates/configmap.yaml
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v2.1/istio_cni/templates/configmap.yaml
  resources/helm/v2.1/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/L

#681 MAISTRA-2147: Make architecture labels configurable in the CSV
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.0.2/maistraoperator.v2.0.2.clusterserviceversion.yaml
  manifests-servicemesh/2.0.2/servicemeshoperator.v2.0.2.clusterserviceversion.yaml
Labels: cherrypick/maistra-2.1, okay to merge, size/S
