Repository maistra/istio-operator, pull requests merged in 2021-05, with the labels that each got.

#710 MAISTRA-2329: Sync CRD's with maistra/istio
  resources/helm/v2.1/istio-init/files/meshfederations.maistra.io.crd.yaml
  resources/helm/v2.1/istio-init/files/servicemeshextensions.maistra.io.crd.yaml
Labels: okay to merge, size/L

#718 MAISTRA-2378 Fix reconciliation of SMMR with large number of members when ovs-multitenant is used
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/namespace_reconciler.go
  pkg/controller/servicemesh/memberroll/ovs_multitenant.go
  pkg/controller/servicemesh/memberroll/ovs_multitenant_test.go
Labels: okay to merge, size/L

#719 MAISTRA-2376 wasm-cacher SA must have pull secrets
  resources/helm/overlays/wasm-extensions/templates/serviceaccount.yaml
  resources/helm/v2.1/wasm-extensions/templates/serviceaccount.yaml
Labels: okay to merge, size/S

#723 OSSM-470: Bump Kiali version to v1.33
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.1/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XS

#713 MAISTRA-2295 chart updates for ServiceImport resource support
  pkg/controller/servicemesh/controlplane/integration_test.go
  resources/helm/v2.1/istio-control/istio-discovery/templates/role.yaml
  resources/helm/v2.1/istio-init/files/serviceexports.maistra.io.crd.yaml
  resources/helm/v2.1/istio-init/files/serviceimports.maistra.io.crd.yaml
Labels: okay to merge, size/L

#725 Fix broken release notes link used in CSV
  build/generate-manifests.sh
  manifests-servicemesh/2.1.0/servicemeshoperator.v2.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS
