Repository maistra/istio-operator, pull requests merged in 2021-11, with the labels that each got.

#864 MAISTRA-2723: Update community images URL
  deploy/maistra-operator.yaml
  deploy/src/deployment-maistra.yaml
  manifests-maistra/2.1.0/maistraoperator.v2.1.0.clusterserviceversion.yaml
Labels: okay to merge, size/M

#865 MAISTRA-2172 Return error if 3scale is enabled in 2.1
  pkg/controller/versions/strategy_v2_1.go
Labels: okay to merge, size/S

#628 test case for additional container support in gateway
  pkg/apis/maistra/conversion/gateways_test.go
Labels: okay to merge, size/M, cherrypick/maistra-2.1

#866 OSSM-734: Remove completely initContainers from injection template
  build/patch-charts.sh
  resources/helm/v2.1/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, size/L

#787 MAISTRA-2545: Disable option for operator webhook management
  cmd/manager/main.go
  pkg/controller/common/config.go
  pkg/controller/servicemesh/webhookca/controller.go
  pkg/controller/servicemesh/webhooks/server.go
Labels: okay to merge, size/S, ok-to-test
