Repository maistra/istio-operator, pull requests merged in 2022-07, with the labels that each got.

#910 OSSM-218: requeue reconcilation when Jaeger or Grafana routes are empty
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/controller/common/reconcile_result.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/servicemesh/controlplane/addons.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/controller_test.go
  pkg/controller/servicemesh/controlplane/hooks.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/L, ok-to-test

#923 OSSM-1466 Remove debug symbols from go build
  build/build.sh
Labels: okay to merge, size/XS

#936 OSSM-1107 Add jwksResolverCA field
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.2.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.2.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/v2/security.go
  pkg/apis/maistra/v2/smcp_new.yaml
Labels: okay to merge, size/L, cherrypick/maistra-2.3

#940 OSSM-1718 Allow deployment of gateways to not-yet-configured namespaces
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/versions/util.go
  pkg/controller/versions/util_test.go
Labels: okay to merge, size/L

#951 OSSM-1751: v2.2 was missing from the dropdown menu
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.2.1/maistraoperator.v2.2.1.clusterserviceversion.yaml
  manifests-servicemesh/2.2.1/servicemeshoperator.v2.2.1.clusterserviceversion.yaml
Labels: okay to merge, size/S

#953 Set the example version to 2.2
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.2.1/maistraoperator.v2.2.1.clusterserviceversion.yaml
  manifests-servicemesh/2.2.1/servicemeshoperator.v2.2.1.clusterserviceversion.yaml
Labels: okay to merge, size/S

#955 OSSM-1775: Fix 3scale version
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-servicemesh/2.2.2/servicemeshoperator.v2.2.2.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#946 OSSM-1805: Requeue patching Kiali if Kiali resource is not available
  pkg/controller/servicemesh/controlplane/addons.go
  pkg/controller/servicemesh/controlplane/addons_test.go
Labels: okay to merge, size/S, cherrypick/maistra-2.2
