Repository maistra/istio-operator, pull requests merged in 2022-03, with the labels that each got.

#884 OSSM-303 | Make creating OpenShift Route for istio-ingressgateway optional
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.1.1/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.1.1/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/conversion/gateways_test.go
  pkg/apis/maistra/v2/gateways.go
  pkg/apis/maistra/v2/smcp_new.yaml
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/servicemesh/controlplane/gateways_test.go
  resources/helm/overlays/gateways/istio-ingress/templates/istio-ingressgateway-route.yaml
  resources/helm/v2.1/gateways/istio-ingress/templates/istio-ingressgateway-route.yaml
  resources/helm/v2.1/gateways/istio-ingress/values.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
Labels: okay to merge, size/L, ok-to-test

#891 OSSM-1162: Remove a non-existing annotation
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v2.1/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/S

#893 OSSM-1162: Remove a non-existing annotation
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v2.1/istio_cni/templates/daemonset.yaml
  resources/helm/v2.2/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/S

#904 Remove unneeded file
  resources/helm/overlays/istio-cni/templates/configmap-cni.yaml.snippet
Labels: okay to merge, size/M

#905 OSSM-1107 Add jwksResolverExtraRootCA feature
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.2.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.2.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/v2/security.go
  pkg/apis/maistra/v2/smcp_new.yaml
Labels: okay to merge, size/L
