Repository maistra/istio-operator, pull requests merged in 2022-05, with the labels that each got.

#903 OSSM-1279 Run Maistra on Kubernetes
  build/patch-charts.sh
  pkg/bootstrap/cni.go
  pkg/bootstrap/cni_test.go
  pkg/controller/common/cni/cni.go
  pkg/controller/servicemesh/member/namespace_reconciler.go
  pkg/controller/versions/strategy_v2_2.go
  resources/helm/overlays/gateways/istio-ingress/templates/istio-ingressgateway-route.yaml
  resources/helm/overlays/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/ingress.yaml
  resources/helm/overlays/istio_cni/templates/configmap.yaml
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v2.2/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.2/gateways/istio-egress/templates/injected-deployment.yaml
  resources/helm/v2.2/gateways/istio-ingress/templates/deployment.yaml
  resources/helm/v2.2/gateways/istio-ingress/templates/injected-deployment.yaml
  resources/helm/v2.2/gateways/istio-ingress/templates/istio-ingressgateway-route.yaml
  resources/helm/v2.2/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/v2.2/istio-telemetry/prometheus/templates/ingress.yaml
  resources/helm/v2.2/istio_cni/templates/configmap.yaml
  resources/helm/v2.2/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/L

#909 OSSM-1228 Reduce differences between Maistra and upstream CNI
  pkg/bootstrap/cni.go
  pkg/controller/common/config.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  resources/helm/overlays/istio_cni/templates/clusterrole.yaml
  resources/helm/overlays/istio_cni/templates/clusterrolebinding.yaml
  resources/helm/overlays/istio_cni/templates/configmap.yaml
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/overlays/istio_cni/templates/serviceaccount.yaml
  resources/helm/v2.2/istio_cni/templates/clusterrole.yaml
  resources/helm/v2.2/istio_cni/templates/clusterrolebinding.yaml
  resources/helm/v2.2/istio_cni/templates/configmap.yaml
  resources/helm/v2.2/istio_cni/templates/daemonset.yaml
  resources/helm/v2.2/istio_cni/templates/serviceaccount.yaml
Labels: okay to merge, size/L

#920 OSSM-1420 Remove cluster-scoped privileges
  build/patch-charts.sh
  resources/helm/overlays/istio-control/istio-discovery/templates/meshclusterrole.yaml
  resources/helm/v2.2/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.2/istio-control/istio-discovery/templates/meshclusterrole.yaml
Labels: okay to merge, size/M

#921 OSSM-1465 Remove istiod-reader ClusterRole and ClusterRoleBinding
  build/patch-charts.sh
  resources/helm/v2.2/istio-control/istio-discovery/templates/reader-clusterrole.yaml
  resources/helm/v2.2/istio-control/istio-discovery/templates/reader-clusterrolebinding.yaml
Labels: okay to merge, size/M

#924 OSSM-1480 Ensure resource patch failures are treated as errors
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/servicemesh/controlplane/pruner.go
Labels: okay to merge, size/S

#926 OSSM-1491 Ensure Routes are created on OpenShift, but not on Kubernetes
  pkg/controller/common/helm/manifestprocessing.go
  resources/helm/overlays/gateways/istio-ingress/templates/istio-ingressgateway-route.yaml
  resources/helm/overlays/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/ingress.yaml
  resources/helm/v2.2/gateways/istio-ingress/templates/istio-ingressgateway-route.yaml
  resources/helm/v2.2/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/v2.2/istio-telemetry/prometheus/templates/ingress.yaml
Labels: okay to merge, size/M

#927 OSSM-1535 Remove objectSelector from validation webhook
  build/patch-charts.sh
  resources/helm/v2.2/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
Labels: okay to merge, size/S

#929 OSSM-993 Deprecate ServiceMeshExtension
  build/patch-charts.sh
  resources/helm/v2.2/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
Labels: okay to merge, size/S
