Repository maistra/istio-operator, pull requests merged in 2022-10, with the labels that each got.

#1020 OSSM-1847: fixes for gateway injection template
  build/patch-charts.sh
  resources/helm/v2.3/istio-control/istio-discovery/files/gateway-injection-template.yaml
Labels: okay to merge, size/XS

#1021 OSSM-2072 Fix sidecar injection webhook config
  build/patch-charts.sh
  resources/helm/overlays/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/helm/v2.3/istio-control/istio-discovery/values.yaml
Labels: okay to merge, size/S

#1016 OSSM-1188 Remove ServiceMeshExtension support
  build/patch-charts.sh
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/versions/strategy_v2_3.go
  resources/helm/overlays/wasm-extensions/Chart.yaml
  resources/helm/overlays/wasm-extensions/templates/_helpers.tpl
  resources/helm/overlays/wasm-extensions/templates/clusterrole.yaml
  resources/helm/overlays/wasm-extensions/templates/clusterrolebinding.yaml
  resources/helm/overlays/wasm-extensions/templates/deployment.yaml
  resources/helm/overlays/wasm-extensions/templates/destinationrule.yaml
  resources/helm/overlays/wasm-extensions/templates/service.yaml
  resources/helm/overlays/wasm-extensions/templates/serviceaccount.yaml
  resources/helm/overlays/wasm-extensions/values.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/clusterrole.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
  resources/helm/v2.3/wasm-extensions/Chart.yaml
  resources/helm/v2.3/wasm-extensions/templates/_helpers.tpl
  resources/helm/v2.3/wasm-extensions/templates/clusterrole.yaml
  resources/helm/v2.3/wasm-extensions/templates/clusterrolebinding.yaml
  resources/helm/v2.3/wasm-extensions/templates/deployment.yaml
  resources/helm/v2.3/wasm-extensions/templates/destinationrule.yaml
  resources/helm/v2.3/wasm-extensions/templates/service.yaml
  resources/helm/v2.3/wasm-extensions/templates/serviceaccount.yaml
  resources/helm/v2.3/wasm-extensions/values.yaml
Labels: okay to merge, size/XL

#1023 OSSM-2100 Allow creation of cluster-scoped SMCP of any name in any namespace
  pkg/controller/versions/strategy_v2_3.go
Labels: okay to merge, size/S

#1024 OSSM-2074 Allow istiod to watch deployments when analysis is enabled
  build/patch-charts.sh
  resources/helm/v2.3/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, size/S

#1025 Make gen
  resources/helm/v2.0/wasm-extensions/templates/deployment.yaml
Labels: okay to merge, size/XS

#1003 OSSM-1872 Deprecate v1.1 from istio-operator 2.3.0
  DEVEL.md
  Makefile
  build/build.sh
  build/generate-crds.sh
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  build/split-istio-crds.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.3.0/maistraoperator.v2.3.0.clusterserviceversion.yaml
  manifests-servicemesh/2.3.0/servicemeshoperator.v2.3.0.clusterserviceversion.yaml
  pkg/apis/maistra/conversion/cluster_test.go
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/policy_test.go
  pkg/apis/maistra/conversion/prometheus_test.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/conversion/telemetry_test.go
  pkg/bootstrap/cni.go
  pkg/bootstrap/cni_test.go
  pkg/controller/common/cni/cni.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/controlplane/profiles_test.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/version/version.go
  resources/helm/overlays/istio_cni/templates/configmap.yaml
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/v2.3/istio_cni/templates/configmap.yaml
  resources/helm/v2.3/istio_cni/templates/daemonset.yaml
Labels: okay to merge, size/XXL

#1035 OSSM-1321: Add permissions to update pods/finalizers required for appending validation messages
  build/patch-charts.sh
  resources/helm/v2.1/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, size/S

#1033 OSSM-2130 Fix SMMR validation webhook message when asterisk is combined with other namespaces
  pkg/apis/maistra/v1/servicemeshmemberroll_types.go
  pkg/controller/servicemesh/webhooks/validation/memberroll.go
  pkg/controller/servicemesh/webhooks/validation/memberroll_test.go
Labels: okay to merge, size/M

#1034 OSSM-2135 Make Kiali cluster-scoped only when both SMCP and SMMR are cluster-scoped
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/M

#1037 OSSM-1321: Update 2.1 templates
  resources/helm/v2.1/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, size/XS, maistra-2.2

#1039 OSSM-2084: Set namespace_label for kiali dashboards
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.3/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XS, ok-to-test

#1040 Bump `replaces` version
  Makefile
  manifests-maistra/2.3.0/maistraoperator.v2.3.0.clusterserviceversion.yaml
  manifests-servicemesh/2.3.0/servicemeshoperator.v2.3.0.clusterserviceversion.yaml
Labels: okay to merge, size/S

#1041 OSSM-2143 Ensure RoleBindings are copied to member namespace only when necessary
  pkg/controller/servicemesh/member/namespace_reconciler.go
  pkg/controller/servicemesh/member/namespace_reconciler_test.go
Labels: okay to merge, size/M

#1042 Remove duplicated rules from istiod-clusterrole-istio-system
  build/patch-charts.sh
  resources/helm/v2.3/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, size/S

#1043 Remove duplicated rules from istiod-clusterrole-istio-system
  build/patch-charts.sh
  resources/helm/v2.2/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, maistra-2.2

#1047 feat(make): simplifies targets for creating charts and other resources
  Makefile
Labels: okay to merge, size/L

#1048 OSSM-2170 Ensure ServiceMeshMembers are deleted when SMMR is cluster-scoped
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/M

#1046 OSSM-2169 Ensure controller requeues ServiceMeshMember on conflicts
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/member/namespace_reconciler.go
Labels: okay to merge, size/M

#1045 Remove SME leftovers from 2.3 templates
  build/patch-charts.sh
  resources/helm/overlays/global.yaml
  resources/helm/v2.3/global.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.3/istio-control/istio-discovery/values.yaml
  resources/smcp-templates/v2.3/maistra
  resources/smcp-templates/v2.3/servicemesh
  resources/smcp-templates/v2.3/small
Labels: okay to merge, size/M
