Repository maistra/istio-operator, pull requests merged in 2022-04, with the labels that each got.

#907 Revert "OSSM-1107 Add jwksResolverExtraRootCA feature"
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.2.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.2.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/v2/security.go
  pkg/apis/maistra/v2/smcp_new.yaml
Labels: okay to merge, size/L

#908 OSSM-1107 Add jwksResolverCA field
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.1.2/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.1.2/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/v2/security.go
  pkg/apis/maistra/v2/smcp_new.yaml
Labels: okay to merge, size/L

#911 OSSM-1354 Update kiali version to v1.48
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.2/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XS

#917 OSSM-1437: use the new retention setting; do not use deprecated setting.
  resources/helm/overlays/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.2/istio-telemetry/prometheus/templates/deployment.yaml
Labels: okay to merge, size/XS, ok-to-test

#918 OSSM-1332 Use pruneIndividually for CRs
  pkg/controller/servicemesh/controlplane/pruner.go
Labels: okay to merge, size/S
