Repository maistra/istio-operator, pull requests merged in 2022-11, with the labels that each got.

#1050 Update 2.3 charts from maistra/istio
  resources/helm/v2.3/gateways/istio-egress/templates/_affinity.tpl
  resources/helm/v2.3/gateways/istio-ingress/templates/_affinity.tpl
  resources/helm/v2.3/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.3/istio-control/istio-discovery/files/grpc-agent.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/role.yaml
Labels: okay to merge, size/L

#1053 OSSM-2236: Fix lint errors
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
  pkg/apis/maistra/v1/conversion.go
  pkg/bootstrap/cni_test.go
  pkg/controller/common/test/runner.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/controller_test.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/webhooks/validation/memberroll.go
  tools.go
Labels: okay to merge, size/M

#1062 OSSM-2241: remove 2.0 as a control plane option
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.3.0/maistraoperator.v2.3.0.clusterserviceversion.yaml
  manifests-servicemesh/2.3.0/servicemeshoperator.v2.3.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#1052 OSSM-534 Support ingress.hosts for grafana and prometheus
  pkg/controller/common/helm/manifestprocessing.go
  pkg/controller/common/helm/patch.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  resources/helm/overlays/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/overlays/istio-telemetry/grafana/values.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/ingress.yaml
  resources/helm/overlays/istio-telemetry/prometheus/values.yaml
  resources/helm/v2.3/istio-telemetry/grafana/templates/ingress.yaml
  resources/helm/v2.3/istio-telemetry/grafana/values.yaml
  resources/helm/v2.3/istio-telemetry/prometheus/templates/ingress.yaml
  resources/helm/v2.3/istio-telemetry/prometheus/values.yaml
Labels: okay to merge, size/L

#1049 OSSM-2187 Allow usage of spec.proxy.networking.protocol.autoDetect
  pkg/apis/maistra/conversion/proxy.go
  pkg/apis/maistra/conversion/proxy_test.go
  pkg/controller/versions/strategy_v2_2.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/M

#1061 OSSM-2126 Support configurable Grafana storage capacity
  build/patch-charts.sh
  pkg/apis/maistra/v2/grafana.go
  resources/helm/v2.3/istio-telemetry/grafana/templates/pvc.yaml
  resources/helm/v2.3/istio-telemetry/grafana/values.yaml
Labels: size/S
