Repository maistra/istio-operator, pull requests merged in 2022-12, with the labels that each got.

#1060 OSSM-2221 remove ignorenamespace label from control plane ns [maistra-2.3]
  pkg/controller/servicemesh/controlplane/namespace_labels.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge, size/XS

#1063 OSSM-2188 Reconcile SMMR even when SMCP is missing
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/L

#1076 Add push target to Makefile
  Makefile
Labels: okay to merge, size/XS

#1079 Revert "OSSM-2221 remove ignorenamespace label from control plane ns [maistra-2.3]"
  pkg/controller/servicemesh/controlplane/namespace_labels.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
Labels: okay to merge, size/XS

#1067 OSSM-2274 Only prune resources that reference the SMCP for which pruning is being performed
  pkg/controller/servicemesh/controlplane/pruner.go
  pkg/controller/servicemesh/controlplane/pruner_test.go
Labels: okay to merge, size/M
