Repository maistra/istio-operator, pull requests merged in 2022-09, with the labels that each got.

#986 OSSM-1958 Update Kiali CR spec.version so it can run the latest builds of Kiali
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.3/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/S, ok-to-test

#982 Fix generate-manifests.sh so it recognizes yq-python correctly
  build/generate-manifests.sh
Labels: okay to merge, size/XS

#966 OSSM-1321 Fix distribution report ConfigMap creation
  build/patch-charts.sh
  resources/helm/v2.2/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, cherrypick/maistra-2.3

#972 OSSM-1928 Remove erroneous maistra-version label from chart overlays [maistra-2.2]
  resources/helm/overlays/istio-init/files/servicemeshpolicies.authentication.maistra.io.crd.yaml
  resources/helm/overlays/istio-init/files/servicemeshrbacconfigs.rbac.maistra.io.crd.yaml
  resources/helm/v2.2/istio-init/files/servicemeshpolicies.authentication.maistra.io.crd.yaml
  resources/helm/v2.2/istio-init/files/servicemeshrbacconfigs.rbac.maistra.io.crd.yaml
Labels: okay to merge, size/XS

#974 OSSM-1928 Remove erroneous maistra-version label from chart overlays [maistra-2.0]
  resources/helm/overlays/istio-init/files/servicemeshpolicies.authentication.maistra.io.crd.yaml
  resources/helm/overlays/istio-init/files/servicemeshrbacconfigs.rbac.maistra.io.crd.yaml
  resources/helm/v2.0/istio-init/files/servicemeshpolicies.authentication.maistra.io.crd.yaml
  resources/helm/v2.0/istio-init/files/servicemeshrbacconfigs.rbac.maistra.io.crd.yaml
Labels: okay to merge, size/XS

#987 OSSM-1928 Remove erroneous maistra-version label from chart overlays [maistra-2.3]
  resources/helm/overlays/istio-init/files/servicemeshpolicies.authentication.maistra.io.crd.yaml
  resources/helm/overlays/istio-init/files/servicemeshrbacconfigs.rbac.maistra.io.crd.yaml
  resources/helm/v2.3/istio-init/files/servicemeshpolicies.authentication.maistra.io.crd.yaml
  resources/helm/v2.3/istio-init/files/servicemeshrbacconfigs.rbac.maistra.io.crd.yaml
Labels: okay to merge, size/XS

#978 OSSM-1951 Fix use of deprecated policy/v1beta1 PodDisruptionBudget [maistra-2.0]
  build/patch-charts.sh
  resources/helm/v2.0/gateways/istio-egress/templates/poddisruptionbudget.yaml
  resources/helm/v2.0/gateways/istio-ingress/templates/poddisruptionbudget.yaml
  resources/helm/v2.0/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
Labels: okay to merge

#977 OSSM-1951 Fix use of deprecated policy/v1beta1 PodDisruptionBudget [maistra-2.1]
  build/patch-charts.sh
  resources/helm/v2.1/gateways/istio-egress/templates/poddisruptionbudget.yaml
  resources/helm/v2.1/gateways/istio-ingress/templates/poddisruptionbudget.yaml
  resources/helm/v2.1/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
Labels: okay to merge, size/S

#976 OSSM-1951 Fix use of deprecated policy/v1beta1 PodDisruptionBudget [maistra-2.2]
  build/patch-charts.sh
  resources/helm/v2.2/gateways/istio-egress/templates/poddisruptionbudget.yaml
  resources/helm/v2.2/gateways/istio-ingress/templates/poddisruptionbudget.yaml
  resources/helm/v2.2/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
Labels: okay to merge, size/S

#975 OSSM-1917 Add yamllint
  Makefile
  build/.yamllint.yml
Labels: okay to merge, size/S

#989 OSSM-1321 Fix distribution report ConfigMap creation
  build/patch-charts.sh
  resources/helm/v2.3/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, size/M

#997 OSSM-1969 Remove duplicate maistra-control-plane label [maistra-2.3]
  resources/helm/overlays/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/overlays/rls/templates/deployment.yaml
  resources/helm/overlays/wasm-extensions/templates/deployment.yaml
  resources/helm/v2.3/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/v2.3/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.3/rls/templates/deployment.yaml
  resources/helm/v2.3/wasm-extensions/templates/deployment.yaml
Labels: okay to merge, size/XS

#995 OSSM-1969 Remove duplicate maistra-control-plane label [maistra-2.1]
  resources/helm/overlays/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/overlays/rls/templates/deployment.yaml
  resources/helm/overlays/wasm-extensions/templates/deployment.yaml
  resources/helm/v2.1/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/v2.1/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.1/rls/templates/deployment.yaml
  resources/helm/v2.1/wasm-extensions/templates/deployment.yaml
Labels: okay to merge, size/XS

#994 OSSM-1969 Remove duplicate maistra-control-plane label [maistra-2.0]
  resources/helm/overlays/wasm-extensions/templates/deployment.yaml
  resources/helm/v2.0/wasm-extensions/templates/deployment.yaml
Labels: okay to merge, size/XS

#1000 Run make gen
  resources/helm/v2.0/wasm-extensions/templates/deployment.yaml
  resources/helm/v2.1/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/v2.1/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.1/rls/templates/deployment.yaml
  resources/helm/v2.1/wasm-extensions/templates/deployment.yaml
  resources/helm/v2.2/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/v2.2/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.2/rls/templates/deployment.yaml
  resources/helm/v2.2/wasm-extensions/templates/deployment.yaml
  resources/helm/v2.3/gateways/istio-egress/values.yaml
  resources/helm/v2.3/gateways/istio-ingress/values.yaml
Labels: okay to merge, size/S

#1004 Fix common.GetOperatorNamespace() to work in a OCP env
  pkg/controller/common/util.go
Labels: okay to merge, size/S, cherrypick/maistra-2.1, cherrypick/maistra-2.2

#1005 OSSM-1330 add support for using cert-manager
  Makefile
  build/build.sh
  build/docker_build.sh
  build/patch-charts.sh
  deploy/examples/cert-manager/README.md
  deploy/examples/cert-manager/istio-csr-helm-values.yaml
  deploy/examples/cert-manager/selfsigned-ca.yaml
  deploy/examples/cert-manager/smcp.yaml
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.3.0/maistraoperator.v2.3.0.clusterserviceversion.yaml
  manifests-maistra/2.3.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.2.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.3.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.3.0/servicemeshoperator.v2.3.0.clusterserviceversion.yaml
  pkg/apis/maistra/conversion/common.go
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/v2/security.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  resources/helm/v2.3/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.3/istio-control/istio-discovery/values.yaml
Labels: okay to merge, size/XL

#1014 OSSM-2053 Don't remove configured (but out-of-date) members from SMMR.status.configuredMembers [maistra-2.2]
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: size/M

#1013 OSSM-2053 Don't remove configured (but out-of-date) members from SMMR.status.configuredMembers
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
Labels: okay to merge, size/M

#1018 make gen
  resources/helm/v2.3/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, size/XS

#1012 OSSM-1975 Use actual Kubernetes version when rendering charts
  cmd/manager/main.go
  pkg/bootstrap/cni.go
  pkg/bootstrap/cni_test.go
  pkg/controller/common/discovery.go
  pkg/controller/common/helm/helm.go
  pkg/controller/common/test/controller-test-utils.go
  pkg/controller/common/test/runner.go
  pkg/controller/common/util.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/controller.go
  pkg/controller/servicemesh/controlplane/controller_test.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  pkg/controller/versions/rendering_strategy_v1_x.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
  pkg/controller/versions/strategy_v2_2.go
  pkg/controller/versions/strategy_v2_3.go
Labels: okay to merge, size/L

#1015 OSSM-1918 Add Helm linter
  Makefile
  build/patch-charts.sh
  resources/helm/overlays/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/helm/overlays/istio-telemetry/grafana/values.yaml
  resources/helm/overlays/istio-telemetry/kiali/values.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/overlays/istio-telemetry/prometheus/values.yaml
  resources/helm/overlays/istio-telemetry/telemetry-common/values.yaml
  resources/helm/overlays/istio-telemetry/tracing/values.yaml
  resources/helm/overlays/istio_cni/values.yaml
  resources/helm/overlays/rls/values.yaml
  resources/helm/overlays/wasm-extensions/values.yaml
  resources/helm/v2.3/gateways/istio-egress/values.yaml
  resources/helm/v2.3/gateways/istio-ingress/values.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/helm/v2.3/istio-control/istio-discovery/values.yaml
  resources/helm/v2.3/istio-telemetry/grafana/values.yaml
  resources/helm/v2.3/istio-telemetry/kiali/values.yaml
  resources/helm/v2.3/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.3/istio-telemetry/prometheus/values.yaml
  resources/helm/v2.3/istio-telemetry/telemetry-common/values.yaml
  resources/helm/v2.3/istio-telemetry/tracing/values.yaml
  resources/helm/v2.3/istio_cni/values.yaml
  resources/helm/v2.3/mesh-config/values.yaml
  resources/helm/v2.3/rls/values.yaml
  resources/helm/v2.3/wasm-extensions/values.yaml
Labels: okay to merge, size/L

#1006 OSSM-1320 Add option to run OSSM in cluster-wide mode
  build/patch-charts.sh
  pkg/apis/maistra/v1/servicemeshmemberroll_types.go
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/controller/common/util.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane.go
  pkg/controller/servicemesh/webhooks/validation/member.go
  pkg/controller/servicemesh/webhooks/validation/member_test.go
  pkg/controller/servicemesh/webhooks/validation/memberroll.go
  pkg/controller/servicemesh/webhooks/validation/memberroll_test.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
  pkg/controller/versions/strategy_v2_2.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/versions.go
  resources/helm/v2.3/istio-control/istio-discovery/templates/clusterrole.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/clusterrolebinding.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/L
