Repository maistra/istio-operator, pull requests merged in 2023-11, with the labels that each got.

#1424 OSSM-5303 Show profiles in a drop-down list in the OpenShift console
  Makefile.core.mk
  api/v1alpha1/istio_types.go
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  hack/update-profiles-list.sh
Labels: okay to merge, size/L

#1422 OSSM-1698: Don't install istio-cni on nodes with label `maistra.io/exclude-cni: 'true'`
  resources/helm/overlays/istio_cni/templates/daemonset-v2.5.yaml
  resources/helm/v2.5/istio_cni/templates/daemonset-v2.5.yaml
Labels: okay to merge, size/S

#1419 OSSM-5309 Updating Readme file with addons install
  bundle/README.md
Labels: okay to merge, size/L

#1410 OSSM-5293 Add rawValues field
  api/v1alpha1/istio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  controllers/istio_controller.go
Labels: okay to merge, size/M

#1434 Introduce HelmValues in place of map[string]interface{}
  api/v1alpha1/istio_types.go
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  pkg/helm/charts.go
  pkg/helm/values.go
  pkg/helm/values_test.go
Labels: okay to merge, size/L

#1435 OSSM-4643: Fix patches for gateway-controller mode
  build/patch-charts.sh
  resources/helm/v2.5/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.5/gateways/istio-egress/values.yaml
  resources/helm/v2.5/gateways/istio-ingress/templates/deployment.yaml
  resources/helm/v2.5/gateways/istio-ingress/values.yaml
  resources/helm/v2.5/istio-control/istio-discovery/files/gateway-injection-template.yaml
  resources/helm/v2.5/istio-control/istio-discovery/files/grpc-agent.yaml
  resources/helm/v2.5/istio-control/istio-discovery/files/injection-template.yaml
  resources/helm/v2.5/istio-control/istio-discovery/files/kube-gateway.yaml
  resources/helm/v2.5/istio-control/istio-discovery/files/waypoint.yaml
  resources/helm/v2.5/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.5/istio-control/istio-discovery/values.yaml
Labels: okay to merge, size/S

#1437 Improve values aggregation code
  controllers/istio_controller.go
  controllers/istio_controller_test.go
Labels: okay to merge, size/L

#1442 Make istio_controller_test easier to read
  controllers/istio_controller_test.go
Labels: okay to merge, size/M

#1441 OSSM-5351 Only install istio-cni when it's enabled in values.istio_cni.enabled
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  pkg/helm/charts.go
  pkg/helm/values.go
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/L

#1443 Added instructions for deleting service mesh 3.0
  bundle/README.md
Labels: okay to merge, size/S

#1303 OSSM-4050 Type-safe helm values
  Makefile.core.mk
  bundle/manifests/operator.istio.io_istios.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/samples/istio-sample-kubernetes.yaml
  hack/patch-istio-crd.sh
Labels: okay to merge, size/XXL

#1448 OSSM-5298 Remove labels from istio-sample
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/samples/istio-sample-kubernetes.yaml
  config/samples/istio-sample-openshift.yaml
  config/samples/kustomization.yaml
Labels: okay to merge, size/S

#1450 OSSM-5359 Move "latest" version to the bottom of the list
  Makefile.core.mk
  api/v1alpha1/istio_types.go
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  hack/patch-istio-crd.sh
  hack/update-istio.sh
  hack/update-version-list.sh
  tests/integration/common-operator-integ-suite.sh
  versions.yaml
Labels: okay to merge, size/L

#1451 OSSM-5362 Install istio-cni in same namespace as the control plane
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  pkg/helm/charts.go
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/M

#1456 OSSM-5386 Add meshConfig to values schema
  bundle/manifests/operator.istio.io_istios.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  hack/patch-istio-crd.sh
Labels: okay to merge, size/M

#1454 OSSM-5353: Sail Docs Feedback
  bundle/README.md
Labels: okay to merge, size/S

#1457 OSSM-5376 Use version v1.20.0 in the OpenShift example
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/samples/istio-sample-kubernetes.yaml
  config/samples/istio-sample-openshift.yaml
Labels: okay to merge, size/XS

#1460 Fix `make gen` failure when CSV file is not yet committed
  build/generate-manifests.sh
Labels: okay to merge, size/XS, cherrypick/maistra-2.3, cherrypick/maistra-2.4, cherrypick/maistra-2.5

#1466 OSSM-5394 Fix values as array type
  bundle/manifests/operator.istio.io_istios.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  hack/patch-istio-crd.sh
Labels: okay to merge, size/L

#1472 OSSM-5383: Minor edits to Sail readme file
  bundle/README.md
Labels: okay to merge, size/S

#1471 OSSM-5395 Convert protobuf Struct and Value
  bundle/manifests/operator.istio.io_istios.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  hack/patch-istio-crd.sh
Labels: okay to merge, size/L

#1480 OSSM-5383: in deployment section changed message in Status column.
  bundle/README.md
Labels: okay to merge, size/XS

#1481 OSSM-5397 avoid modify all kind cluster when running kind integration test
  tests/integration/integ-suite-kind.sh
Labels: okay to merge, size/S

#1482 OSSM-5297: Added instructions for Installing Istioctl.
  bundle/README.md
Labels: okay to merge, size/M

#1484 OSSM-4819 Use Helm's PostRenderer to add owner references to resources
  go.mod
  go.sum
  pkg/helm/charts.go
  pkg/helm/ownerreferences.go
  pkg/helm/ownerreferences_test.go
Labels: okay to merge, size/L

#1485 Bump gateway api to 1.0.0
  bundle/README.md
Labels: okay to merge, size/XS

#1487 Removing toolchain directive as it's breaking downstream builds
  go.mod
Labels: okay to merge, size/XS

#1478 OSSM-1397 Add back `maistra.io/member-of` label when it's removed from the namespace
  pkg/controller/servicemesh/member/controller.go
Labels: okay to merge, size/M, cherrypick/maistra-2.4

#1492 Ensure failed tests show correct line
  controllers/istio_controller_test.go
Labels: okay to merge, size/XS

#1493 Reorg customize config section, add example config and version field …
  bundle/README.md
Labels: okay to merge, size/M

#1490 OSSM-5423 Fix istiod readiness check when revision is set
  controllers/istio_controller.go
  controllers/istio_controller_test.go
Labels: okay to merge, size/L

#1498 update overlays to kiali 1.73
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.5/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XS, needs-ok-to-test, ok-to-test
