Repository maistra/istio-operator, pull requests merged in 2023-07, with the labels that each got.

#1233 Fix go.mod reference to luksa/helm
  go.mod
  go.sum
Labels: okay to merge, size/S

#1234 OSSM-4189 Increase resource limits for istio-operator pod
  bundle/manifests/maistraoperator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: okay to merge, size/XS

#1236 OSSM-4397 Ensure istio-cni can use the privileged SCC
  bundle/manifests/maistraoperator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/istiohelminstall_controller.go
  hack/download-charts.sh
  pkg/istio/maistra_30_strategy.go
  resources/charts/v3.0/istio-cni/templates/clusterrole.yaml
Labels: okay to merge, size/M

#1243 OSSM-4470 - Efficiency Improvements For Openshift CI PROW Job Integra…
  tests/integration/build-operator.sh
  tests/integration/check-operator.sh
  tests/integration/control-plane-test.sh
  tests/integration/operator-integ-suite-ocp.sh
Labels: okay to merge, size/M

#1253 OSSM-4254: Rename to Sail Operator
  Makefile
  PROJECT
  bundle.Dockerfile
  bundle/manifests/istio-operator-metrics-service_v1_service.yaml
  bundle/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/istiohelminstall_editor_role.yaml
  config/rbac/istiohelminstall_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/kustomization.yaml
  config/samples/maistra.io_v1_istiohelminstall.yaml
  hack/operatorhub/publish-bundle.sh
Labels: okay to merge, size/L

#1254 OSSM-3360: Sail Operator Read Me
  bundle/README.md
Labels: okay to merge, size/M, ok-to-test

#1257 Fix & run make gen
  build/patch-charts.sh
  resources/helm/v2.4/gateway/templates/poddisruptionbudget.yaml
  resources/helm/v2.4/gateway/values.schema.json
  resources/helm/v2.4/gateway/values.yaml
Labels: okay to merge, size/M

#1259 Revert "Bump golang.org/x/crypto from 0.0.0-20200709230013-948cd5f35899 to 0.1.0 (#1124)"
  go.mod
  go.sum
Labels: okay to merge, size/M

#1258 Add Istio configuration section to README.md
  bundle/README.md
Labels: okay to merge, ok-to-test

#1260 Add a link to the README in the operator description
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
Labels: okay to merge, size/S

#1255 OSSM-4562 - Add CNI Test
  tests/integration/check-operator.sh
  tests/integration/control-plane-test.sh
  tests/integration/operator-integ-suite-ocp.sh
Labels: okay to merge, size/L
