Repository maistra/istio-operator, pull requests merged in 2023-05, with the labels that each got.

#1183 Run make gen
  resources/helm/v2.2/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.2/gateways/istio-ingress/templates/deployment.yaml
Labels: okay to merge, size/S

#1188 OSSM-3934: Update oauth-proxy to v4.9 in the servicemesh template
  resources/smcp-templates/v2.4/servicemesh
Labels: okay to merge, size/XS

#1189 Reenable IOR in default setting
  build/patch-charts.sh
  resources/helm/v2.4/istio-control/istio-discovery/templates/deployment.yaml
  resources/smcp-templates/v2.4/base
Labels: okay to merge, size/S

#1176 OSSM-3802 Implement SMCP.spec.meshConfig.discoverySelectors
  build/.golangci.yml
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.4.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.4.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
  pkg/apis/maistra/conversion/discovery_selectors.go
  pkg/apis/maistra/conversion/discovery_selectors_test.go
  pkg/apis/maistra/v2/meshconfig.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
  pkg/controller/versions/strategy_v2_2.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/strategy_v2_4.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/L

#1192 OSSM-3937 Remove the 2.1 SMCP option from the 2.4 SM drop-down in OS UI
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.4.0/maistraoperator.v2.4.0.clusterserviceversion.yaml
  manifests-servicemesh/2.4.0/servicemeshoperator.v2.4.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#1193 OSSM-2285: Remove support for v2.0
  Makefile
  build/build.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.4.0/maistraoperator.v2.4.0.clusterserviceversion.yaml
  manifests-servicemesh/2.4.0/servicemeshoperator.v2.4.0.clusterserviceversion.yaml
  pkg/apis/maistra/conversion/cluster_test.go
  pkg/apis/maistra/conversion/discovery_selectors_test.go
  pkg/apis/maistra/conversion/extension_providers_test.go
  pkg/apis/maistra/conversion/gateways_test.go
  pkg/apis/maistra/conversion/grafana_test.go
  pkg/apis/maistra/conversion/jaeger_test.go
  pkg/apis/maistra/conversion/kiali_test.go
  pkg/apis/maistra/conversion/logging_test.go
  pkg/apis/maistra/conversion/policy_test.go
  pkg/apis/maistra/conversion/prometheus_test.go
  pkg/apis/maistra/conversion/proxy_test.go
  pkg/apis/maistra/conversion/runtime_test.go
  pkg/apis/maistra/conversion/security_test.go
  pkg/apis/maistra/conversion/techpreviews_test.go
  pkg/apis/maistra/conversion/telemetry_test.go
  pkg/apis/maistra/conversion/threescale_test.go
  pkg/bootstrap/cni.go
  pkg/bootstrap/cni_test.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/versions/versions.go
  pkg/version/version.go
Labels: okay to merge, size/XL

#1195 OSSM-2285: Remove v2.0 leftovers
  pkg/controller/common/cni/cni.go
Labels: okay to merge, size/XS

#1194 OSSM-3986: Reconcile role bindings for Prometheus
  pkg/controller/servicemesh/member/namespace_reconciler.go
Labels: okay to merge, size/S

#1196 OSSM-4014 Add Make target that downloads charts
  Makefile
  hack/download-charts.sh
  resources/charts/v3.0/UPDATING-CHARTS.md
  resources/charts/v3.0/istio-cni/templates/daemonset.yaml
  resources/charts/v3.0/istio-cni/values.yaml
  resources/charts/v3.0/istio-control/istio-discovery/files/grpc-simple.yaml
  resources/charts/v3.0/istio-control/istio-discovery/files/injection-template.yaml
  resources/charts/v3.0/istio-control/istio-discovery/files/kube-gateway.yaml
  resources/charts/v3.0/istiod-remote/files/injection-template.yaml
Labels: okay to merge, size/L

#1089 OSSM-1712 Use vanilla prometheus
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.4.0/maistraoperator.v2.4.0.clusterserviceversion.yaml
  manifests-servicemesh/2.4.0/servicemeshoperator.v2.4.0.clusterserviceversion.yaml
  pkg/controller/common/config.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/memberroll/prometheus.go
  pkg/controller/versions/strategy_v2_4.go
  resources/helm/overlays/istio-telemetry/prometheus/templates/_sd_namespace.tpl
  resources/helm/overlays/istio-telemetry/prometheus/templates/configmap.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/overlays/istio-telemetry/prometheus/values.yaml
  resources/helm/v2.4/istio-telemetry/prometheus/templates/_sd_namespace.tpl
  resources/helm/v2.4/istio-telemetry/prometheus/templates/configmap.yaml
  resources/helm/v2.4/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.4/istio-telemetry/prometheus/values.yaml
Labels: okay to merge, size/XL
