Repository maistra/istio-operator, pull requests merged in 2023-10, with the labels that each got.

#1329 Add `deploy-example-kubernetes` target to Makefile
  Makefile
  README.md
  config/samples/istio-sample-kubernetes.yaml
  config/samples/istio-sample-openshift.yaml
  config/samples/kustomization.yaml
  tests/integration/operator-integ-suite-ocp.sh
Labels: okay to merge, size/M

#1331 OSSM-4882 Add description to IstioSpec.version and IstioSpec.values
  api/v1alpha1/istio_types.go
  bundle/manifests/operator.istio.io_istios.yaml
  config/crd/bases/operator.istio.io_istios.yaml
Labels: okay to merge, size/S

#1337 OSSM-4897 Disable olm-crds-have-resources-test scorecard test
  bundle/tests/scorecard/config.yaml
  config/scorecard/patches/olm.config.yaml
Labels: okay to merge, size/S

#1336 OSSM-4896 Add OLM spec descriptors for the Istio resource
  api/v1alpha1/istio_types.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
Labels: okay to merge, size/M

#1340 OSSM-4942 Hide istio CRDs in the OpenShift Console
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  hack/download-charts.sh
Labels: okay to merge, size/S

#1341 OSSM-4898 Add `make undeploy-olm`
  Makefile
Labels: okay to merge, size/XS

#1334 OSSM-4885 Enable the possibility to run integration test in kind
  Makefile
  config/samples/istio-sample-kubernetes.yaml
  tests/integration/README.md
  tests/integration/common-operator-integ-suite.sh
  tests/integration/config/default.yaml
  tests/integration/integ-suite-kind.sh
  tests/integration/integ-suite-ocp.sh
Labels: okay to merge, size/L

#1343 Invoke make in silent mode
  Makefile
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/S

#1344 Ensure OLM deploy/undeploys operator in correct namespace
  Makefile
Labels: okay to merge, size/XS

#1345 OSSM-4885 Integration operator test change default configuration for kind cluster
  tests/integration/config/default.yaml
Labels: okay to merge, size/M

#1347 OSSM-4957 Move istio CNI plugin binaries to /var/lib/cni/bin
  pkg/bootstrap/cni.go
Labels: okay to merge, size/XS, cherrypick/maistra-2.4

#1346 Fix usage of oc in kind tests
  tests/integration/common-operator-integ-suite.sh
  tests/integration/integ-suite-kind.sh
  tests/integration/integ-suite-ocp.sh
Labels: okay to merge, size/XS

#1354 Add CODEOWNERS
  CODEOWNERS
Labels: okay to merge, size/XS

#1357 Simplify OpenShift sample
  api/v1alpha1/istio_types.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  config/samples/istio-sample-openshift.yaml
Labels: okay to merge, size/M

#1359 Fix update istio
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  resources/v3.0/charts/gateway/templates/deployment.yaml
  resources/v3.0/charts/gateway/values.schema.json
  resources/v3.0/charts/gateway/values.yaml
  resources/v3.0/charts/istio-control/istio-discovery/files/waypoint.yaml
  resources/v3.0/charts/istio-control/istio-discovery/values.yaml
  resources/v3.0/charts/istiod-remote/values.yaml
Labels: okay to merge, size/S, tide/merge-method-rebase

#1370 Fix the nigthly target
  Makefile.core.mk
  hack/operatorhub/publish-bundle.sh
Labels: okay to merge, size/S

#1372 Fix lint-watches.sh
  hack/lint-watches.sh
Labels: okay to merge, size/S

#1374 Remove ubi references
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
Labels: okay to merge, size/S

#1378 Prevent `make undeploy` from hanging forever
  Makefile.core.mk
Labels: okay to merge, size/XS

#1376 OSSM-5038: Enable kind internal registry
  tests/integration/integ-suite-kind.sh
Labels: okay to merge, size/M

#1384 OSSM-5041 Always apply default profile in addition to the selected profile
  controllers/istio_controller.go
  controllers/istio_controller_test.go
Labels: okay to merge, size/M

#1392 OSSM-5275 Update `createdAt` timestamp only when there are actual changes in the CSV
  Makefile.core.mk
Labels: okay to merge, size/XS

#1393 Update `createdAt` timestamp only when there are actual changes in the CSV
  build/generate-manifests.sh
Labels: okay to merge, cherrypick/maistra-2.2, cherrypick/maistra-2.3, cherrypick/maistra-2.4

#1400 OSSM-5296 Ensure profiles contain meshConfig section
  hack/download-charts.sh
  resources/latest/profiles/ambient.yaml
  resources/latest/profiles/default.yaml
  resources/latest/profiles/demo.yaml
  resources/latest/profiles/preview.yaml
  resources/v1.18.5/profiles/ambient.yaml
  resources/v1.18.5/profiles/default.yaml
  resources/v1.18.5/profiles/demo.yaml
  resources/v1.18.5/profiles/preview.yaml
  resources/v1.19.1/profiles/ambient.yaml
  resources/v1.19.1/profiles/default.yaml
  resources/v1.19.1/profiles/demo.yaml
  resources/v1.19.1/profiles/preview.yaml
  resources/v1.19.3/profiles/ambient.yaml
  resources/v1.19.3/profiles/default.yaml
  resources/v1.19.3/profiles/demo.yaml
  resources/v1.19.3/profiles/preview.yaml
Labels: okay to merge, size/L

#1399 Ensure older Istio versions can run on OpenShift
  hack/download-charts.sh
  resources/v1.18.5/charts/istiod/templates/deployment.yaml
  resources/v1.19.1/charts/istiod/templates/deployment.yaml
  resources/v1.19.3/charts/istiod/templates/deployment.yaml
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/S

#1405 OSSM-5024 Add `make format`
  Makefile.core.mk
Labels: okay to merge, size/XS

#1406 Update deps
  common/.commonfiles.sha
  common/config/.golangci.yml
  go.mod
  go.sum
  versions.yaml
Labels: okay to merge, size/S

#1407 Remove unused .golangci.yml and .yamllint.yml
  .golangci.yml
  .yamllint.yml
Labels: okay to merge, size/L

#1408 Revert "Fix lint due to the update of golangci-lint 1.55.0"
  controllers/istio_controller_test.go
  controllers/suite_test.go
  pkg/kube/finalizers_test.go
Labels: okay to merge, size/L

#1356 OSSM-4774 Use internal registry of OCP
  tests/integration/common-operator-integ-suite.sh
  tests/integration/config/role-bindings.yaml
Labels: okay to merge, size/L

#1404 OSSM-5301 Support multiple default profiles
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/suite_test.go
  main.go
Labels: okay to merge, size/L

#1409 OSSM-5302 Use profiles 'default' and 'openshift' as the default on OpenShift
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/manifests/default_overlay_profile_patch.yaml
  config/manifests/kustomization.yaml
  config/samples/istio-sample-openshift.yaml
Labels: okay to merge, size/S

#1416 Wait until artifacts are available on GCS
  hack/update-istio.sh
Labels: okay to merge, size/S

#1411 Add gateway config instructions and sample config
  bundle/README.md
  config/samples/ingress-gateway.yaml
Labels: okay to merge, size/L
