Repository maistra/istio-operator, pull requests merged in 2023-02, with the labels that each got.

#1099 OSSM-3249 Ensure ClusterScoped controlPlaneMode works in SMCP profiles
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/strategy_v2_4.go
Labels: okay to merge, size/M

#1106 OSSM-3341: Prometheus jobs for dual-stack
  resources/helm/overlays/istio-telemetry/prometheus/templates/configmap.yaml
  resources/helm/v2.4/istio-telemetry/prometheus/templates/configmap.yaml
Labels: okay to merge, size/M, jira/valid-reference

#1110 OSSM-3372: Document cert-manager configuration in the default profile
  deploy/examples/cert-manager/smcp-2.3.1.yaml
  deploy/examples/cert-manager/smcp.yaml
Labels: okay to merge, size/S, jira/valid-reference

#1112 OSSM-1330: Use well known paths for TLS certificates
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
Labels: okay to merge, size/L, jira/valid-reference

#1098 OSSM-924 Support Gateway Controller Mode
  build/patch-charts.sh
  go.mod
  go.sum
  resources/helm/overlays/global.yaml
  resources/helm/overlays/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/helm/overlays/istio_cni/templates/clusterrole.yaml
  resources/helm/overlays/istio_cni/templates/clusterrolebinding.yaml
  resources/helm/overlays/istio_cni/templates/configmap-v2.3.yaml
  resources/helm/overlays/istio_cni/templates/configmap-v2.4.yaml
  resources/helm/overlays/istio_cni/templates/configmap.yaml
  resources/helm/overlays/istio_cni/templates/daemonset-v2.3.yaml
  resources/helm/overlays/istio_cni/templates/daemonset-v2.4.yaml
  resources/helm/overlays/istio_cni/templates/daemonset.yaml
  resources/helm/overlays/istio_cni/templates/serviceaccount.yaml
  resources/helm/overlays/istio_cni/values.yaml
  resources/helm/v2.3/global.yaml
  resources/helm/v2.4/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.4/gateways/istio-egress/values.yaml
  resources/helm/v2.4/gateways/istio-ingress/templates/deployment.yaml
  resources/helm/v2.4/gateways/istio-ingress/values.yaml
  resources/helm/v2.4/global.yaml
  resources/helm/v2.4/istio-control/istio-discovery/files/gateway-injection-template.yaml
  resources/helm/v2.4/istio-control/istio-discovery/files/injection-template.yaml
  resources/helm/v2.4/istio-control/istio-discovery/templates/configmap.yaml
  resources/helm/v2.4/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.4/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/helm/v2.4/istio-control/istio-discovery/values.yaml
  resources/helm/v2.4/istio_cni/templates/clusterrole.yaml
  resources/helm/v2.4/istio_cni/templates/clusterrolebinding.yaml
  resources/helm/v2.4/istio_cni/templates/configmap-v2.3.yaml
  resources/helm/v2.4/istio_cni/templates/configmap-v2.4.yaml
  resources/helm/v2.4/istio_cni/templates/configmap.yaml
  resources/helm/v2.4/istio_cni/templates/daemonset-v2.3.yaml
  resources/helm/v2.4/istio_cni/templates/daemonset-v2.4.yaml
  resources/helm/v2.4/istio_cni/templates/daemonset.yaml
  resources/helm/v2.4/istio_cni/templates/serviceaccount.yaml
  resources/helm/v2.4/istio_cni/values.yaml
  resources/smcp-templates/v2.4/gateway-controller
Labels: okay to merge, size/L

#1117 OSSM-3398 Replace caRootCertConfigMap with caCertConfigMapName
  build/patch-charts.sh
  resources/helm/overlays/global.yaml
  resources/helm/overlays/istio-telemetry/prometheus/templates/deployment.yaml
  resources/helm/v2.3/global.yaml
  resources/helm/v2.4/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.4/gateways/istio-egress/values.yaml
  resources/helm/v2.4/gateways/istio-ingress/templates/deployment.yaml
  resources/helm/v2.4/gateways/istio-ingress/values.yaml
  resources/helm/v2.4/global.yaml
  resources/helm/v2.4/istio-control/istio-discovery/files/gateway-injection-template.yaml
  resources/helm/v2.4/istio-control/istio-discovery/files/gen-istio.yaml
  resources/helm/v2.4/istio-control/istio-discovery/files/injection-template.yaml
  resources/helm/v2.4/istio-control/istio-discovery/templates/deployment.yaml
  resources/helm/v2.4/istio-control/istio-discovery/values.yaml
  resources/helm/v2.4/istio-telemetry/prometheus/templates/deployment.yaml
  resources/smcp-templates/v2.4/gateway-controller
Labels: okay to merge, size/M
