Repository maistra/istio-operator, pull requests merged in 2023-12, with the labels that each got.

#1521 OSSM-5425 Allow two control planes to be deployed concurrently
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/istiorevision/suite_test.go
  main.go
  pkg/helm/charts.go
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/L

#1525 Mark Istio(Revision).spec.version as required
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istiorevisions.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  pkg/kube/finalizers_test.go
Labels: okay to merge, size/M

#1526 Clean up kustomization.yaml files
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manifests/kustomization.yaml
  config/openshift/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/rbac/kustomization.yaml
  config/scorecard/kustomization.yaml
Labels: okay to merge, size/M

#1523 Fix update sdk
  bundle/tests/scorecard/config.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  tools/update_deps.sh
Labels: okay to merge, size/S

#1530 Update IstioRevision annotations as well
  hack/update-version-list.sh
Labels: okay to merge, size/XS

#1519 OSSM-3368: Allow changing SMCP mode to cluster-wide
  pkg/controller/versions/strategy_v2_5.go
Labels: okay to merge, size/S

#1536 Various fixes
  PROJECT
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istiorevisions.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
Labels: okay to merge, size/L

#1534 OSSM-5414 Make Istio and IstioRevision cluster-scoped
  PROJECT
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istiorevisions.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  config/samples/istio-sample-kubernetes.yaml
  config/samples/istio-sample-openshift.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  pkg/helm/charts.go
  pkg/helm/ownerreferences.go
Labels: okay to merge, size/L

#1539 Update deps
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  go.mod
  go.sum
  pkg/helm/restclientgetter.go
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  resources/latest/profiles/default.yaml
  versions.yaml
Labels: okay to merge, size/L

#1544 OSSM-5410 Add update strategy to Istio resource
  api/v1alpha1/istio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  config/samples/istio-sample-kubernetes.yaml
  config/samples/istio-sample-openshift.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
Labels: okay to merge, size/L

#1545 OSSM-5412 Implement semi-automatic update strategy
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istiorevisions.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  config/samples/istio-sample-kubernetes.yaml
  config/samples/istio-sample-openshift.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/XL

#1546 Fix nightly build
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
Labels: okay to merge, size/M

#1547 OSSM-5569 Add revision counts to Istio.status
  api/v1alpha1/istio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istios.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
Labels: okay to merge, size/L

#1514 OSSM-5552 Replacing CSV version
  Makefile
  manifests-maistra/2.5.0/maistraoperator.v2.5.0.clusterserviceversion.yaml
  manifests-servicemesh/2.5.0/servicemeshoperator.v2.5.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#1549 OSSM-5581 Improve & clean up logging
  controllers/istio/istio_controller.go
  controllers/istiorevision/istiorevision_controller.go
  main.go
  pkg/common/context.go
  pkg/helm/charts.go
  pkg/kube/finalizers.go
  pkg/test/environment.go
Labels: okay to merge, size/L

#1551 OSSM-5582 Add copyright banners and enable lint-copyright-banner
  Makefile.core.mk
  api/v1alpha1/common.go
  api/v1alpha1/istiorevision_types_test.go
  controllers/istio/istio_controller_test.go
  controllers/istiorevision/istiorevision_controller_test.go
  hack/copy-crds.sh
  hack/download-charts.sh
  hack/lint-watches.sh
  hack/operatorhub/publish-bundle.sh
  hack/patch-istio-crd.sh
  hack/remove-old-versions.sh
  hack/update-istio.sh
  hack/update-profiles-list.sh
  hack/update-version-list.sh
  hack/validate_semver.sh
  pkg/common/config.go
  pkg/common/metadata.go
  pkg/helm/ownerreferences.go
  pkg/helm/ownerreferences_test.go
  pkg/helm/restclientgetter.go
  pkg/helm/values.go
  pkg/helm/values_test.go
  pkg/kube/finalizers.go
  pkg/kube/finalizers_test.go
  pkg/kube/status-patch.go
  pkg/test/environment.go
  pkg/version/version.go
  tools/update_deps.sh
Labels: okay to merge, size/L

#1503 OSSM-5439 Remove the 2.2 SMCP option from the 2.5 SM drop-down in UI
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.5.0/maistraoperator.v2.5.0.clusterserviceversion.yaml
  manifests-servicemesh/2.5.0/servicemeshoperator.v2.5.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#1552 OSSM-5584 Move integration tests into a separate package
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/istiorevision/suite_test.go
  tests/integration/istiorevision_test.go
  tests/integration/suite_test.go
Labels: okay to merge, size/XL

#1553 OSSM-5575 Update kubebuilder from v3 to v4
  Makefile.core.mk
  PROJECT
  bundle.Dockerfile
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  cmd/main.go
Labels: okay to merge, size/S

#1531 OSSM-5444-1 Support provider zipkin
  Makefile
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.5.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.5.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/extension_providers.go
  pkg/apis/maistra/conversion/extension_providers_test.go
  pkg/apis/maistra/v2/extension_providers.go
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/versions/strategy_v2_4.go
  pkg/controller/versions/strategy_v2_5.go
Labels: okay to merge, size/L

#1558 OSSM-5444: Fix mapping `spec.tracing.type: None` to helm values
  pkg/apis/maistra/conversion/jaeger_test.go
  pkg/apis/maistra/conversion/tracing.go
  resources/helm/overlays/global.yaml
  resources/helm/v2.5/global.yaml
Labels: okay to merge, size/M
