Repository maistra/istio-operator, pull requests merged in 2023-01, with the labels that each got.

#1054 OSSM-2073: Add integration tests for checking sidecar injection in KinD
  Makefile
  deploy/examples/maistra_v2_servicemeshcontrolplane_cr_minimal.yaml
  tests/integration/README.md
  tests/integration/build-operator.sh
  tests/integration/config/default.yaml
  tests/integration/config/topology/singlecluster.json
  tests/integration/deploy-operator.sh
  tests/integration/istio-integ-suite-kind.sh
  tests/integration/kind_provisioner.sh
  tests/integration/lib.sh
  tests/integration/metallb.yaml
  tests/integration/operator-integ-suite-kind.sh
  tests/integration/smcp-httpbin-test.sh
Labels: okay to merge, size/XXL

#1090 OSSM-2492 Pass tolerations to Jaeger
  resources/helm/overlays/istio-telemetry/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/overlays/istio-telemetry/tracing/templates/jaeger-production-elasticsearch.yaml
  resources/helm/v2.3/istio-telemetry/tracing/templates/jaeger-all-in-one.yaml
  resources/helm/v2.3/istio-telemetry/tracing/templates/jaeger-production-elasticsearch.yaml
Labels: okay to merge, size/M

#1091 OSSM-2493 Pass default nodeSelector and tolerations to Kiali
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.3/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/S

#1082 [OSSM-2221 | OSSM-2340] Ensure injection in SMCP ns disabled below v2.4
  pkg/controller/servicemesh/controlplane/deleter.go
  pkg/controller/servicemesh/controlplane/namespace_labels.go
  pkg/controller/servicemesh/controlplane/reconciler.go
  pkg/controller/servicemesh/controlplane/reconciler_test.go
  resources/helm/overlays/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.4/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  resources/helm/v2.4/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/L
