Repository maistra/istio-operator, pull requests merged in 2023-09, with the labels that each got.

#1295 Add arm64 to servicemesh manifests
  build/generate-manifests.sh
  manifests-servicemesh/2.4.3/servicemeshoperator.v2.4.3.clusterserviceversion.yaml
Labels: okay to merge, size/XS, ok-to-test

#1296 OSSM-4763: Enable arm64 in globals
  manifests-maistra/2.4.3/maistraoperator.v2.4.3.clusterserviceversion.yaml
  manifests-servicemesh/2.4.3/servicemeshoperator.v2.4.3.clusterserviceversion.yaml
  resources/helm/overlays/global.yaml
  resources/helm/v2.4/global.yaml
Labels: okay to merge, size/XS

#1292 OSSM-4491 Add missing configuration options to EnvoyExtAuthzHttp
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.4.3/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.4.3/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/extension_providers.go
  pkg/apis/maistra/conversion/extension_providers_test.go
  pkg/apis/maistra/v2/extension_providers.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
Labels: okay to merge, size/L

#1274 OSSM-4465 Changing host in DR for Jaeger to FQDN v2.4
  resources/helm/overlays/istio-telemetry/tracing/templates/policy-jaeger.yaml
  resources/helm/v2.4/istio-telemetry/tracing/templates/policy-jaeger.yaml
Labels: okay to merge, size/XS

#1300 Link the gateway docs to the preliminary version of Istio site
  bundle/README.md
Labels: okay to merge, size/XS

#1301 OSSM-4817 Add VERSION column to kubectl get istios
  api/v1alpha1/istio_types.go
  bundle/manifests/operator.istio.io_istios.yaml
  config/crd/bases/operator.istio.io_istios.yaml
Labels: okay to merge, size/S

#1302 Fix make lint-helm
  Makefile
Labels: okay to merge, size/XS

#1304 OSSM-4819: Add a note so we don't forget about it
  go.mod
Labels: okay to merge, size/XS

#1306 OSSM-4842 Print version info on --version
  main.go
Labels: okay to merge, size/XS

#1310 OSSM-4632 Avoid nil value in runAsGroup in injection template
  build/patch-charts.sh
  resources/helm/v2.2/istio-control/istio-discovery/files/gateway-injection-template.yaml
  resources/helm/v2.2/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, size/S

#1314 OSSM-4855 Adding build operator support for MacOs
  Makefile
  build/split-istio-crds.sh
Labels: okay to merge, size/XS

#1312 Use a string for the channels field
  Makefile
  bundle.Dockerfile
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: okay to merge, size/XS

#1316 Run make gen
  resources/helm/v2.2/istio-control/istio-discovery/files/gateway-injection-template.yaml
  resources/helm/v2.2/istio-control/istio-discovery/files/injection-template.yaml
  resources/helm/v2.2/istio-telemetry/tracing/templates/policy-jaeger.yaml
Labels: okay to merge, size/S

#1315 OSSM-4632 Avoid nil value in runAsGroup in injection template
  build/patch-charts.sh
  resources/helm/v2.3/istio-control/istio-discovery/files/gateway-injection-template.yaml
  resources/helm/v2.3/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, size/S

#1318 OSSM-4632 Avoid nil value in runAsGroup in injection template (#1310)
  build/patch-charts.sh
  resources/helm/v2.4/istio-control/istio-discovery/files/gateway-injection-template.yaml
  resources/helm/v2.4/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, size/S

#1317 OSSM-4855 Add support to build operator on MacOs
  Makefile
  build/generate-manifests.sh
  build/split-istio-crds.sh
Labels: okay to merge, size/XS, cherrypick/maistra-2.4

#1321 OSSM-3771 - Add routeConfig to additionalGateways in SMCP
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.4.3/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.4.3/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/gateways.go
  pkg/apis/maistra/conversion/gateways_test.go
  pkg/apis/maistra/v2/gateways.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/servicemesh/controlplane/gateways_test.go
Labels: okay to merge, size/L, ok-to-test

#1325 Fix naming
  config/samples/operator.istio.io_v1alpha1_istio.yaml
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  pkg/helm/charts.go
  pkg/helm/ownerreferences.go
  pkg/strategy/maistra_30_strategy.go
  pkg/strategy/versionstrategy.go
  pkg/test/environment.go
Labels: okay to merge, size/L

#1324 OSSM-4869 Fix Linux support
  Makefile
Labels: okay to merge, size/XS, cherrypick/maistra-2.2, cherrypick/maistra-2.4

#1323 OSSM-4869 Fix Linux support
  Makefile
Labels: okay to merge, size/XS

#1326 OSSM-4849 Add status to Istio resource
  api/v1alpha1/istio_types.go
  api/v1alpha1/istio_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istios.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/suite_test.go
Labels: okay to merge, size/XL
