Repository maistra/istio-operator, pull requests merged in 2023-04, with the labels that each got.

#1157 OSSM-3717 Fix CNI ConfigMap reference for v2.3
  resources/helm/overlays/istio_cni/templates/daemonset-v2.3.yaml
  resources/helm/v2.4/istio_cni/templates/daemonset-v2.3.yaml
Labels: okay to merge, size/XS

#1158 OSSM-3291: Remove validations of extension providers in SMCP v1
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/strategy_v1_1_test.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/L

#1155 OSSM-3235 Ensure operator can't deadlock because istiod isn't running
  build/patch-charts.sh
  resources/helm/v2.4/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
Labels: okay to merge, size/S

#1160 OSSM-1352: Integrate with custom Kiali and external Prometheus
  Makefile
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/controller/servicemesh/controlplane/addons.go
  pkg/controller/servicemesh/controlplane/addons_test.go
  pkg/controller/servicemesh/controlplane/common_test.go
  pkg/controller/servicemesh/controlplane/gateways_test.go
  pkg/controller/servicemesh/controlplane/integration_test.go
  pkg/controller/servicemesh/controlplane/networkpolicy_test.go
  pkg/controller/servicemesh/controlplane/rls_test.go
  pkg/controller/servicemesh/controlplane/wasm_extensions_test.go
  pkg/controller/versions/strategy_v2_4.go
Labels: okay to merge, size/L

#1162 Update istio-csr-helm-values.yaml
  deploy/examples/cert-manager/istio-csr-helm-values.yaml
Labels: okay to merge, size/S

#1163 Updating the Cert-Manager DNS name
  deploy/examples/cert-manager/istio-csr-helm-values.yaml
Labels: okay to merge, size/XS

#1156 OSSM-3703: Add example of certificate rotation with cert-manager
  deploy/examples/cert-manager/README.md
  deploy/examples/cert-manager/custom-cert-rotation/README.md
  deploy/examples/cert-manager/custom-cert-rotation/cacerts.yaml
  deploy/examples/cert-manager/custom-cert-rotation/cluster-issuer.yaml
  deploy/examples/cert-manager/custom-cert-rotation/mesh.yaml
  deploy/examples/cert-manager/istio-csr/README.md
  deploy/examples/cert-manager/istio-csr/istio-ca.yaml
  deploy/examples/cert-manager/istio-csr/istio-csr.yaml
  deploy/examples/cert-manager/istio-csr/mesh.yaml
  deploy/examples/cert-manager/istio-csr/route.yaml
  deploy/examples/cert-manager/istio-csr/selfsigned-ca.yaml
  deploy/examples/cert-manager/istio-csr/smcp-2.3.1.yaml
Labels: okay to merge, size/L

#1166 OSSM-3235 Ensure operator can't deadlock because istiod isn't running [maistra-2.3]
  build/patch-charts.sh
  resources/helm/v2.3/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
Labels: okay to merge, size/S

#1165 OSSM-3235 Ensure operator can't deadlock because istiod isn't running [maistra-2.2]
  build/patch-charts.sh
  resources/helm/v2.2/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
Labels: okay to merge, size/S

#1168 Update charts & make gen
  resources/helm/v2.2/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
  resources/helm/v2.3/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
Labels: okay to merge, size/XS

#1169 OSSM-3747: Remove duplicated env vars from gateway templates
  build/patch-charts.sh
  resources/helm/v2.4/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.4/gateways/istio-ingress/templates/deployment.yaml
Labels: okay to merge, size/M

#1172 [maistra-2.3] OSSM-3747: Remove duplicated env vars from gateway templates
  build/patch-charts.sh
  resources/helm/v2.2/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
  resources/helm/v2.3/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.3/gateways/istio-ingress/templates/deployment.yaml
Labels: okay to merge, size/M

#1171 [maistra-2.2] OSSM-3747: Remove duplicated env vars from gateway templates
  build/patch-charts.sh
  resources/helm/v2.2/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.2/gateways/istio-ingress/templates/deployment.yaml
Labels: okay to merge, size/M

#1174 OSSM-3747: Update gateway templates 2.2
  resources/helm/v2.2/gateways/istio-egress/templates/deployment.yaml
  resources/helm/v2.2/gateways/istio-ingress/templates/deployment.yaml
Labels: okay to merge, size/S

#1159 OSSM-3654 Set ior to disabled by default
  build/patch-charts.sh
  resources/helm/v2.4/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/S

#1175 OSSM-3803 Move extensionProviders to SMCP.spec.meshConfig.extensionProviders
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.4.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.4.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/extension_providers.go
  pkg/apis/maistra/conversion/extension_providers_test.go
  pkg/apis/maistra/conversion/zz_generated.conversion.go
  pkg/apis/maistra/v2/meshconfig.go
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
  pkg/controller/versions/strategy_v2_2.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/strategy_v2_4.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/XXL

#1148 OSSM-3684: Simplify certificates configuration for Istio 1.16
  pkg/apis/maistra/conversion/common.go
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/security.go
  pkg/apis/maistra/conversion/security_test.go
Labels: okay to merge, size/L, jira/valid-reference

#1177 OSSM-3654 Disable IOR by default in v2.4
  resources/smcp-templates/v2.4/base
Labels: okay to merge, size/XS

#1178 Add infra tool for Git on Prow
  tools/run-test-infra-script.sh
Labels: okay to merge, size/M, cherrypick/maistra-2.2, cherrypick/maistra-2.3
