Repository maistra/istio-operator, pull requests merged in 2023-08, with the labels that each got.

#1263 OSSM-4574: link to instructions for bookinfo
  bundle/README.md
Labels: okay to merge, size/XS

#1265 OSSM-4639 fixing Unrecognized import path "vbom.ml/util"
  go.mod
  go.sum
Labels: okay to merge, size/XS

#1276 Fix the update-istio target
  Makefile
Labels: okay to merge, size/XS

#1267 OSSM-4194 Made change to the host in the DestinationRule v2.2
  resources/helm/overlays/mesh-config/templates/enable-mesh-mtls.yaml
  resources/helm/v2.2/mesh-config/templates/enable-mesh-mtls.yaml
Labels: okay to merge, size/XS

#1262 OSSM-3508 Allow cluster-scoped SMCP when user has cluster-scoped create SMCP privilege
  pkg/controller/versions/strategy_v2_4.go
Labels: okay to merge, size/S, cherrypick/maistra-2.5

#1232 OSSM-4194 Made change to the host in the DestinationRule v2.4
  resources/helm/overlays/mesh-config/templates/enable-mesh-mtls.yaml
  resources/helm/v2.4/mesh-config/templates/enable-mesh-mtls.yaml
Labels: okay to merge, size/XS

#1279 Run make gen
  resources/helm/v2.2/mesh-config/templates/enable-mesh-mtls.yaml
Labels: okay to merge, size/XS

#1268 OSSM-4194 Make Changes to the host in Destination Rule v2.3
  resources/helm/overlays/mesh-config/templates/enable-mesh-mtls.yaml
  resources/helm/v2.3/mesh-config/templates/enable-mesh-mtls.yaml
Labels: okay to merge, size/XS

#1282 OSSM-4465 Destination Rule for Jaeger v2.3
  resources/helm/overlays/istio-telemetry/tracing/templates/policy-jaeger.yaml
  resources/helm/v2.3/istio-telemetry/tracing/templates/policy-jaeger.yaml
Labels: okay to merge, size/XS

#1231 OSSM-3979 Adding EnvoyExtAuthzGRPC to GA
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.4.3/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.4.3/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/extension_providers.go
  pkg/apis/maistra/conversion/extension_providers_test.go
  pkg/apis/maistra/v2/extension_providers.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/versions/strategy_v2_4.go
Labels: okay to merge, size/XL

#1288 Remove privilege commands from test and doc
  bundle/README.md
  tests/integration/operator-integ-suite-ocp.sh
Labels: okay to merge, size/M

#1289 OSSM-4711: Remove default gateway installations
  controllers/istiohelminstall_controller.go
  tests/integration/operator-integ-suite-ocp.sh
Labels: okay to merge, size/S

#1287 OSSM-4758 OSSM-4759 Rename IstioHelmInstall to Istio and move to operator.istio.io/v1alpha1
  PROJECT
  README.md
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/istio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/README.md
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  config/crd/bases/operator.istio.io_istios.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_istios.yaml
  config/crd/patches/webhook_in_istios.yaml
  config/manifests/bases/sailoperator.clusterserviceversion.yaml
  config/rbac/istio_editor_role.yaml
  config/rbac/istio_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/operator.istio.io_v1alpha1_istio.yaml
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/suite_test.go
  hack/lint-watches.sh
  main.go
  pkg/common/metadata.go
  pkg/istio/maistra_30_strategy.go
  pkg/istio/versionstrategy.go
  pkg/kube/finalizers_test.go
  pkg/test/environment.go
  tests/integration/operator-integ-suite-ocp.sh
Labels: okay to merge, size/L
