Repository maistra/istio-operator, pull requests merged in 2023-06, with the labels that each got.

#1199 OSSM-4015 Add tests to the operator
  Dockerfile
  Makefile
  README.md
  TODO.md
  api/v1/istiohelminstall_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/maistra.io_istiohelminstalls.yaml
  controllers/istiohelminstall_controller.go
  controllers/istiohelminstall_controller_test.go
  controllers/suite_test.go
  go.mod
  main.go
  pkg/common/config.go
  pkg/helm/charts.go
  pkg/helm/restclientgetter.go
  pkg/istio/maistra_30_strategy.go
  pkg/istio/versionstrategy.go
  pkg/kube/finalizers.go
  pkg/kube/finalizers_test.go
  pkg/kube/k8s.go
  pkg/kube/status-patch.go
  pkg/test/environment.go
Labels: okay to merge, size/XL

#1202 OSSM-3709 Publish operator bundle
  Makefile
  PROJECT
  README.md
  bundle.Dockerfile
  bundle/manifests/maistraoperator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/maistraoperator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/maistraoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/maistraoperator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/istiohelminstall_editor_role.yaml
  config/rbac/istiohelminstall_viewer_role.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/maistra.io_v1_istiohelminstall.yaml
  hack/operatorhub/operatorhub-pr-template.md
  hack/operatorhub/publish-bundle.sh
  hack/validate_semver.sh
Labels: okay to merge, size/L

#1208 OSSM-4016 Changes to better support maistra-assist
  Makefile
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
Labels: okay to merge, size/M

#1204 Log version on startup
  Dockerfile
  Makefile
  main.go
  pkg/version/version.go
Labels: okay to merge, size/M

#1209 OSSM-3709 Some fixes for the OLM bundle generation
  Makefile
  bundle.Dockerfile
  bundle/manifests/istio-operator-metrics-service_v1_service.yaml
  bundle/manifests/maistra.io_istiohelminstalls.yaml
  bundle/manifests/maistraoperator.clusterserviceversion.yaml
  bundle/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/metadata/annotations.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  hack/operatorhub/publish-bundle.sh
Labels: okay to merge, size/M

#1210 OSSM-4102 - Add Annotation For network-attachment-definitions
  bundle/manifests/maistraoperator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/istiohelminstall_controller.go
Labels: okay to merge, size/S

#1211 Fix the `deploy` target by silencing Make output
  Makefile
Labels: okay to merge, size/XS

#1215 Add missing annotations for OperatorHub
  Makefile
  bundle/manifests/maistraoperator.clusterserviceversion.yaml
  config/manifests/bases/maistraoperator.clusterserviceversion.yaml
Labels: okay to merge, size/S

#1216 OSSM-4185 Use a simple tag to reference new prometheus images
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.4.0/maistraoperator.v2.4.0.clusterserviceversion.yaml
  manifests-servicemesh/2.4.0/servicemeshoperator.v2.4.0.clusterserviceversion.yaml
Labels: okay to merge, size/S

#1218 Support Makefile.overrides
  Makefile
Labels: okay to merge, size/XS

#1219 Add --log-api-requests option
  main.go
Labels: okay to merge, size/S

#1227 OSSM-3711 Add README.md
  LICENSE
  Makefile
  README.md
  hack/config.properties
  main.go
Labels: okay to merge, size/L

#1220 OSSM-4048 Properly manage owned resources
  Makefile
  api/v1/istiohelminstall_types.go
  controllers/istiohelminstall_controller.go
  controllers/istiohelminstall_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/lint-watches.sh
  main.go
  pkg/helm/charts.go
  pkg/helm/ownerreferences.go
  pkg/helm/restclientgetter.go
Labels: okay to merge, size/XL

#1228 OSSM-4246 Fix make deploy
  Makefile
Labels: okay to merge, size/XS
