Repository maistra/istio-operator, pull requests merged in 2023-03, with the labels that each got.

#1108 OSSM-3288: Add ExtensionProviders
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.4.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.4.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
  pkg/apis/maistra/conversion/extension_providers.go
  pkg/apis/maistra/conversion/extension_providers_test.go
  pkg/apis/maistra/conversion/zz_generated.conversion.go
  pkg/apis/maistra/v2/extension_providers.go
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
Labels: okay to merge, size/L, jira/valid-reference

#1127 Set kiali version to 1.65
  resources/helm/overlays/istio-telemetry/kiali/templates/kiali-cr.yaml
  resources/helm/v2.4/istio-telemetry/kiali/templates/kiali-cr.yaml
Labels: okay to merge, size/XS, ok-to-test

#1126 OSSM-3259 Move controlPlaneMode out of SMCP.spec.techPreview
  build/patch-charts.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.4.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.4.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/conversion_test.go
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
  pkg/apis/maistra/conversion/zz_generated.conversion.go
  pkg/apis/maistra/v2/servicemeshcontrolplane_types.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/memberroll/controller_test.go
  pkg/controller/servicemesh/webhooks/validation/controlplane_test.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
  pkg/controller/versions/strategy_v2_2.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/strategy_v2_4.go
  pkg/controller/versions/util.go
  pkg/controller/versions/versions.go
  resources/helm/v2.4/istio-control/istio-discovery/templates/clusterrolebinding.yaml
  resources/helm/v2.4/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/L

#1131 OSSM-3468 Don't create RoleBindings in member namespace in ClusterWide mode
  pkg/controller/servicemesh/member/controller.go
  pkg/controller/servicemesh/member/controller_test.go
  pkg/controller/servicemesh/member/namespace_reconciler.go
  pkg/controller/servicemesh/member/namespace_reconciler_test.go
Labels: okay to merge, size/M

#1139 OSSM-3577 Change SMMR.spec.memberSelector into an array
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.4.0/servicemeshmemberrolls.crd.yaml
  manifests-servicemesh/2.4.0/servicemeshmemberrolls.crd.yaml
  pkg/apis/maistra/v1/servicemeshmemberroll_types.go
  pkg/apis/maistra/v1/servicemeshmemberroll_types_test.go
  pkg/apis/maistra/v1/zz_generated.deepcopy.go
  pkg/controller/servicemesh/memberroll/controller.go
  pkg/controller/servicemesh/webhooks/validation/memberroll.go
  pkg/controller/servicemesh/webhooks/validation/memberroll_test.go
  pkg/controller/versions/strategy_v2_4.go
Labels: okay to merge, size/L

#1136 OSSM-3291: Promote envoyExtAuthzHttp to GA
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  go.mod
  go.sum
  manifests-maistra/2.4.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.4.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/common.go
  pkg/apis/maistra/conversion/conversion_v1_to_v2.go
  pkg/apis/maistra/conversion/conversion_v2_to_v1.go
  pkg/apis/maistra/conversion/extension_providers.go
  pkg/apis/maistra/conversion/extension_providers_test.go
  pkg/apis/maistra/v1/helmvalues.go
  pkg/apis/maistra/v2/extension_providers.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/versions/strategy_v1_1.go
  pkg/controller/versions/strategy_v1_1_test.go
  pkg/controller/versions/strategy_v2_4.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/XXL, jira/valid-reference

#1143 OSSM-3291: Allow to set `spec.extensionProviders` only in 2.4+
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
  pkg/controller/versions/strategy_v2_2.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/S, jira/valid-reference
