Repository maistra/istio-operator, pull requests merged in 2024-01, with the labels that each got.

#1568 OSSM-5594: Do not disable tracing in Kiali when `spec.tracing: None` is set
  pkg/controller/servicemesh/controlplane/addons.go
Labels: okay to merge, size/M

#1516 OSSM-5444 Support Distributed Tracing 3
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/crd.yaml
  manifests-maistra/2.5.0/servicemeshcontrolplanes.crd.yaml
  manifests-servicemesh/2.5.0/servicemeshcontrolplanes.crd.yaml
  pkg/apis/maistra/conversion/extension_providers.go
  pkg/apis/maistra/conversion/extension_providers_test.go
  pkg/apis/maistra/v2/extension_providers.go
  pkg/apis/maistra/v2/zz_generated.deepcopy.go
  pkg/controller/versions/strategy_v2_4.go
  pkg/controller/versions/strategy_v2_5.go
Labels: okay to merge, size/XL

#1522 OSSM-5416 Building multi-platform container image
  Dockerfile
  Makefile.core.mk
Labels: okay to merge, size/M

#1582 Update deps
  .devcontainer/devcontainer.json
  Makefile.core.mk
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
Labels: okay to merge, size/L

#1581 Prevent nested docker build
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/XS, ok-to-test

#1583 Fix yq usage in update-istio.sh
  hack/update-istio.sh
Labels: okay to merge, size/XS

#1586 OSSM-5812 Ensure CNI is deployed when using the openshift profile
  controllers/istiorevision/istiorevision_controller.go
Labels: okay to merge, size/XS

#1591 OSSM-5815: Adding VALUES_FILE var to be able to overwrite default values
  Makefile.core.mk
Labels: okay to merge, size/S

#1593 Using variable instead of hardcoded string
  Makefile.core.mk
Labels: okay to merge, size/XS

#1594 OSSM-5815: Skip timestamp revert operation for untracked CSV
  Makefile.core.mk
Labels: okay to merge, size/XS

#1595 OSSM-5815: set the operator diplay name dynamically from chart
  chart/templates/olm/clusterserviceversion.yaml
  chart/values.yaml
Labels: okay to merge, size/XS

#1590 OSSM-5685 Support offline installation through default image digests
  chart/templates/auth_proxy_service.yaml
  chart/templates/deployment.yaml
  chart/templates/namespace.yaml
  chart/templates/rbac/auth_proxy_role_binding.yaml
  chart/templates/rbac/leader_election_role_binding.yaml
  chart/templates/rbac/role_binding.yaml
  chart/values.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  pkg/common/config.go
Labels: okay to merge, size/L

#1602 Fix registry detection on long-running OCP
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/XS

#1603 OSSM-5844 Ensure logr gets called correctly
  pkg/helm/charts.go
Labels: okay to merge, size/XS
