Repository maistra/istio-operator, pull requests merged in 2024-07, with the labels that each got.

#1818 OSSM-6757 Ensure CNI pod starts when using older images
  resources/helm/overlays/istio_cni/templates/daemonset-v2.4.yaml
  resources/helm/overlays/istio_cni/templates/daemonset-v2.5.yaml
  resources/helm/overlays/istio_cni/templates/daemonset-v2.6.yaml
  resources/helm/v2.6/istio_cni/templates/daemonset-v2.4.yaml
  resources/helm/v2.6/istio_cni/templates/daemonset-v2.5.yaml
  resources/helm/v2.6/istio_cni/templates/daemonset-v2.6.yaml
Labels: okay to merge, size/M

#1802 OSSM-6391 - 2.6 Disable the OSSM operator's Jaeger and ES installation by default
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.6.0/maistraoperator.v2.6.0.clusterserviceversion.yaml
  manifests-servicemesh/2.6.0/servicemeshoperator.v2.6.0.clusterserviceversion.yaml
  pkg/controller/servicemesh/webhooks/mutation/common_test.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane_test.go
Labels: okay to merge, size/L, ok-to-test

#1825 Make webhook startup logging less verbose
  pkg/controller/servicemesh/webhooks/server.go
Labels: okay to merge, size/M

#1827 OSSM-6774 Use the existing kube clients to create metrics resources
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/common/discovery.go
  pkg/controller/common/util.go
  pkg/controller/servicemesh/controlplane/controller.go
Labels: okay to merge, size/M

#1831 OSSM-6697 Fix duplicate caCertConfigMapName env var
  build/patch-charts.sh
  resources/helm/v2.6/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/XS

#1832 OSSM-6850 Ensure OLM-managed CRDs are never overwritten
  pkg/bootstrap/crds.go
  pkg/bootstrap/crds_test.go
Labels: okay to merge, size/M
