Repository maistra/istio-operator, pull requests merged in 2024-06, with the labels that each got.

#1791 [maistra-2.3] OSSM-6605: Remove telemetry EnvoyFilters
  resources/helm/overlays/mesh-config/templates/telemetryv2_1.6.yaml
  resources/helm/v2.3/mesh-config/templates/telemetryv2_1.6.yaml
Labels: okay to merge, size/XXL

#1789 [maistra-2.5] OSSM-6605: Remove telemetry EnvoyFilters
  resources/helm/overlays/mesh-config/templates/telemetryv2_1.6.yaml
  resources/helm/v2.5/mesh-config/templates/telemetryv2_1.6.yaml
Labels: okay to merge, size/XXL

#1749 OSSM-5921: create istio-reader service account and cluster role when multi-cluster and cluster-wide modes are enabled
  build/patch-charts.sh
  resources/helm/overlays/istio-control/istio-discovery/templates/reader-serviceaccount.yaml
  resources/helm/v2.5/istio-control/istio-discovery/templates/reader-clusterrole.yaml
  resources/helm/v2.5/istio-control/istio-discovery/templates/reader-clusterrolebinding.yaml
  resources/helm/v2.5/istio-control/istio-discovery/templates/reader-serviceaccount.yaml
Labels: okay to merge, size/L, ok-to-test

#1796 OSSM-6339: Bump moby pkg used by helm
  go.mod
  go.sum
Labels: okay to merge, size/M

#1800 Revert "OSSM-6339: Bump moby pkg used by helm"
  go.mod
  go.sum
Labels: okay to merge, size/M

#1801 OSSM-6339: Bump moby to 17.12.0
  go.mod
  go.sum
Labels: okay to merge, size/S

#1803 OSSM-6339: Bump moby to 17.12.0 (#1801)
  go.mod
  go.sum
Labels: okay to merge, size/S

#1804 OSSM-6696: Disable repair controller in istio-cni
  resources/helm/overlays/istio_cni/templates/daemonset-v2.6.yaml
  resources/helm/overlays/istio_cni/values.yaml
  resources/helm/v2.6/istio_cni/templates/daemonset-v2.6.yaml
  resources/helm/v2.6/istio_cni/values.yaml
Labels: okay to merge, size/XS

#1807 OSSM-6336 Deploy istio-cni ClusterRoleBinding and ServiceAccount only when required
  resources/helm/overlays/istio_cni/templates/clusterrolebinding.yaml
  resources/helm/overlays/istio_cni/templates/serviceaccount.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrolebinding.yaml
  resources/helm/v2.6/istio_cni/templates/serviceaccount.yaml
Labels: okay to merge, size/XS

#1808 OSSM-6714 Rename and clean up cni template files
  resources/helm/overlays/istio_cni/templates/clusterrole-v2.0-v2.3.yaml
  resources/helm/overlays/istio_cni/templates/clusterrole-v2.4-v2.6.yaml
  resources/helm/overlays/istio_cni/templates/clusterrole-v2.4.yaml
  resources/helm/overlays/istio_cni/templates/clusterrole-v2.5.yaml
  resources/helm/overlays/istio_cni/templates/clusterrolebinding-v2.0-v2.3.yaml
  resources/helm/overlays/istio_cni/templates/clusterrolebinding-v2.4-v2.6.yaml
  resources/helm/overlays/istio_cni/templates/clusterrolebinding-v2.4.yaml
  resources/helm/overlays/istio_cni/templates/clusterrolebinding-v2.6.yaml
  resources/helm/overlays/istio_cni/templates/configmap-v2.0-v2.2.yaml
  resources/helm/overlays/istio_cni/templates/daemonset-v2.0-v2.2.yaml
  resources/helm/overlays/istio_cni/templates/serviceaccount-v2.0-v2.3.yaml
  resources/helm/overlays/istio_cni/templates/serviceaccount-v2.4-v2.6.yaml
  resources/helm/overlays/istio_cni/templates/serviceaccount-v2.4.yaml
  resources/helm/overlays/istio_cni/templates/serviceaccount-v2.5.yaml
  resources/helm/overlays/istio_cni/templates/serviceaccount-v2.6.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrole-v2.0-v2.3.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrole-v2.4-v2.6.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrole-v2.5.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrole-v2.6.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrolebinding-v2.0-v2.3.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrolebinding-v2.4-v2.6.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrolebinding-v2.4.yaml
  resources/helm/v2.6/istio_cni/templates/clusterrolebinding-v2.6.yaml
  resources/helm/v2.6/istio_cni/templates/configmap-v2.0-v2.2.yaml
  resources/helm/v2.6/istio_cni/templates/daemonset-v2.0-v2.2.yaml
  resources/helm/v2.6/istio_cni/templates/serviceaccount-v2.0-v2.3.yaml
  resources/helm/v2.6/istio_cni/templates/serviceaccount-v2.4-v2.6.yaml
  resources/helm/v2.6/istio_cni/templates/serviceaccount-v2.4.yaml
  resources/helm/v2.6/istio_cni/templates/serviceaccount-v2.5.yaml
  resources/helm/v2.6/istio_cni/templates/serviceaccount-v2.6.yaml
Labels: okay to merge, size/L

#1811 Fix error messages
  pkg/controller/versions/rendering_strategy_v1_x.go
  pkg/controller/versions/strategy_v2_0.go
  pkg/controller/versions/strategy_v2_1.go
  pkg/controller/versions/strategy_v2_2.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/strategy_v2_4.go
  pkg/controller/versions/strategy_v2_5.go
  pkg/controller/versions/strategy_v2_6.go
Labels: okay to merge, size/L

#1810 OSSM-6717 Ensure istio-cni is invoked
  pkg/controller/versions/strategy_v2_6.go
Labels: okay to merge, size/XS

#1809 OSSM-6693: Do not set default values of `PILOT_ENABLE_GATEWAY_API_*`
  build/patch-charts.sh
  resources/helm/v2.6/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/S

#1812 Set must gather image dynamically during cpaas build
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-servicemesh/2.6.0/servicemeshoperator.v2.6.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#1805 OSSM-6693: Enable Gateway API by default in cluster-wide mode
  build/patch-charts.sh
  resources/helm/v2.6/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/XS

#1814 OSSM-6728 Remove the 2.3 SMCP option from the 2.6 SM drop-down in UI
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.6.0/maistraoperator.v2.6.0.clusterserviceversion.yaml
  manifests-servicemesh/2.6.0/servicemeshoperator.v2.6.0.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#1806 OSSM-6411: Copy appropriate istio-cni binary based on host OS
  resources/helm/overlays/istio_cni/templates/daemonset-v2.4.yaml
  resources/helm/overlays/istio_cni/templates/daemonset-v2.5.yaml
  resources/helm/overlays/istio_cni/templates/daemonset-v2.6.yaml
  resources/helm/v2.6/istio_cni/templates/daemonset-v2.4.yaml
  resources/helm/v2.6/istio_cni/templates/daemonset-v2.5.yaml
  resources/helm/v2.6/istio_cni/templates/daemonset-v2.6.yaml
Labels: okay to merge, size/L

#1816 OSSM-2101 Delete unused CNI resources when pruning
  pkg/controller/servicemesh/controlplane/cni_pruner.go
  pkg/controller/servicemesh/controlplane/cni_pruner_test.go
  pkg/controller/servicemesh/controlplane/pruner.go
  pkg/controller/servicemesh/controlplane/reconciler.go
Labels: okay to merge, size/L

#1813 Remove 2.2 version from 2.6 manifests
  build/build.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.6.0/maistraoperator.v2.6.0.clusterserviceversion.yaml
  manifests-servicemesh/2.6.0/servicemeshoperator.v2.6.0.clusterserviceversion.yaml
  pkg/bootstrap/cni_test.go
  pkg/version/version.go
Labels: okay to merge, size/M

#1817 Remove erroneous v2.5.2 CSV from 2.6.0 directories
  manifests-maistra/2.6.0/maistraoperator.v2.5.2.clusterserviceversion.yaml
  manifests-servicemesh/2.6.0/servicemeshoperator.v2.5.2.clusterserviceversion.yaml
Labels: okay to merge, size/XXL
