Repository maistra/istio-operator, pull requests merged in 2024-08, with the labels that each got.

#1840 Update charts from 2.4 and 2.5
  resources/helm/v2.4/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
  resources/helm/v2.5/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml
Labels: okay to merge, size/L

#1841 OSSM 2.6.1 Fix CVP Prometheus errors
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-servicemesh/2.6.1/servicemeshoperator.v2.6.1.clusterserviceversion.yaml
Labels: okay to merge, size/M

#1836 OSSM-4055: Revert "OSSM-3986: Reconcile role bindings for Prometheus (#1194)"
  pkg/controller/servicemesh/member/namespace_reconciler.go
Labels: okay to merge, size/S
