Repository maistra/istio-operator, pull requests merged in 2024-04, with the labels that each got.

#1733 OSSM-6056 Initial changes to add k8s go client to e2e test
  .gitignore
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/integ-suite-kind.sh
  tests/e2e/integ-suite-ocp.sh
  tests/e2e/operator/env.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/operator/operator_test.go
  tests/e2e/operator/util/client/client.go
  tests/e2e/operator/util/gomega/matchers.go
  tests/e2e/operator/util/helm/helm.go
  tests/e2e/operator/util/kubectl/kubectl.go
Labels: okay to merge, size/XL

#1761 OSSM-6163 Fix Grafana oauth client auth error
  resources/helm/overlays/istio-telemetry/grafana/values.yaml
  resources/helm/v2.5/istio-telemetry/grafana/values.yaml
Labels: okay to merge, size/XS

#1765 OSSM-6163 Grafana patch v2.3 v2.4 values in 2.5 branch
  resources/helm/v2.3/istio-telemetry/grafana/values.yaml
  resources/helm/v2.4/istio-telemetry/grafana/values.yaml
Labels: okay to merge, size/XS

#1766 OSSM-6289 Allow istiod to read/write webhookconfigurations in cluster-wide mode
  build/patch-charts.sh
  resources/helm/v2.5/istio-control/istio-discovery/templates/clusterrole.yaml
Labels: okay to merge, size/S

#1772 OSSM-6267 b/c 2.3 branch Grafana helm changes
  resources/helm/overlays/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/overlays/istio-telemetry/grafana/values.yaml
  resources/helm/overlays/istio-telemetry/telemetry-common/templates/htpasswd-secret.yaml
  resources/helm/v2.3/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/v2.3/istio-telemetry/grafana/values.yaml
  resources/helm/v2.3/istio-telemetry/telemetry-common/templates/htpasswd-secret.yaml
Labels: okay to merge, size/S

#1771 OSSM-6267 b/c 2.4 branch Grafana helm changes
  resources/helm/overlays/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/overlays/istio-telemetry/grafana/values.yaml
  resources/helm/overlays/istio-telemetry/telemetry-common/templates/htpasswd-secret.yaml
  resources/helm/v2.3/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/v2.3/istio-telemetry/grafana/values.yaml
  resources/helm/v2.3/istio-telemetry/telemetry-common/templates/htpasswd-secret.yaml
  resources/helm/v2.4/istio-telemetry/grafana/templates/deployment.yaml
  resources/helm/v2.4/istio-telemetry/grafana/values.yaml
  resources/helm/v2.4/istio-telemetry/telemetry-common/templates/htpasswd-secret.yaml
Labels: okay to merge, size/M

#1775 OSSM-6385 Make sure to remove kiali annotation when kiali is disabled
  pkg/controller/servicemesh/memberroll/controller.go
Labels: okay to merge, size/XS
