Repository maistra/istio-operator, pull requests merged in 2024-03, with the labels that each got.

#1657 OSSM-5894 Add tool for transforming upstream values types to the operator API
  Makefile.core.mk
  api/v1alpha1/meshconfig_deps_types.go
  api/v1alpha1/meshconfig_types.go
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/values_types.go
  api/v1alpha1/values_types_extra.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  go.mod
  hack/api_transformer/main.go
  hack/api_transformer/transform.yaml
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
Labels: okay to merge, size/XXL

#1653 OSSM-5999: Set istio settings in custom Kiali resource automatically
  pkg/controller/servicemesh/controlplane/addons.go
Labels: okay to merge, size/S

#1662 Print debug information when integration test fails
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/S

#1663 Make scorecard test work in kind
  Makefile.core.mk
  tests/integration/common-operator-integ-suite.sh
  tests/scorecard-test.sh
Labels: okay to merge, size/M

#1361 Fix `make help`
  Makefile.core.mk
  Makefile.overrides.mk
Labels: okay to merge, size/M

#1666 OSSM-3368: Update error message on update of SMCP mode
  pkg/controller/versions/strategy_v2_4.go
Labels: okay to merge, size/XS

#1669 Improvements to debug output when integration test fails
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/XS

#1670 Remove error logging for expected failures, add requeues
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
Labels: okay to merge, size/M

#1672 OSSM-6049 Change nodeSelector fields type
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  hack/api_transformer/transform.yaml
  hack/download-charts.sh
  resources/v1.19.7/profiles/default.yaml
  resources/v1.20.3/profiles/default.yaml
Labels: okay to merge, size/XL

#1668 Rename go pkg to github.com/istio-ecosystem/sail-operator
  Makefile.core.mk
  api/v1alpha1/values_types_extra.go
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  go.mod
  pkg/kube/finalizers.go
  pkg/kube/finalizers_test.go
  pkg/test/environment.go
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/api/k8sapi_utils.go
  tests/integration/api/suite_test.go
Labels: okay to merge, size/L

#1673 s/istio-operator/sail-operator/ in most of places
  Dockerfile
  Makefile.core.mk
  bundle/manifests/sail-operator-metrics-service_v1_service.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/Chart.yaml
  chart/templates/deployment.yaml
  chart/templates/olm/clusterserviceversion.yaml
  chart/values.yaml
  cmd/main.go
  controllers/istiorevision/istiorevision_controller_test.go
  pkg/common/metadata.go
  tests/integration/README.md
  tests/integration/api/suite_test.go
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/M

#1675 Rename "Istio operator" in README and docs
  README.md
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  tests/integration/README.md
Labels: okay to merge, size/S

#1677 Prepare for fork
  Makefile.core.mk
  hack/patch-istio-crd.sh
  hack/remove-old-versions.sh
  hack/update-istio.sh
  hack/update-profiles-list.sh
  hack/update-version-list.sh
  tests/integration/api/versions.go
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/L

#1682 Add ginkgolinter
  common/config/.golangci.yml
  pkg/kube/finalizers_test.go
  tools/golangci-override.yaml
Labels: okay to merge, size/S

#1665 OSSM-5541: istio-operator Pod keeps waiting for leader lease
  cmd/manager/main.go
Labels: okay to merge, size/S

#1685 OSSM-6088 Leader election improvements
  cmd/main.go
Labels: okay to merge, size/XS

#1640 OSSM 5344 Ginkgo Operator testing Framework
  .gitignore
  Makefile.core.mk
  README.md
  chart/templates/namespace.yaml
  pkg/util/tests/ginkgo/ginkgo_util.go
  pkg/util/tests/helm/helm.go
  pkg/util/tests/kubectl/kubectl.go
  pkg/util/tests/shell/shell.go
  pkg/util/tests/types/resourcecondition_types.go
  pkg/util/tests/types/resourcelist_types.go
  tests/integration/README.md
  tests/integration/common-operator-integ-suite.sh
  tests/integration/operator/env_utils.go
  tests/integration/operator/operator_suite_test.go
  tests/integration/operator/operator_test.go
Labels: okay to merge, size/XXL

#1691 Remove ignore-not-found option
  Makefile.core.mk
Labels: okay to merge, size/S

#1689 Run tests wih "--no-color" only when not attached to a terminal
  tests/integration/common-operator-integ-suite.sh
Labels: okay to merge, size/XS

#1692 OSSM-6110 Check istiod version in e2e test
  pkg/util/tests/kubectl/kubectl.go
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/operator/env_utils.go
  tests/integration/operator/operator_suite_test.go
  tests/integration/operator/operator_test.go
  tests/integration/supportedversion/supportedversion.go
  versions.yaml
Labels: okay to merge, size/L

#1695 Test improvements
  Makefile.core.mk
  tests/integration/common-operator-integ-suite.sh
  tests/integration/operator/env_utils.go
  tests/integration/operator/operator_suite_test.go
  tests/integration/operator/operator_test.go
Labels: okay to merge, size/S, tide/merge-method-rebase

#1696 Ensure automatic update of version in Istio CR samples
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/samples/istio-sample-kubernetes.yaml
  chart/samples/istio-sample-openshift.yaml
  hack/update-version-list.sh
  versions.yaml
Labels: okay to merge, size/S

#1700 Refactor helm
  cmd/main.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  pkg/helm/chartmanager.go
  tests/integration/api/suite_test.go
Labels: okay to merge, size/L

#1704 Fix e2e cleanup timing out
  pkg/util/tests/kubectl/kubectl.go
  tests/integration/operator/operator_test.go
Labels: okay to merge, size/M

#1676 OSSM-5871 Introduce IstioCNI resource and controller
  README.md
  api/v1alpha1/istiocni_types.go
  api/v1alpha1/istiorevision_types.go
  api/v1alpha1/istiorevision_types_test.go
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/values_types_extra.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiocnis.yaml
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/operator.istio.io_istiocnis.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  chart/samples/istiocni-sample.yaml
  chart/templates/rbac/role.yaml
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  hack/api_transformer/transform.yaml
  hack/download-charts.sh
  hack/lint-watches.sh
  hack/update-profiles-list.sh
  hack/update-version-list.sh
  pkg/profiles/profiles.go
  pkg/profiles/profiles_test.go
  pkg/requestmappers/requestmappers.go
  pkg/util/tests/kubectl/kubectl.go
  resources/v1.20.3/profiles/openshift.yaml
  tests/integration/api/istio_test.go
  tests/integration/api/istiocni_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/api/k8sapi_utils.go
  tests/integration/api/suite_test.go
  tests/integration/operator/env_utils.go
  tests/integration/operator/operator_test.go
Labels: okay to merge, size/XXL

#1706 Update bundle/README
  bundle/README.md
Labels: okay to merge, size/L

#1708 Fix path
  bundle/README.md
Labels: okay to merge, size/XS

#1707 Simplify scheme usage by centralizing the scheme
  cmd/main.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller_test.go
  go.mod
  pkg/scheme/scheme.go
  pkg/test/environment.go
  tests/integration/api/suite_test.go
Labels: okay to merge, size/L

#1709 OSSM-6131 Split Test suites on integration and e2e
  Makefile.core.mk
  tests/e2e/README.md
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/config/default.yaml
  tests/e2e/config/role-bindings.yaml
  tests/e2e/integ-suite-kind.sh
  tests/e2e/integ-suite-ocp.sh
  tests/e2e/operator/env_utils.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/operator/operator_test.go
  tests/integration/README.md
  tests/scorecard-test.sh
  tools/golangci-override.yaml
Labels: okay to merge, size/L

#1713 Ensure that the linter doesn't ignore e2e tests
  common/config/.golangci.yml
  tools/golangci-override.yaml
Labels: okay to merge, size/S

#1710 OSSM-6126 Handle conflict when removing finalizer
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  go.mod
  pkg/kube/finalizers.go
  pkg/kube/finalizers_test.go
Labels: okay to merge, size/L

#1716 Improve organization of test util packages
  pkg/test/util/ginkgo/ginkgo.go
  pkg/test/util/supportedversion/supportedversion.go
  pkg/util/tests/types/resourcecondition_types.go
  pkg/util/tests/types/resourcelist_types.go
  tests/e2e/operator/env.go
  tests/e2e/operator/operator_test.go
  tests/e2e/operator/util/helm/helm.go
  tests/e2e/operator/util/kubectl/kubectl.go
  tests/e2e/operator/util/kubectl/resourcecondition_types.go
  tests/e2e/operator/util/kubectl/resourcelist_types.go
  tests/e2e/operator/util/shell/shell.go
  tests/integration/api/istio_test.go
  tests/integration/api/istiocni_test.go
  tests/integration/api/istiorevision_test.go
Labels: okay to merge, size/L

#1712 Update make docker-push to build and push
  Makefile.core.mk
  tests/e2e/common-operator-integ-suite.sh
Labels: okay to merge, size/XS

#1711 OSSM-6132 Split make test targets
  Makefile.core.mk
  tests/integration/api/istio_test.go
  tests/integration/api/istiocni_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/api/suite_test.go
Labels: okay to merge, size/S

#1717 Comment out NetworkPolicy which is optional
  chart/samples/ingress-gateway.yaml
Labels: okay to merge, size/S

#1715 OSSM-6128 Improve code for adding finalizer
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/kube/finalizers.go
  pkg/kube/finalizers_test.go
Labels: okay to merge, size/L

#1719 Fix copyright
  Makefile.core.mk
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/integ-suite-kind.sh
  tests/e2e/integ-suite-ocp.sh
Labels: okay to merge, size/M

#1721 Refactor finalizers and improve logging
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/kube/finalizers.go
  pkg/kube/finalizers_test.go
  pkg/util/tests/kube/kube.go
Labels: okay to merge, size/L

#1722 Delete coverprofile from make test
  Makefile.core.mk
Labels: okay to merge, size/XS

#1723 Don't silently ignore errors in docker build/push
  Makefile.core.mk
Labels: okay to merge, size/XS

#1731 OSSM-6140 Ensure IstioCNI status is updated on reconcile errors
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
Labels: okay to merge, size/M

#1734 Ensure IstioCNI is properly included in the CSV
  PROJECT
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/olm/samples.yaml
Labels: okay to merge, size/M

#1732 OSSM-6155 Return Client.get error instead of just logging it
  controllers/istio/istio_controller.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
Labels: okay to merge, size/XS

#1736 Improve status conditions
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiocni_types.go
  api/v1alpha1/istiorevision_types.go
  api/v1alpha1/istiorevision_types_test.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  tests/integration/api/istiocni_test.go
  tests/integration/api/istiorevision_test.go
Labels: okay to merge, size/L

#1737 Simplify determineXyzCondition functions
  api/v1alpha1/istiorevision_types.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
Labels: okay to merge, size/L

#1739 OSSM-6169 Set status to Unknown when condition can't be ascertained
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
Labels: okay to merge, size/L

#1742 OSSM-6153 Simplify error handling around updateStatus()
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
Labels: okay to merge, size/L

#1743 Extract determineStatus() from updateStatus()
  controllers/istio/istio_controller.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
Labels: okay to merge, size/M

#1746 OSSM-6180 Don't create IstioCNI resource when running `make deploy`
  chart/templates/olm/samples.yaml
Labels: okay to merge, size/XS

#1727 OSSM-4840 Ensure chart is rendered even when existing helm release is in a weird state
  Makefile.core.mk
  api/v1alpha1/values_types_extra.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/helm/chartmanager.go
  pkg/helm/chartmanager_test.go
  pkg/helm/testdata/chart/Chart.yaml
  pkg/helm/testdata/chart/templates/configmap.yaml
  pkg/helm/values.go
  pkg/test/environment.go
  tests/integration/api/suite_test.go
Labels: okay to merge, size/L

#1747 OSSM-6163: Fix v2.5 SMCP Prometheus route errors
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-servicemesh/2.5.0/servicemeshoperator.v2.5.0.clusterserviceversion.yaml
  manifests-servicemesh/2.5.1/servicemeshoperator.v2.5.1.clusterserviceversion.yaml
Labels: okay to merge, size/S

#1748 Refactor and clean up
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiocni_types.go
  api/v1alpha1/istiorevision_types.go
  api/v1alpha1/values_types_extra.go
  bundle/manifests/operator.istio.io_istiocnis.yaml
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiocnis.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  hack/api_transformer/main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/constants/constants.go
  pkg/helm/chartmanager.go
  pkg/helm/chartmanager_test.go
  pkg/helm/ownerreferences.go
  pkg/helm/values.go
  pkg/helm/values_test.go
  pkg/kube/finalizers_test.go
  pkg/profiles/profiles.go
  pkg/profiles/profiles_test.go
  pkg/requestmappers/requestmappers.go
  pkg/test/environment.go
  pkg/util/tests/kube/kube.go
  tests/e2e/operator/util/shell/shell.go
  tests/integration/api/suite_test.go
Labels: okay to merge, size/L

#1751 Small adjustements to the publish bundle script
  Makefile.core.mk
  hack/operatorhub/publish-bundle.sh
Labels: okay to merge, size/M

#1750 Run all ginkgo tests with --no-color when running in CI
  Makefile.core.mk
  tests/e2e/common-operator-integ-suite.sh
Labels: okay to merge, size/S

#1753 Fix --no-color in e2e tests
  tests/e2e/common-operator-integ-suite.sh
Labels: okay to merge, size/XS

#1755 OSSM-6189 Update status even when status can't be determined
  api/v1alpha1/istio_types.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/errlist/builder.go
  pkg/errlist/builder_test.go
Labels: okay to merge, size/L
