Repository maistra/istio-operator, pull requests merged in 2024-05, with the labels that each got.

#1776 [OSSM-6331] Add istiod logLevel validation
  pkg/apis/maistra/v2/logging.go
  pkg/controller/versions/strategy_v2_3.go
  pkg/controller/versions/strategy_v2_4.go
  pkg/controller/versions/strategy_v2_5.go
  pkg/controller/versions/util.go
Labels: okay to merge, size/M

#1778 OSSM cleanup 2.2 manifest and references
  Makefile
  build/build.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.5.2/maistraoperator.v2.5.2.clusterserviceversion.yaml
  manifests-servicemesh/2.5.2/servicemeshoperator.v2.5.2.clusterserviceversion.yaml
  pkg/bootstrap/cni_test.go
  pkg/version/version.go
Labels: okay to merge, size/M

#1781 OSSM-6426 Add config options for leader election
  cmd/manager/main.go
  pkg/controller/common/config.go
Labels: okay to merge, size/M

#1779 OSSM-4585 include must-gather image in csv
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-servicemesh/2.5.2/servicemeshoperator.v2.5.2.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#1783 Keep 2.2 manifests for upgrade testing from 2.2 to 2.3
  Makefile
  build/build.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.5.2/maistraoperator.v2.5.2.clusterserviceversion.yaml
  manifests-servicemesh/2.5.2/servicemeshoperator.v2.5.2.clusterserviceversion.yaml
  pkg/bootstrap/cni_test.go
  pkg/version/version.go
Labels: okay to merge, size/M

#1785 OSSM-4585 Update must-gather related image in csv
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-servicemesh/2.5.2/servicemeshoperator.v2.5.2.clusterserviceversion.yaml
Labels: okay to merge, size/XS

#1786 OSSM-6403: Set proxy GID in runAsGroup
  build/patch-charts.sh
  resources/helm/v2.5/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, size/S

#1787 [maistra-2.4] OSSM-6403: Set proxy GID in runAsGroup
  build/patch-charts.sh
  resources/helm/v2.4/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, size/S

#1788 [maistra-2.5] make gen
  resources/helm/v2.4/istio-control/istio-discovery/files/injection-template.yaml
Labels: okay to merge, size/XS
