Repository maistra/istio-operator, pull requests merged in 2024-02, with the labels that each got.

#1608 OSSM-5855 HELM_TEMPL_DEF_FLAGS changes in var declaration
  Makefile.core.mk
Labels: okay to merge, size/XS

#1611 Organice API integration test in their own folder
  tests/integration/api/apierror_matchers.go
  tests/integration/api/ginkgo_utils.go
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/api/k8sapi_utils.go
  tests/integration/api/suite_test.go
  tests/integration/api/versions.go
Labels: okay to merge, size/XS

#1597 OSSM-5570 Add values and meshConfig types
  Makefile.core.mk
  api/v1alpha1/istio_types.go
  api/v1alpha1/meshconfig_deps_types.go
  api/v1alpha1/meshconfig_types.go
  api/v1alpha1/values_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istios.yaml
  controllers/istio/istio_controller_test.go
  tests/integration/api/istio_test.go
Labels: okay to merge, size/XXL

#1618 OSSM-5878 Add "profile" and "compatibilityVersion" to values struct
  api/v1alpha1/values_types.go
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istios.yaml
Labels: okay to merge, size/S

#1620 OSSM-5884 Add global.proxy.resources
  api/v1alpha1/values_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istios.yaml
Labels: okay to merge, size/L

#1624 OSSM-5888 Make sure we update customresourcedefinitions.owned in CSV
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/olm/clusterserviceversion.yaml
Labels: okay to merge, size/L

#1625 OSSM-5885 Fix the json patch to enable OpenShiftRoute
  pkg/controller/servicemesh/webhooks/mutation/common_test.go
  pkg/controller/servicemesh/webhooks/mutation/controlplane.go
Labels: okay to merge, size/S

#1626 OSSM 2.5 cleanup 2.1 manifest and references
  Makefile
  build/build.sh
  deploy/maistra-operator.yaml
  deploy/servicemesh-operator.yaml
  deploy/src/deployment-maistra.yaml
  deploy/src/deployment-servicemesh.yaml
  manifests-maistra/2.5.0/maistraoperator.v2.5.0.clusterserviceversion.yaml
  manifests-servicemesh/2.5.0/servicemeshoperator.v2.5.0.clusterserviceversion.yaml
  pkg/apis/maistra/v2/smcp_new.yaml
  pkg/bootstrap/cni_test.go
  pkg/version/version.go
Labels: okay to merge, size/M

#1617 OSSM-5849 - add infrastructure feature related annotations
  build/generate-manifests.sh
  build/manifest-templates/clusterserviceversion.yaml
  manifests-maistra/2.5.0/maistraoperator.v2.5.0.clusterserviceversion.yaml
  manifests-servicemesh/2.5.0/servicemeshoperator.v2.5.0.clusterserviceversion.yaml
Labels: okay to merge, size/M, ok-to-test

#1629 Fix installation after removing support for v2.1
  pkg/controller/common/cni/cni.go
Labels: okay to merge, size/XS

#1630 OSSM-5848 Added feature annotations
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/olm/clusterserviceversion.yaml
  chart/values.yaml
Labels: okay to merge, size/S, ok-to-test

#1632 Adding comment
  chart/values.yaml
Labels: okay to merge, size/XS

#1628 OSSM-5887 Make IstioRevision.spec.values strongly typed
  api/v1alpha1/common.go
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  api/v1alpha1/values_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  hack/download-charts.sh
  resources/gwAPIControllerMode/profiles/ambient.yaml
  resources/gwAPIControllerMode/profiles/default.yaml
  resources/gwAPIControllerMode/profiles/demo.yaml
  resources/gwAPIControllerMode/profiles/preview.yaml
  resources/latest/profiles/default.yaml
  resources/v1.19.6/profiles/ambient.yaml
  resources/v1.19.6/profiles/default.yaml
  resources/v1.19.6/profiles/demo.yaml
  resources/v1.19.6/profiles/preview.yaml
  resources/v1.20.1/profiles/ambient.yaml
  resources/v1.20.1/profiles/default.yaml
  resources/v1.20.1/profiles/demo.yaml
  resources/v1.20.1/profiles/preview.yaml
  resources/v1.20.2/profiles/ambient.yaml
  resources/v1.20.2/profiles/default.yaml
  resources/v1.20.2/profiles/demo.yaml
  resources/v1.20.2/profiles/preview.yaml
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
Labels: okay to merge, size/XXL

#1636 OSSM-5899 Add k8s-related fields to values
  api/v1alpha1/values_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  hack/download-charts.sh
  resources/v1.19.6/profiles/default.yaml
  resources/v1.20.1/profiles/default.yaml
  resources/v1.20.2/profiles/default.yaml
Labels: okay to merge, size/XXL

#1638 OSSM-5614 Add CEL validation to Istio and IstioRevision
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
Labels: okay to merge, size/L

#1644 Use the same copyright banner across all go files
  Makefile.core.mk
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  api/v1alpha1/meshconfig_deps_types.go
  api/v1alpha1/meshconfig_types.go
  api/v1alpha1/values_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istiorevision/istiorevision_controller.go
  hack/boilerplate.go.txt
  pkg/helm/charts.go
  tests/integration/api/suite_test.go
Labels: okay to merge, size/L

#1650 OSSM-5988 Skip go.mod updates until cachito has been updated
  go.mod
  go.sum
  tools/update_deps.sh
Labels: okay to merge, size/S

#1655 Fix gen-check
  resources/helm/v2.4/mesh-config/templates/telemetryv2_1.16.yaml
  resources/helm/v2.5/mesh-config/templates/telemetryv2_1.16.yaml
Labels: okay to merge, size/M
